// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type BulkUpdateIncidentMilestonesRequest struct {
	IncidentID                   string                                  `pathParam:"style=simple,explode=false,name=incident_id"`
	BulkUpdateIncidentMilestones components.BulkUpdateIncidentMilestones `request:"mediaType=application/json"`
}

func (b *BulkUpdateIncidentMilestonesRequest) GetIncidentID() string {
	if b == nil {
		return ""
	}
	return b.IncidentID
}

func (b *BulkUpdateIncidentMilestonesRequest) GetBulkUpdateIncidentMilestones() components.BulkUpdateIncidentMilestones {
	if b == nil {
		return components.BulkUpdateIncidentMilestones{}
	}
	return b.BulkUpdateIncidentMilestones
}
