// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type CloseIncidentRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (c *CloseIncidentRequest) GetIncidentID() string {
	if c == nil {
		return ""
	}
	return c.IncidentID
}
