// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type CreateChangeIdentityRequest struct {
	ChangeID             string                          `pathParam:"style=simple,explode=false,name=change_id"`
	CreateChangeIdentity components.CreateChangeIdentity `request:"mediaType=application/json"`
}

func (o *CreateChangeIdentityRequest) GetChangeID() string {
	if o == nil {
		return ""
	}
	return o.ChangeID
}

func (o *CreateChangeIdentityRequest) GetCreateChangeIdentity() components.CreateChangeIdentity {
	if o == nil {
		return components.CreateChangeIdentity{}
	}
	return o.CreateChangeIdentity
}
