// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type CreateLifecycleMeasurementDefinitionRequest struct {
	Name                string  `json:"name"`
	Slug                *string `json:"slug,omitempty"`
	Description         *string `json:"description,omitempty"`
	StartsAtMilestoneID string  `json:"starts_at_milestone_id"`
	EndsAtMilestoneID   string  `json:"ends_at_milestone_id"`
}

func (c *CreateLifecycleMeasurementDefinitionRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateLifecycleMeasurementDefinitionRequest) GetSlug() *string {
	if c == nil {
		return nil
	}
	return c.Slug
}

func (c *CreateLifecycleMeasurementDefinitionRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateLifecycleMeasurementDefinitionRequest) GetStartsAtMilestoneID() string {
	if c == nil {
		return ""
	}
	return c.StartsAtMilestoneID
}

func (c *CreateLifecycleMeasurementDefinitionRequest) GetEndsAtMilestoneID() string {
	if c == nil {
		return ""
	}
	return c.EndsAtMilestoneID
}
