// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateIncidentTaskRequest struct {
	IncidentID         string                        `pathParam:"style=simple,explode=false,name=incident_id"`
	CreateIncidentTask components.CreateIncidentTask `request:"mediaType=application/json"`
}

func (o *CreateIncidentTaskRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *CreateIncidentTaskRequest) GetCreateIncidentTask() components.CreateIncidentTask {
	if o == nil {
		return components.CreateIncidentTask{}
	}
	return o.CreateIncidentTask
}
