// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateTeamOnCallScheduleRequest struct {
	TeamID                   string                              `pathParam:"style=simple,explode=false,name=team_id"`
	CreateTeamOnCallSchedule components.CreateTeamOnCallSchedule `request:"mediaType=application/json"`
}

func (c *CreateTeamOnCallScheduleRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateTeamOnCallScheduleRequest) GetCreateTeamOnCallSchedule() components.CreateTeamOnCallSchedule {
	if c == nil {
		return components.CreateTeamOnCallSchedule{}
	}
	return c.CreateTeamOnCallSchedule
}
