// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateTeamCallRouteRequest struct {
	TeamID              string                         `pathParam:"style=simple,explode=false,name=team_id"`
	CreateTeamCallRoute components.CreateTeamCallRoute `request:"mediaType=application/json"`
}

func (c *CreateTeamCallRouteRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateTeamCallRouteRequest) GetCreateTeamCallRoute() components.CreateTeamCallRoute {
	if c == nil {
		return components.CreateTeamCallRoute{}
	}
	return c.CreateTeamCallRoute
}
