// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateOnCallScheduleRotationRequest struct {
	TeamID                       string                                  `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID                   string                                  `pathParam:"style=simple,explode=false,name=schedule_id"`
	CreateOnCallScheduleRotation components.CreateOnCallScheduleRotation `request:"mediaType=application/json"`
}

func (c *CreateOnCallScheduleRotationRequest) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}

func (c *CreateOnCallScheduleRotationRequest) GetScheduleID() string {
	if c == nil {
		return ""
	}
	return c.ScheduleID
}

func (c *CreateOnCallScheduleRotationRequest) GetCreateOnCallScheduleRotation() components.CreateOnCallScheduleRotation {
	if c == nil {
		return components.CreateOnCallScheduleRotation{}
	}
	return c.CreateOnCallScheduleRotation
}
