// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateIncidentTaskListRequest struct {
	IncidentID             string                            `pathParam:"style=simple,explode=false,name=incident_id"`
	CreateIncidentTaskList components.CreateIncidentTaskList `request:"mediaType=application/json"`
}

func (c *CreateIncidentTaskListRequest) GetIncidentID() string {
	if c == nil {
		return ""
	}
	return c.IncidentID
}

func (c *CreateIncidentTaskListRequest) GetCreateIncidentTaskList() components.CreateIncidentTaskList {
	if c == nil {
		return components.CreateIncidentTaskList{}
	}
	return c.CreateIncidentTaskList
}
