// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type CreateTeamSignalRuleRequest struct {
	TeamID               string                          `pathParam:"style=simple,explode=false,name=team_id"`
	CreateTeamSignalRule components.CreateTeamSignalRule `request:"mediaType=application/json"`
}

func (o *CreateTeamSignalRuleRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *CreateTeamSignalRuleRequest) GetCreateTeamSignalRule() components.CreateTeamSignalRule {
	if o == nil {
		return components.CreateTeamSignalRule{}
	}
	return o.CreateTeamSignalRule
}
