// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type CreateNuncLinkRequest struct {
	NuncConnectionID string `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
}

func (c *CreateNuncLinkRequest) GetNuncConnectionID() string {
	if c == nil {
		return ""
	}
	return c.NuncConnectionID
}
