// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type CreateTeamCallRouteRequest struct {
	TeamID              string                         `pathParam:"style=simple,explode=false,name=team_id"`
	CreateTeamCallRoute components.CreateTeamCallRoute `request:"mediaType=application/json"`
}

func (o *CreateTeamCallRouteRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *CreateTeamCallRouteRequest) GetCreateTeamCallRoute() components.CreateTeamCallRoute {
	if o == nil {
		return components.CreateTeamCallRoute{}
	}
	return o.CreateTeamCallRoute
}
