// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteCommentReactionRequest struct {
	ReactionID     string `pathParam:"style=simple,explode=false,name=reaction_id"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversation_id"`
	CommentID      string `pathParam:"style=simple,explode=false,name=comment_id"`
}

func (o *DeleteCommentReactionRequest) GetReactionID() string {
	if o == nil {
		return ""
	}
	return o.ReactionID
}

func (o *DeleteCommentReactionRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *DeleteCommentReactionRequest) GetCommentID() string {
	if o == nil {
		return ""
	}
	return o.CommentID
}
