// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteTicketRequest struct {
	TicketID string `pathParam:"style=simple,explode=false,name=ticket_id"`
}

func (o *DeleteTicketRequest) GetTicketID() string {
	if o == nil {
		return ""
	}
	return o.TicketID
}
