// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteScimUserRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteScimUserRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
