// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteIncidentTaskRequest struct {
	TaskID     string `pathParam:"style=simple,explode=false,name=task_id"`
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (d *DeleteIncidentTaskRequest) GetTaskID() string {
	if d == nil {
		return ""
	}
	return d.TaskID
}

func (d *DeleteIncidentTaskRequest) GetIncidentID() string {
	if d == nil {
		return ""
	}
	return d.IncidentID
}
