// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteNuncLinkRequest struct {
	NuncConnectionID string `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	LinkID           string `pathParam:"style=simple,explode=false,name=link_id"`
}

func (o *DeleteNuncLinkRequest) GetNuncConnectionID() string {
	if o == nil {
		return ""
	}
	return o.NuncConnectionID
}

func (o *DeleteNuncLinkRequest) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}
