// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteSignalsEventSourceRequest struct {
	TransposerSlug string `pathParam:"style=simple,explode=false,name=transposer_slug"`
}

func (o *DeleteSignalsEventSourceRequest) GetTransposerSlug() string {
	if o == nil {
		return ""
	}
	return o.TransposerSlug
}
