// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteSeverityMatrixConditionRequest struct {
	ConditionID string `pathParam:"style=simple,explode=false,name=condition_id"`
}

func (d *DeleteSeverityMatrixConditionRequest) GetConditionID() string {
	if d == nil {
		return ""
	}
	return d.ConditionID
}
