// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteScheduledMaintenanceRequest struct {
	ScheduledMaintenanceID string `pathParam:"style=simple,explode=false,name=scheduled_maintenance_id"`
}

func (o *DeleteScheduledMaintenanceRequest) GetScheduledMaintenanceID() string {
	if o == nil {
		return ""
	}
	return o.ScheduledMaintenanceID
}
