// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteNuncComponentGroupRequest struct {
	NuncConnectionID string `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	GroupID          string `pathParam:"style=simple,explode=false,name=group_id"`
}

func (d *DeleteNuncComponentGroupRequest) GetNuncConnectionID() string {
	if d == nil {
		return ""
	}
	return d.NuncConnectionID
}

func (d *DeleteNuncComponentGroupRequest) GetGroupID() string {
	if d == nil {
		return ""
	}
	return d.GroupID
}
