// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteEnvironmentRequest struct {
	// Environment UUID or slug
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
}

func (d *DeleteEnvironmentRequest) GetEnvironmentID() string {
	if d == nil {
		return ""
	}
	return d.EnvironmentID
}
