// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteEmailSubscriberRequest struct {
	NuncConnectionID string `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	// A list of subscriber IDs to unsubscribe.
	SubscriberIds string `queryParam:"style=form,explode=true,name=subscriber_ids"`
}

func (o *DeleteEmailSubscriberRequest) GetNuncConnectionID() string {
	if o == nil {
		return ""
	}
	return o.NuncConnectionID
}

func (o *DeleteEmailSubscriberRequest) GetSubscriberIds() string {
	if o == nil {
		return ""
	}
	return o.SubscriberIds
}
