// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteSlackEmojiActionRequest struct {
	// Slack Connection UUID
	ConnectionID  string `pathParam:"style=simple,explode=false,name=connection_id"`
	EmojiActionID string `pathParam:"style=simple,explode=false,name=emoji_action_id"`
}

func (o *DeleteSlackEmojiActionRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *DeleteSlackEmojiActionRequest) GetEmojiActionID() string {
	if o == nil {
		return ""
	}
	return o.EmojiActionID
}
