// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteCommentRequest struct {
	CommentID      string `pathParam:"style=simple,explode=false,name=comment_id"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversation_id"`
}

func (d *DeleteCommentRequest) GetCommentID() string {
	if d == nil {
		return ""
	}
	return d.CommentID
}

func (d *DeleteCommentRequest) GetConversationID() string {
	if d == nil {
		return ""
	}
	return d.ConversationID
}
