// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteTicketingProjectConfigRequest struct {
	TicketingProjectID string `pathParam:"style=simple,explode=false,name=ticketing_project_id"`
	ConfigID           string `pathParam:"style=simple,explode=false,name=config_id"`
}

func (d *DeleteTicketingProjectConfigRequest) GetTicketingProjectID() string {
	if d == nil {
		return ""
	}
	return d.TicketingProjectID
}

func (d *DeleteTicketingProjectConfigRequest) GetConfigID() string {
	if d == nil {
		return ""
	}
	return d.ConfigID
}
