// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteOnCallShiftRequest struct {
	ID         string `pathParam:"style=simple,explode=false,name=id"`
	TeamID     string `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule_id"`
}

func (d *DeleteOnCallShiftRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteOnCallShiftRequest) GetTeamID() string {
	if d == nil {
		return ""
	}
	return d.TeamID
}

func (d *DeleteOnCallShiftRequest) GetScheduleID() string {
	if d == nil {
		return ""
	}
	return d.ScheduleID
}
