// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteChangeEventRequest struct {
	ChangeEventID string `pathParam:"style=simple,explode=false,name=change_event_id"`
}

func (o *DeleteChangeEventRequest) GetChangeEventID() string {
	if o == nil {
		return ""
	}
	return o.ChangeEventID
}
