// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteRunbookRequest struct {
	RunbookID string `pathParam:"style=simple,explode=false,name=runbook_id"`
}

func (d *DeleteRunbookRequest) GetRunbookID() string {
	if d == nil {
		return ""
	}
	return d.RunbookID
}
