// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteCommentReactionRequest struct {
	ReactionID     string `pathParam:"style=simple,explode=false,name=reaction_id"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversation_id"`
	CommentID      string `pathParam:"style=simple,explode=false,name=comment_id"`
}

func (d *DeleteCommentReactionRequest) GetReactionID() string {
	if d == nil {
		return ""
	}
	return d.ReactionID
}

func (d *DeleteCommentReactionRequest) GetConversationID() string {
	if d == nil {
		return ""
	}
	return d.ConversationID
}

func (d *DeleteCommentReactionRequest) GetCommentID() string {
	if d == nil {
		return ""
	}
	return d.CommentID
}
