// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeletePostMortemReasonRequest struct {
	ReportID string `pathParam:"style=simple,explode=false,name=report_id"`
	ReasonID string `pathParam:"style=simple,explode=false,name=reason_id"`
}

func (d *DeletePostMortemReasonRequest) GetReportID() string {
	if d == nil {
		return ""
	}
	return d.ReportID
}

func (d *DeletePostMortemReasonRequest) GetReasonID() string {
	if d == nil {
		return ""
	}
	return d.ReasonID
}
