// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteChangeRequest struct {
	ChangeID string `pathParam:"style=simple,explode=false,name=change_id"`
}

func (d *DeleteChangeRequest) GetChangeID() string {
	if d == nil {
		return ""
	}
	return d.ChangeID
}
