// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteChangeIdentityRequest struct {
	IdentityID string `pathParam:"style=simple,explode=false,name=identity_id"`
	ChangeID   string `pathParam:"style=simple,explode=false,name=change_id"`
}

func (o *DeleteChangeIdentityRequest) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

func (o *DeleteChangeIdentityRequest) GetChangeID() string {
	if o == nil {
		return ""
	}
	return o.ChangeID
}
