// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteIncidentRetrospectiveDynamicInputRequest struct {
	RetrospectiveID string `pathParam:"style=simple,explode=false,name=retrospective_id"`
	FieldID         string `pathParam:"style=simple,explode=false,name=field_id"`
	// The ID of the dynamic input field to delete.
	DynamicInputFieldID string `queryParam:"style=form,explode=true,name=dynamic_input_field_id"`
	IncidentID          string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *DeleteIncidentRetrospectiveDynamicInputRequest) GetRetrospectiveID() string {
	if o == nil {
		return ""
	}
	return o.RetrospectiveID
}

func (o *DeleteIncidentRetrospectiveDynamicInputRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

func (o *DeleteIncidentRetrospectiveDynamicInputRequest) GetDynamicInputFieldID() string {
	if o == nil {
		return ""
	}
	return o.DynamicInputFieldID
}

func (o *DeleteIncidentRetrospectiveDynamicInputRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}
