// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteWebhookRequest struct {
	WebhookID string `pathParam:"style=simple,explode=false,name=webhook_id"`
}

func (o *DeleteWebhookRequest) GetWebhookID() string {
	if o == nil {
		return ""
	}
	return o.WebhookID
}
