// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteTeamOnCallScheduleRequest struct {
	TeamID     string `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule_id"`
}

func (o *DeleteTeamOnCallScheduleRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *DeleteTeamOnCallScheduleRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}
