// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteSlackEmojiActionRequest struct {
	// Slack Connection UUID
	ConnectionID  string `pathParam:"style=simple,explode=false,name=connection_id"`
	EmojiActionID string `pathParam:"style=simple,explode=false,name=emoji_action_id"`
}

func (d *DeleteSlackEmojiActionRequest) GetConnectionID() string {
	if d == nil {
		return ""
	}
	return d.ConnectionID
}

func (d *DeleteSlackEmojiActionRequest) GetEmojiActionID() string {
	if d == nil {
		return ""
	}
	return d.EmojiActionID
}
