// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
)

type DeleteIncidentImpactType string

const (
	DeleteIncidentImpactTypeEnvironments    DeleteIncidentImpactType = "environments"
	DeleteIncidentImpactTypeFunctionalities DeleteIncidentImpactType = "functionalities"
	DeleteIncidentImpactTypeServices        DeleteIncidentImpactType = "services"
	DeleteIncidentImpactTypeCustomers       DeleteIncidentImpactType = "customers"
)

func (e DeleteIncidentImpactType) ToPointer() *DeleteIncidentImpactType {
	return &e
}
func (e *DeleteIncidentImpactType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "environments":
		fallthrough
	case "functionalities":
		fallthrough
	case "services":
		fallthrough
	case "customers":
		*e = DeleteIncidentImpactType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteIncidentImpactType: %v", v)
	}
}

type DeleteIncidentImpactRequest struct {
	IncidentID string                   `pathParam:"style=simple,explode=false,name=incident_id"`
	Type       DeleteIncidentImpactType `pathParam:"style=simple,explode=false,name=type"`
	ID         string                   `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteIncidentImpactRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *DeleteIncidentImpactRequest) GetType() DeleteIncidentImpactType {
	if o == nil {
		return DeleteIncidentImpactType("")
	}
	return o.Type
}

func (o *DeleteIncidentImpactRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
