// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type ExportSignalsShiftAnalyticsRequestBody struct {
	// Array of user IDs to fetch oncall hours for
	UserIds []string `multipartForm:"name=user_ids"`
	// Array of team IDs to fetch oncall hours for
	TeamIds []string `multipartForm:"name=team_ids"`
}

func (o *ExportSignalsShiftAnalyticsRequestBody) GetUserIds() []string {
	if o == nil {
		return nil
	}
	return o.UserIds
}

func (o *ExportSignalsShiftAnalyticsRequestBody) GetTeamIds() []string {
	if o == nil {
		return nil
	}
	return o.TeamIds
}

type ExportSignalsShiftAnalyticsRequest struct {
	// Start of the period to fetch hours for (UTC)
	PeriodStart time.Time `queryParam:"style=form,explode=true,name=period_start"`
	// End of the period to fetch hours for (UTC)
	PeriodEnd   time.Time                               `queryParam:"style=form,explode=true,name=period_end"`
	RequestBody *ExportSignalsShiftAnalyticsRequestBody `request:"mediaType=multipart/form-data"`
}

func (e ExportSignalsShiftAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportSignalsShiftAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ExportSignalsShiftAnalyticsRequest) GetPeriodStart() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PeriodStart
}

func (o *ExportSignalsShiftAnalyticsRequest) GetPeriodEnd() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PeriodEnd
}

func (o *ExportSignalsShiftAnalyticsRequest) GetRequestBody() *ExportSignalsShiftAnalyticsRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}
