// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type ExportSignalsShiftAnalyticsRequest struct {
	// Array of user IDs to fetch oncall hours for
	UserIds []string `queryParam:"style=form,explode=false,name=user_ids"`
	// Array of team IDs to fetch oncall hours for
	TeamIds []string `queryParam:"style=form,explode=false,name=team_ids"`
	// Start of the period to fetch hours for (UTC)
	PeriodStart time.Time `queryParam:"style=form,explode=true,name=period_start"`
	// End of the period to fetch hours for (UTC)
	PeriodEnd time.Time `queryParam:"style=form,explode=true,name=period_end"`
}

func (e ExportSignalsShiftAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportSignalsShiftAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExportSignalsShiftAnalyticsRequest) GetUserIds() []string {
	if e == nil {
		return nil
	}
	return e.UserIds
}

func (e *ExportSignalsShiftAnalyticsRequest) GetTeamIds() []string {
	if e == nil {
		return nil
	}
	return e.TeamIds
}

func (e *ExportSignalsShiftAnalyticsRequest) GetPeriodStart() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.PeriodStart
}

func (e *ExportSignalsShiftAnalyticsRequest) GetPeriodEnd() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.PeriodEnd
}
