// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type GenerateAudienceSummaryRequestBody struct {
	// Whether to force regeneration of the summary
	ForceRegenerate *bool `default:"true" json:"force_regenerate"`
}

func (g GenerateAudienceSummaryRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenerateAudienceSummaryRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GenerateAudienceSummaryRequestBody) GetForceRegenerate() *bool {
	if g == nil {
		return nil
	}
	return g.ForceRegenerate
}

type GenerateAudienceSummaryRequest struct {
	// Unique identifier of the audience
	AudienceID string `pathParam:"style=simple,explode=false,name=audience_id"`
	// Unique identifier of the incident to summarize
	IncidentID  string                              `pathParam:"style=simple,explode=false,name=incident_id"`
	RequestBody *GenerateAudienceSummaryRequestBody `request:"mediaType=application/json"`
}

func (g *GenerateAudienceSummaryRequest) GetAudienceID() string {
	if g == nil {
		return ""
	}
	return g.AudienceID
}

func (g *GenerateAudienceSummaryRequest) GetIncidentID() string {
	if g == nil {
		return ""
	}
	return g.IncidentID
}

func (g *GenerateAudienceSummaryRequest) GetRequestBody() *GenerateAudienceSummaryRequestBody {
	if g == nil {
		return nil
	}
	return g.RequestBody
}
