// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAudienceRequest struct {
	// Unique identifier of the audience
	AudienceID string `pathParam:"style=simple,explode=false,name=audience_id"`
}

func (o *GetAudienceRequest) GetAudienceID() string {
	if o == nil {
		return ""
	}
	return o.AudienceID
}
