// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAudienceSummaryRequest struct {
	// Unique identifier of the audience
	AudienceID string `pathParam:"style=simple,explode=false,name=audience_id"`
	// Unique identifier of the incident to summarize
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *GetAudienceSummaryRequest) GetAudienceID() string {
	if o == nil {
		return ""
	}
	return o.AudienceID
}

func (o *GetAudienceSummaryRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}
