// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAudienceRequest struct {
	// Unique identifier of the audience
	AudienceID string `pathParam:"style=simple,explode=false,name=audience_id"`
}

func (g *GetAudienceRequest) GetAudienceID() string {
	if g == nil {
		return ""
	}
	return g.AudienceID
}
