// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConferenceBridgeTranslationRequest struct {
	// The ID of the conference bridge
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The language code of the translation
	LanguageCode string `pathParam:"style=simple,explode=false,name=language_code"`
	IncidentID   string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (g *GetConferenceBridgeTranslationRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetConferenceBridgeTranslationRequest) GetLanguageCode() string {
	if g == nil {
		return ""
	}
	return g.LanguageCode
}

func (g *GetConferenceBridgeTranslationRequest) GetIncidentID() string {
	if g == nil {
		return ""
	}
	return g.IncidentID
}
