// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConfigurationOptionsRequest struct {
	TicketingProjectID string `pathParam:"style=simple,explode=false,name=ticketing_project_id"`
}

func (g *GetConfigurationOptionsRequest) GetTicketingProjectID() string {
	if g == nil {
		return ""
	}
	return g.TicketingProjectID
}
