// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetIntegrationRequest struct {
	// Integration UUID
	IntegrationID string `pathParam:"style=simple,explode=false,name=integration_id"`
}

func (o *GetIntegrationRequest) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}
