// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetIncidentRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (g *GetIncidentRequest) GetIncidentID() string {
	if g == nil {
		return ""
	}
	return g.IncidentID
}
