// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetInboundFieldMapRequest struct {
	MapID              string `pathParam:"style=simple,explode=false,name=map_id"`
	TicketingProjectID string `pathParam:"style=simple,explode=false,name=ticketing_project_id"`
}

func (g *GetInboundFieldMapRequest) GetMapID() string {
	if g == nil {
		return ""
	}
	return g.MapID
}

func (g *GetInboundFieldMapRequest) GetTicketingProjectID() string {
	if g == nil {
		return ""
	}
	return g.TicketingProjectID
}
