// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetIncidentRetrospectiveFieldRequest struct {
	RetrospectiveID string `pathParam:"style=simple,explode=false,name=retrospective_id"`
	FieldID         string `pathParam:"style=simple,explode=false,name=field_id"`
	IncidentID      string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *GetIncidentRetrospectiveFieldRequest) GetRetrospectiveID() string {
	if o == nil {
		return ""
	}
	return o.RetrospectiveID
}

func (o *GetIncidentRetrospectiveFieldRequest) GetFieldID() string {
	if o == nil {
		return ""
	}
	return o.FieldID
}

func (o *GetIncidentRetrospectiveFieldRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}
