// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetRunbookExecutionRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (o *GetRunbookExecutionRequest) GetExecutionID() string {
	if o == nil {
		return ""
	}
	return o.ExecutionID
}
