// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetRetrospectiveTemplateRequest struct {
	RetrospectiveTemplateID string `pathParam:"style=simple,explode=false,name=retrospective_template_id"`
}

func (o *GetRetrospectiveTemplateRequest) GetRetrospectiveTemplateID() string {
	if o == nil {
		return ""
	}
	return o.RetrospectiveTemplateID
}
