// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetRunbookExecutionRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
}

func (g *GetRunbookExecutionRequest) GetExecutionID() string {
	if g == nil {
		return ""
	}
	return g.ExecutionID
}
