// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetScheduledMaintenanceRequest struct {
	ScheduledMaintenanceID string `pathParam:"style=simple,explode=false,name=scheduled_maintenance_id"`
}

func (g *GetScheduledMaintenanceRequest) GetScheduledMaintenanceID() string {
	if g == nil {
		return ""
	}
	return g.ScheduledMaintenanceID
}
