// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetStatuspageConnectionRequest struct {
	// Connection UUID
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (g *GetStatuspageConnectionRequest) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}
