// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetSeverityMatrixConditionRequest struct {
	ConditionID string `pathParam:"style=simple,explode=false,name=condition_id"`
}

func (g *GetSeverityMatrixConditionRequest) GetConditionID() string {
	if g == nil {
		return ""
	}
	return g.ConditionID
}
