// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetStatusUpdateTemplateRequest struct {
	StatusUpdateTemplateID string `pathParam:"style=simple,explode=false,name=status_update_template_id"`
}

func (g *GetStatusUpdateTemplateRequest) GetStatusUpdateTemplateID() string {
	if g == nil {
		return ""
	}
	return g.StatusUpdateTemplateID
}
