// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetTaskListRequest struct {
	TaskListID string `pathParam:"style=simple,explode=false,name=task_list_id"`
}

func (o *GetTaskListRequest) GetTaskListID() string {
	if o == nil {
		return ""
	}
	return o.TaskListID
}
