// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetTeamOnCallScheduleRequest struct {
	TeamID     string `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule_id"`
	// An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window. If provided, only shifts that end at or after this time will be included.
	ShiftTimeWindowStart *string `queryParam:"style=form,explode=true,name=shift_time_window_start"`
	// An optional ISO8601 timestamp for filtering the shifts listed in each on-call schedule to only include shifts that overlap with the provided time window.. If provided, only shifts that start at or before this time will be included.
	ShiftTimeWindowEnd *string `queryParam:"style=form,explode=true,name=shift_time_window_end"`
}

func (g *GetTeamOnCallScheduleRequest) GetTeamID() string {
	if g == nil {
		return ""
	}
	return g.TeamID
}

func (g *GetTeamOnCallScheduleRequest) GetScheduleID() string {
	if g == nil {
		return ""
	}
	return g.ScheduleID
}

func (g *GetTeamOnCallScheduleRequest) GetShiftTimeWindowStart() *string {
	if g == nil {
		return nil
	}
	return g.ShiftTimeWindowStart
}

func (g *GetTeamOnCallScheduleRequest) GetShiftTimeWindowEnd() *string {
	if g == nil {
		return nil
	}
	return g.ShiftTimeWindowEnd
}
