// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetTicketingPriorityRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetTicketingPriorityRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
