// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetTeamSignalRuleRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
	ID     string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetTeamSignalRuleRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *GetTeamSignalRuleRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
