// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetVoteStatusRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
	EventID    string `pathParam:"style=simple,explode=false,name=event_id"`
}

func (g *GetVoteStatusRequest) GetIncidentID() string {
	if g == nil {
		return ""
	}
	return g.IncidentID
}

func (g *GetVoteStatusRequest) GetEventID() string {
	if g == nil {
		return ""
	}
	return g.EventID
}
