// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetZendeskCustomerSupportIssueRequest struct {
	// Zendesk ticket ID
	TicketID string `queryParam:"style=form,explode=true,name=ticket_id"`
	// Use to include attached_incidents
	Include *string `queryParam:"style=form,explode=true,name=include"`
}

func (g *GetZendeskCustomerSupportIssueRequest) GetTicketID() string {
	if g == nil {
		return ""
	}
	return g.TicketID
}

func (g *GetZendeskCustomerSupportIssueRequest) GetInclude() *string {
	if g == nil {
		return nil
	}
	return g.Include
}
