// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type IngestCatalogDataRequest struct {
	CatalogID         string                       `pathParam:"style=simple,explode=false,name=catalog_id"`
	IngestCatalogData components.IngestCatalogData `request:"mediaType=application/json"`
}

func (i *IngestCatalogDataRequest) GetCatalogID() string {
	if i == nil {
		return ""
	}
	return i.CatalogID
}

func (i *IngestCatalogDataRequest) GetIngestCatalogData() components.IngestCatalogData {
	if i == nil {
		return components.IngestCatalogData{}
	}
	return i.IngestCatalogData
}
