// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListRunbookActionsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// List actions supporting this specific Runbook type
	Type *string `queryParam:"style=form,explode=true,name=type"`
	// Boolean to determine whether to return a slimified version of the action object's integration
	Lite *bool `queryParam:"style=form,explode=true,name=lite"`
}

func (l *ListRunbookActionsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListRunbookActionsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListRunbookActionsRequest) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListRunbookActionsRequest) GetLite() *bool {
	if l == nil {
		return nil
	}
	return l.Lite
}
