// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListStatuspageConnectionPagesRequest struct {
	// Connection UUID
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (o *ListStatuspageConnectionPagesRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}
