// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListAvailableTicketingFieldMapsRequest struct {
	TicketingProjectID string `pathParam:"style=simple,explode=false,name=ticketing_project_id"`
}

func (l *ListAvailableTicketingFieldMapsRequest) GetTicketingProjectID() string {
	if l == nil {
		return ""
	}
	return l.TicketingProjectID
}
