// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// ListTranscriptEntriesSort - The order to sort the transcript entries.
type ListTranscriptEntriesSort string

const (
	ListTranscriptEntriesSortAsc  ListTranscriptEntriesSort = "asc"
	ListTranscriptEntriesSortDesc ListTranscriptEntriesSort = "desc"
)

func (e ListTranscriptEntriesSort) ToPointer() *ListTranscriptEntriesSort {
	return &e
}
func (e *ListTranscriptEntriesSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListTranscriptEntriesSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListTranscriptEntriesSort: %v", v)
	}
}

type ListTranscriptEntriesRequest struct {
	// The ID of the transcript entry to start after.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// The ID of the transcript entry to start before.
	Before *string `queryParam:"style=form,explode=true,name=before"`
	// The order to sort the transcript entries.
	Sort       *ListTranscriptEntriesSort `default:"asc" queryParam:"style=form,explode=true,name=sort"`
	IncidentID string                     `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (l ListTranscriptEntriesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTranscriptEntriesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"incident_id"}); err != nil {
		return err
	}
	return nil
}

func (l *ListTranscriptEntriesRequest) GetAfter() *string {
	if l == nil {
		return nil
	}
	return l.After
}

func (l *ListTranscriptEntriesRequest) GetBefore() *string {
	if l == nil {
		return nil
	}
	return l.Before
}

func (l *ListTranscriptEntriesRequest) GetSort() *ListTranscriptEntriesSort {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListTranscriptEntriesRequest) GetIncidentID() string {
	if l == nil {
		return ""
	}
	return l.IncidentID
}
