// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type ListAudiencesRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// Include archived (discarded) audiences
	IncludeArchived *bool `default:"false" queryParam:"style=form,explode=true,name=include_archived"`
}

func (l ListAudiencesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAudiencesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAudiencesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAudiencesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListAudiencesRequest) GetIncludeArchived() *bool {
	if l == nil {
		return nil
	}
	return l.IncludeArchived
}
