// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListSignalsEmailTargetsRequest struct {
	// A query string to search the list of targets by.
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

func (o *ListSignalsEmailTargetsRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}
