// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListChangeIdentitiesRequest struct {
	Page     *int   `queryParam:"style=form,explode=true,name=page"`
	PerPage  *int   `queryParam:"style=form,explode=true,name=per_page"`
	ChangeID string `pathParam:"style=simple,explode=false,name=change_id"`
}

func (l *ListChangeIdentitiesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListChangeIdentitiesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListChangeIdentitiesRequest) GetChangeID() string {
	if l == nil {
		return ""
	}
	return l.ChangeID
}
