// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListIncidentStatusPagesRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (l *ListIncidentStatusPagesRequest) GetIncidentID() string {
	if l == nil {
		return ""
	}
	return l.IncidentID
}
