// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListRolesRequest struct {
	// A search query to filter roles by name and slug.
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListRolesRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListRolesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListRolesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
