// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListTeamCallRoutesRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
}

func (l *ListTeamCallRoutesRequest) GetTeamID() string {
	if l == nil {
		return ""
	}
	return l.TeamID
}
