// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListEnvironmentsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// A query to search environments by their name or description
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// A query to search environments by their name
	Name *string `queryParam:"style=form,explode=true,name=name"`
}

func (o *ListEnvironmentsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListEnvironmentsRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *ListEnvironmentsRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListEnvironmentsRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
