// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListTeamEscalationPoliciesRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=team_id"`
	// A query string for searching through the list of escalation policies.
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListTeamEscalationPoliciesRequest) GetTeamID() string {
	if l == nil {
		return ""
	}
	return l.TeamID
}

func (l *ListTeamEscalationPoliciesRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListTeamEscalationPoliciesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTeamEscalationPoliciesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
