// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
)

type ListSavedSearchesResourceType string

const (
	ListSavedSearchesResourceTypeChangeEvents          ListSavedSearchesResourceType = "change_events"
	ListSavedSearchesResourceTypeIncidents             ListSavedSearchesResourceType = "incidents"
	ListSavedSearchesResourceTypeServices              ListSavedSearchesResourceType = "services"
	ListSavedSearchesResourceTypeScheduledMaintenances ListSavedSearchesResourceType = "scheduled_maintenances"
	ListSavedSearchesResourceTypeTicketTasks           ListSavedSearchesResourceType = "ticket_tasks"
	ListSavedSearchesResourceTypeTicketFollowUps       ListSavedSearchesResourceType = "ticket_follow_ups"
	ListSavedSearchesResourceTypeAnalytics             ListSavedSearchesResourceType = "analytics"
	ListSavedSearchesResourceTypeImpactAnalytics       ListSavedSearchesResourceType = "impact_analytics"
	ListSavedSearchesResourceTypeAlerts                ListSavedSearchesResourceType = "alerts"
	ListSavedSearchesResourceTypeIncidentEvents        ListSavedSearchesResourceType = "incident_events"
)

func (e ListSavedSearchesResourceType) ToPointer() *ListSavedSearchesResourceType {
	return &e
}
func (e *ListSavedSearchesResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "change_events":
		fallthrough
	case "incidents":
		fallthrough
	case "services":
		fallthrough
	case "scheduled_maintenances":
		fallthrough
	case "ticket_tasks":
		fallthrough
	case "ticket_follow_ups":
		fallthrough
	case "analytics":
		fallthrough
	case "impact_analytics":
		fallthrough
	case "alerts":
		fallthrough
	case "incident_events":
		*e = ListSavedSearchesResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSavedSearchesResourceType: %v", v)
	}
}

type ListSavedSearchesRequest struct {
	ResourceType ListSavedSearchesResourceType `pathParam:"style=simple,explode=false,name=resource_type"`
	// The user ID used to filter saved searches.
	UserID *string `queryParam:"style=form,explode=true,name=user_id"`
	// Filter saved searches with a query on their name
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListSavedSearchesRequest) GetResourceType() ListSavedSearchesResourceType {
	if o == nil {
		return ListSavedSearchesResourceType("")
	}
	return o.ResourceType
}

func (o *ListSavedSearchesRequest) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *ListSavedSearchesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListSavedSearchesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListSavedSearchesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}
