// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListSchedulesRequest struct {
	// Filter schedules with a query on their name
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListSchedulesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListSchedulesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListSchedulesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}
