// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListAwsConnectionsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// AWS account ID containing the role to be assumed
	AwsAccountID *string `queryParam:"style=form,explode=true,name=aws_account_id"`
	// ARN of the role to be assumed
	TargetArn *string `queryParam:"style=form,explode=true,name=target_arn"`
	// The external ID supplied when assuming the role
	ExternalID *string `queryParam:"style=form,explode=true,name=external_id"`
}

func (l *ListAwsConnectionsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAwsConnectionsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListAwsConnectionsRequest) GetAwsAccountID() *string {
	if l == nil {
		return nil
	}
	return l.AwsAccountID
}

func (l *ListAwsConnectionsRequest) GetTargetArn() *string {
	if l == nil {
		return nil
	}
	return l.TargetArn
}

func (l *ListAwsConnectionsRequest) GetExternalID() *string {
	if l == nil {
		return nil
	}
	return l.ExternalID
}
