// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListServiceEnvironmentsRequest struct {
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	Page      *int   `queryParam:"style=form,explode=true,name=page"`
	PerPage   *int   `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListServiceEnvironmentsRequest) GetServiceID() string {
	if l == nil {
		return ""
	}
	return l.ServiceID
}

func (l *ListServiceEnvironmentsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListServiceEnvironmentsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
