// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListIncidentTasksRequest struct {
	Page       *int   `queryParam:"style=form,explode=true,name=page"`
	PerPage    *int   `queryParam:"style=form,explode=true,name=per_page"`
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (l *ListIncidentTasksRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListIncidentTasksRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListIncidentTasksRequest) GetIncidentID() string {
	if l == nil {
		return ""
	}
	return l.IncidentID
}
