// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"github.com/firehydrant/firehydrant-go-sdk/types"
)

type ListInfrastructureTypeMetricsInfraType string

const (
	ListInfrastructureTypeMetricsInfraTypeEnvironments    ListInfrastructureTypeMetricsInfraType = "environments"
	ListInfrastructureTypeMetricsInfraTypeFunctionalities ListInfrastructureTypeMetricsInfraType = "functionalities"
	ListInfrastructureTypeMetricsInfraTypeServices        ListInfrastructureTypeMetricsInfraType = "services"
	ListInfrastructureTypeMetricsInfraTypeCustomers       ListInfrastructureTypeMetricsInfraType = "customers"
)

func (e ListInfrastructureTypeMetricsInfraType) ToPointer() *ListInfrastructureTypeMetricsInfraType {
	return &e
}
func (e *ListInfrastructureTypeMetricsInfraType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "environments":
		fallthrough
	case "functionalities":
		fallthrough
	case "services":
		fallthrough
	case "customers":
		*e = ListInfrastructureTypeMetricsInfraType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListInfrastructureTypeMetricsInfraType: %v", v)
	}
}

type ListInfrastructureTypeMetricsRequest struct {
	InfraType ListInfrastructureTypeMetricsInfraType `pathParam:"style=simple,explode=false,name=infra_type"`
	// The start date to return metrics from; defaults to 30 days ago
	StartDate *types.Date `queryParam:"style=form,explode=true,name=start_date"`
	// The end date to return metrics from, defaults to today
	EndDate *types.Date `queryParam:"style=form,explode=true,name=end_date"`
}

func (l ListInfrastructureTypeMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInfrastructureTypeMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInfrastructureTypeMetricsRequest) GetInfraType() ListInfrastructureTypeMetricsInfraType {
	if l == nil {
		return ListInfrastructureTypeMetricsInfraType("")
	}
	return l.InfraType
}

func (l *ListInfrastructureTypeMetricsRequest) GetStartDate() *types.Date {
	if l == nil {
		return nil
	}
	return l.StartDate
}

func (l *ListInfrastructureTypeMetricsRequest) GetEndDate() *types.Date {
	if l == nil {
		return nil
	}
	return l.EndDate
}
