// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListSlackEmojiActionsRequest struct {
	// Slack Connection UUID
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	Page         *int   `queryParam:"style=form,explode=true,name=page"`
	PerPage      *int   `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListSlackEmojiActionsRequest) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListSlackEmojiActionsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSlackEmojiActionsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
