// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListIncidentAttachmentsRequest struct {
	IncidentID     string  `pathParam:"style=simple,explode=false,name=incident_id"`
	AttachableType *string `queryParam:"style=form,explode=true,name=attachable_type"`
	Page           *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage        *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListIncidentAttachmentsRequest) GetIncidentID() string {
	if l == nil {
		return ""
	}
	return l.IncidentID
}

func (l *ListIncidentAttachmentsRequest) GetAttachableType() *string {
	if l == nil {
		return nil
	}
	return l.AttachableType
}

func (l *ListIncidentAttachmentsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListIncidentAttachmentsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
