// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListWebhooksRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListWebhooksRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListWebhooksRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}
