// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListIncidentRetrospectivesRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// Filter by hidden status.
	IsHidden   *bool  `queryParam:"style=form,explode=true,name=is_hidden"`
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (l *ListIncidentRetrospectivesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListIncidentRetrospectivesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListIncidentRetrospectivesRequest) GetIsHidden() *bool {
	if l == nil {
		return nil
	}
	return l.IsHidden
}

func (l *ListIncidentRetrospectivesRequest) GetIncidentID() string {
	if l == nil {
		return ""
	}
	return l.IncidentID
}
