// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListIncidentTagsRequest struct {
	Prefix *string `queryParam:"style=form,explode=true,name=prefix"`
}

func (l *ListIncidentTagsRequest) GetPrefix() *string {
	if l == nil {
		return nil
	}
	return l.Prefix
}
