// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListScheduledMaintenancesRequest struct {
	// Filter scheduled_maintenances with a query on their name
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Page    *int    `queryParam:"style=form,explode=true,name=page"`
	PerPage *int    `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListScheduledMaintenancesRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListScheduledMaintenancesRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListScheduledMaintenancesRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
