// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListSignalsEventSourcesRequest struct {
	// Team ID to send signals to directly
	TeamID *string `queryParam:"style=form,explode=true,name=team_id"`
	// Escalation policy ID to send signals to directly. `team_id` is required if this is provided.
	EscalationPolicyID *string `queryParam:"style=form,explode=true,name=escalation_policy_id"`
	// On-call schedule ID to send signals to directly. `team_id` is required if this is provided.
	OnCallScheduleID *string `queryParam:"style=form,explode=true,name=on_call_schedule_id"`
	// User ID to send signals to directly
	UserID *string `queryParam:"style=form,explode=true,name=user_id"`
}

func (l *ListSignalsEventSourcesRequest) GetTeamID() *string {
	if l == nil {
		return nil
	}
	return l.TeamID
}

func (l *ListSignalsEventSourcesRequest) GetEscalationPolicyID() *string {
	if l == nil {
		return nil
	}
	return l.EscalationPolicyID
}

func (l *ListSignalsEventSourcesRequest) GetOnCallScheduleID() *string {
	if l == nil {
		return nil
	}
	return l.OnCallScheduleID
}

func (l *ListSignalsEventSourcesRequest) GetUserID() *string {
	if l == nil {
		return nil
	}
	return l.UserID
}
