// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListAwsCloudtrailBatchesRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// AWS connection ID
	ConnectionID *string `queryParam:"style=form,explode=true,name=connection_id"`
}

func (o *ListAwsCloudtrailBatchesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListAwsCloudtrailBatchesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *ListAwsCloudtrailBatchesRequest) GetConnectionID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionID
}
