// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListSeverityMatrixImpactsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
}

func (l *ListSeverityMatrixImpactsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSeverityMatrixImpactsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}
