// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListTeamsRequest struct {
	Page    *int `queryParam:"style=form,explode=true,name=page"`
	PerPage *int `queryParam:"style=form,explode=true,name=per_page"`
	// A query to search teams by their name or description
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// A query to search teams by their name
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// A comma separated list of service IDs
	Services *string `queryParam:"style=form,explode=true,name=services"`
	// Filter by teams that have or do not have members with a default incident role asssigned. Value may be 'present', 'blank', or the ID of an incident role.
	DefaultIncidentRole *string `queryParam:"style=form,explode=true,name=default_incident_role"`
	// Boolean to determine whether to return a slimified version of the teams object
	Lite *bool `queryParam:"style=form,explode=true,name=lite"`
}

func (l *ListTeamsRequest) GetPage() *int {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTeamsRequest) GetPerPage() *int {
	if l == nil {
		return nil
	}
	return l.PerPage
}

func (l *ListTeamsRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListTeamsRequest) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListTeamsRequest) GetServices() *string {
	if l == nil {
		return nil
	}
	return l.Services
}

func (l *ListTeamsRequest) GetDefaultIncidentRole() *string {
	if l == nil {
		return nil
	}
	return l.DefaultIncidentRole
}

func (l *ListTeamsRequest) GetLite() *bool {
	if l == nil {
		return nil
	}
	return l.Lite
}
