// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListCommentReactionsRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversation_id"`
	CommentID      string `pathParam:"style=simple,explode=false,name=comment_id"`
}

func (l *ListCommentReactionsRequest) GetConversationID() string {
	if l == nil {
		return ""
	}
	return l.ConversationID
}

func (l *ListCommentReactionsRequest) GetCommentID() string {
	if l == nil {
		return ""
	}
	return l.CommentID
}
