// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type PublishPostMortemReportRequest struct {
	ReportID                string                             `pathParam:"style=simple,explode=false,name=report_id"`
	PublishPostMortemReport components.PublishPostMortemReport `request:"mediaType=application/json"`
}

func (o *PublishPostMortemReportRequest) GetReportID() string {
	if o == nil {
		return ""
	}
	return o.ReportID
}

func (o *PublishPostMortemReportRequest) GetPublishPostMortemReport() components.PublishPostMortemReport {
	if o == nil {
		return components.PublishPostMortemReport{}
	}
	return o.PublishPostMortemReport
}
