// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RefreshConnectionRequest struct {
	Slug         string `pathParam:"style=simple,explode=false,name=slug"`
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (r *RefreshConnectionRequest) GetSlug() string {
	if r == nil {
		return ""
	}
	return r.Slug
}

func (r *RefreshConnectionRequest) GetConnectionID() string {
	if r == nil {
		return ""
	}
	return r.ConnectionID
}
