// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RefreshCatalogRequest struct {
	CatalogID string `pathParam:"style=simple,explode=false,name=catalog_id"`
}

func (o *RefreshCatalogRequest) GetCatalogID() string {
	if o == nil {
		return ""
	}
	return o.CatalogID
}
