// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RefreshCatalogRequest struct {
	CatalogID string `pathParam:"style=simple,explode=false,name=catalog_id"`
}

func (r *RefreshCatalogRequest) GetCatalogID() string {
	if r == nil {
		return ""
	}
	return r.CatalogID
}
