// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type ReorderPostMortemReasonsRequest struct {
	ReportID                 string                              `pathParam:"style=simple,explode=false,name=report_id"`
	ReorderPostMortemReasons components.ReorderPostMortemReasons `request:"mediaType=application/json"`
}

func (r *ReorderPostMortemReasonsRequest) GetReportID() string {
	if r == nil {
		return ""
	}
	return r.ReportID
}

func (r *ReorderPostMortemReasonsRequest) GetReorderPostMortemReasons() components.ReorderPostMortemReasons {
	if r == nil {
		return components.ReorderPostMortemReasons{}
	}
	return r.ReorderPostMortemReasons
}
