// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentRetrospectiveRequest struct {
	RetrospectiveID             string                                 `pathParam:"style=simple,explode=false,name=retrospective_id"`
	IncidentID                  string                                 `pathParam:"style=simple,explode=false,name=incident_id"`
	UpdateIncidentRetrospective components.UpdateIncidentRetrospective `request:"mediaType=application/json"`
}

func (u *UpdateIncidentRetrospectiveRequest) GetRetrospectiveID() string {
	if u == nil {
		return ""
	}
	return u.RetrospectiveID
}

func (u *UpdateIncidentRetrospectiveRequest) GetIncidentID() string {
	if u == nil {
		return ""
	}
	return u.IncidentID
}

func (u *UpdateIncidentRetrospectiveRequest) GetUpdateIncidentRetrospective() components.UpdateIncidentRetrospective {
	if u == nil {
		return components.UpdateIncidentRetrospective{}
	}
	return u.UpdateIncidentRetrospective
}
