// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentTypeRequest struct {
	ID                 string                        `pathParam:"style=simple,explode=false,name=id"`
	UpdateIncidentType components.UpdateIncidentType `request:"mediaType=application/json"`
}

func (o *UpdateIncidentTypeRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateIncidentTypeRequest) GetUpdateIncidentType() components.UpdateIncidentType {
	if o == nil {
		return components.UpdateIncidentType{}
	}
	return o.UpdateIncidentType
}
