// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentLinkRequest struct {
	LinkID             string                        `pathParam:"style=simple,explode=false,name=link_id"`
	IncidentID         string                        `pathParam:"style=simple,explode=false,name=incident_id"`
	UpdateIncidentLink components.UpdateIncidentLink `request:"mediaType=application/json"`
}

func (u *UpdateIncidentLinkRequest) GetLinkID() string {
	if u == nil {
		return ""
	}
	return u.LinkID
}

func (u *UpdateIncidentLinkRequest) GetIncidentID() string {
	if u == nil {
		return ""
	}
	return u.IncidentID
}

func (u *UpdateIncidentLinkRequest) GetUpdateIncidentLink() components.UpdateIncidentLink {
	if u == nil {
		return components.UpdateIncidentLink{}
	}
	return u.UpdateIncidentLink
}
