// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateEnvironmentRequest struct {
	// Environment UUID
	EnvironmentID     string                       `pathParam:"style=simple,explode=false,name=environment_id"`
	UpdateEnvironment components.UpdateEnvironment `request:"mediaType=application/json"`
}

func (o *UpdateEnvironmentRequest) GetEnvironmentID() string {
	if o == nil {
		return ""
	}
	return o.EnvironmentID
}

func (o *UpdateEnvironmentRequest) GetUpdateEnvironment() components.UpdateEnvironment {
	if o == nil {
		return components.UpdateEnvironment{}
	}
	return o.UpdateEnvironment
}
