// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateCustomFieldDefinitionRequest struct {
	FieldID                     string                                 `pathParam:"style=simple,explode=false,name=field_id"`
	UpdateCustomFieldDefinition components.UpdateCustomFieldDefinition `request:"mediaType=application/json"`
}

func (u *UpdateCustomFieldDefinitionRequest) GetFieldID() string {
	if u == nil {
		return ""
	}
	return u.FieldID
}

func (u *UpdateCustomFieldDefinitionRequest) GetUpdateCustomFieldDefinition() components.UpdateCustomFieldDefinition {
	if u == nil {
		return components.UpdateCustomFieldDefinition{}
	}
	return u.UpdateCustomFieldDefinition
}
