// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateServiceRequest struct {
	ServiceID     string                   `pathParam:"style=simple,explode=false,name=service_id"`
	UpdateService components.UpdateService `request:"mediaType=application/json"`
}

func (o *UpdateServiceRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *UpdateServiceRequest) GetUpdateService() components.UpdateService {
	if o == nil {
		return components.UpdateService{}
	}
	return o.UpdateService
}
