// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateLifecycleMeasurementDefinitionRequestBody struct {
	Name                *string `json:"name,omitempty"`
	Slug                *string `json:"slug,omitempty"`
	Description         *string `json:"description,omitempty"`
	StartsAtMilestoneID *string `json:"starts_at_milestone_id,omitempty"`
	EndsAtMilestoneID   *string `json:"ends_at_milestone_id,omitempty"`
}

func (u *UpdateLifecycleMeasurementDefinitionRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateLifecycleMeasurementDefinitionRequestBody) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UpdateLifecycleMeasurementDefinitionRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateLifecycleMeasurementDefinitionRequestBody) GetStartsAtMilestoneID() *string {
	if u == nil {
		return nil
	}
	return u.StartsAtMilestoneID
}

func (u *UpdateLifecycleMeasurementDefinitionRequestBody) GetEndsAtMilestoneID() *string {
	if u == nil {
		return nil
	}
	return u.EndsAtMilestoneID
}

type UpdateLifecycleMeasurementDefinitionRequest struct {
	MeasurementDefinitionID string                                           `pathParam:"style=simple,explode=false,name=measurement_definition_id"`
	RequestBody             *UpdateLifecycleMeasurementDefinitionRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateLifecycleMeasurementDefinitionRequest) GetMeasurementDefinitionID() string {
	if u == nil {
		return ""
	}
	return u.MeasurementDefinitionID
}

func (u *UpdateLifecycleMeasurementDefinitionRequest) GetRequestBody() *UpdateLifecycleMeasurementDefinitionRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}
