// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentImpactPatchRequest struct {
	IncidentID                string                               `pathParam:"style=simple,explode=false,name=incident_id"`
	UpdateIncidentImpactPatch components.UpdateIncidentImpactPatch `request:"mediaType=application/json"`
}

func (u *UpdateIncidentImpactPatchRequest) GetIncidentID() string {
	if u == nil {
		return ""
	}
	return u.IncidentID
}

func (u *UpdateIncidentImpactPatchRequest) GetUpdateIncidentImpactPatch() components.UpdateIncidentImpactPatch {
	if u == nil {
		return components.UpdateIncidentImpactPatch{}
	}
	return u.UpdateIncidentImpactPatch
}
