// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
)

type UpdateRetrospectiveTemplateFieldsType string

const (
	UpdateRetrospectiveTemplateFieldsTypeText              UpdateRetrospectiveTemplateFieldsType = "text"
	UpdateRetrospectiveTemplateFieldsTypeSingleSelect      UpdateRetrospectiveTemplateFieldsType = "single_select"
	UpdateRetrospectiveTemplateFieldsTypeMultiSelect       UpdateRetrospectiveTemplateFieldsType = "multi_select"
	UpdateRetrospectiveTemplateFieldsTypeNumeric           UpdateRetrospectiveTemplateFieldsType = "numeric"
	UpdateRetrospectiveTemplateFieldsTypeDatetime          UpdateRetrospectiveTemplateFieldsType = "datetime"
	UpdateRetrospectiveTemplateFieldsTypeDynamicInputGroup UpdateRetrospectiveTemplateFieldsType = "dynamic_input_group"
	UpdateRetrospectiveTemplateFieldsTypeMarkdown          UpdateRetrospectiveTemplateFieldsType = "markdown"
	UpdateRetrospectiveTemplateFieldsTypeMarkdownText      UpdateRetrospectiveTemplateFieldsType = "markdown_text"
)

func (e UpdateRetrospectiveTemplateFieldsType) ToPointer() *UpdateRetrospectiveTemplateFieldsType {
	return &e
}
func (e *UpdateRetrospectiveTemplateFieldsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "single_select":
		fallthrough
	case "multi_select":
		fallthrough
	case "numeric":
		fallthrough
	case "datetime":
		fallthrough
	case "dynamic_input_group":
		fallthrough
	case "markdown":
		fallthrough
	case "markdown_text":
		*e = UpdateRetrospectiveTemplateFieldsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateRetrospectiveTemplateFieldsType: %v", v)
	}
}

type UpdateRetrospectiveTemplateRequestBody struct {
	Name                    *string                                 `json:"name,omitempty"`
	Description             *string                                 `json:"description,omitempty"`
	IsDefault               *bool                                   `json:"is_default,omitempty"`
	SectionsSlug            []string                                `json:"sections[slug]"`
	SectionsElements        []string                                `json:"sections[elements]"`
	FieldsID                []string                                `json:"fields[id],omitempty"`
	FieldsLabel             []string                                `json:"fields[label]"`
	FieldsType              []UpdateRetrospectiveTemplateFieldsType `json:"fields[type]"`
	FieldsHelpText          []string                                `json:"fields[help_text],omitempty"`
	FieldsPermissibleValues []string                                `json:"fields[permissible_values],omitempty"`
	FieldsIsRequired        []bool                                  `json:"fields[is_required],omitempty"`
	FieldsSchema            []string                                `json:"fields[schema],omitempty"`
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetSectionsSlug() []string {
	if o == nil {
		return []string{}
	}
	return o.SectionsSlug
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetSectionsElements() []string {
	if o == nil {
		return []string{}
	}
	return o.SectionsElements
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsID() []string {
	if o == nil {
		return nil
	}
	return o.FieldsID
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsLabel() []string {
	if o == nil {
		return []string{}
	}
	return o.FieldsLabel
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsType() []UpdateRetrospectiveTemplateFieldsType {
	if o == nil {
		return []UpdateRetrospectiveTemplateFieldsType{}
	}
	return o.FieldsType
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsHelpText() []string {
	if o == nil {
		return nil
	}
	return o.FieldsHelpText
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsPermissibleValues() []string {
	if o == nil {
		return nil
	}
	return o.FieldsPermissibleValues
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsIsRequired() []bool {
	if o == nil {
		return nil
	}
	return o.FieldsIsRequired
}

func (o *UpdateRetrospectiveTemplateRequestBody) GetFieldsSchema() []string {
	if o == nil {
		return nil
	}
	return o.FieldsSchema
}

type UpdateRetrospectiveTemplateRequest struct {
	RetrospectiveTemplateID string                                 `pathParam:"style=simple,explode=false,name=retrospective_template_id"`
	RequestBody             UpdateRetrospectiveTemplateRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateRetrospectiveTemplateRequest) GetRetrospectiveTemplateID() string {
	if o == nil {
		return ""
	}
	return o.RetrospectiveTemplateID
}

func (o *UpdateRetrospectiveTemplateRequest) GetRequestBody() UpdateRetrospectiveTemplateRequestBody {
	if o == nil {
		return UpdateRetrospectiveTemplateRequestBody{}
	}
	return o.RequestBody
}
