// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateNuncImageFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (u *UpdateNuncImageFile) GetFileName() string {
	if u == nil {
		return ""
	}
	return u.FileName
}

func (u *UpdateNuncImageFile) GetContent() any {
	if u == nil {
		return nil
	}
	return u.Content
}

type UpdateNuncImageRequestBody struct {
	File *UpdateNuncImageFile `multipartForm:"file,name=file"`
}

func (u *UpdateNuncImageRequestBody) GetFile() *UpdateNuncImageFile {
	if u == nil {
		return nil
	}
	return u.File
}

type UpdateNuncImageRequest struct {
	NuncConnectionID string                      `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	Type             string                      `pathParam:"style=simple,explode=false,name=type"`
	RequestBody      *UpdateNuncImageRequestBody `request:"mediaType=multipart/form-data"`
}

func (u *UpdateNuncImageRequest) GetNuncConnectionID() string {
	if u == nil {
		return ""
	}
	return u.NuncConnectionID
}

func (u *UpdateNuncImageRequest) GetType() string {
	if u == nil {
		return ""
	}
	return u.Type
}

func (u *UpdateNuncImageRequest) GetRequestBody() *UpdateNuncImageRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}
