// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateTaskListRequest struct {
	TaskListID     string                    `pathParam:"style=simple,explode=false,name=task_list_id"`
	UpdateTaskList components.UpdateTaskList `request:"mediaType=application/json"`
}

func (u *UpdateTaskListRequest) GetTaskListID() string {
	if u == nil {
		return ""
	}
	return u.TaskListID
}

func (u *UpdateTaskListRequest) GetUpdateTaskList() components.UpdateTaskList {
	if u == nil {
		return components.UpdateTaskList{}
	}
	return u.UpdateTaskList
}
