// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateNuncConnectionRequestBody struct {
	CompanyName        *string `json:"company_name,omitempty"`
	CompanyWebsite     *string `json:"company_website,omitempty"`
	CompanyTosURL      *string `json:"company_tos_url,omitempty"`
	GreetingTitle      *string `json:"greeting_title,omitempty"`
	GreetingBody       *string `json:"greeting_body,omitempty"`
	OperationalMessage *string `json:"operational_message,omitempty"`
	Title              *string `json:"title,omitempty"`
	// Status page condition to map your severity matrix condition to
	ConditionsNuncCondition []string `json:"conditions[nunc_condition]"`
	// Severity matrix condition id
	ConditionsConditionID        []string `json:"conditions[condition_id]"`
	ComponentsInfrastructureType []string `json:"components[infrastructure_type]"`
	ComponentsInfrastructureID   []string `json:"components[infrastructure_id]"`
	PrimaryColor                 *string  `json:"primary_color,omitempty"`
	SecondaryColor               *string  `json:"secondary_color,omitempty"`
	ExposedFields                []string `json:"exposed_fields,omitempty"`
	EnableHistogram              *bool    `json:"enable_histogram,omitempty"`
	UIVersion                    *int     `json:"ui_version,omitempty"`
}

func (u *UpdateNuncConnectionRequestBody) GetCompanyName() *string {
	if u == nil {
		return nil
	}
	return u.CompanyName
}

func (u *UpdateNuncConnectionRequestBody) GetCompanyWebsite() *string {
	if u == nil {
		return nil
	}
	return u.CompanyWebsite
}

func (u *UpdateNuncConnectionRequestBody) GetCompanyTosURL() *string {
	if u == nil {
		return nil
	}
	return u.CompanyTosURL
}

func (u *UpdateNuncConnectionRequestBody) GetGreetingTitle() *string {
	if u == nil {
		return nil
	}
	return u.GreetingTitle
}

func (u *UpdateNuncConnectionRequestBody) GetGreetingBody() *string {
	if u == nil {
		return nil
	}
	return u.GreetingBody
}

func (u *UpdateNuncConnectionRequestBody) GetOperationalMessage() *string {
	if u == nil {
		return nil
	}
	return u.OperationalMessage
}

func (u *UpdateNuncConnectionRequestBody) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateNuncConnectionRequestBody) GetConditionsNuncCondition() []string {
	if u == nil {
		return []string{}
	}
	return u.ConditionsNuncCondition
}

func (u *UpdateNuncConnectionRequestBody) GetConditionsConditionID() []string {
	if u == nil {
		return []string{}
	}
	return u.ConditionsConditionID
}

func (u *UpdateNuncConnectionRequestBody) GetComponentsInfrastructureType() []string {
	if u == nil {
		return []string{}
	}
	return u.ComponentsInfrastructureType
}

func (u *UpdateNuncConnectionRequestBody) GetComponentsInfrastructureID() []string {
	if u == nil {
		return []string{}
	}
	return u.ComponentsInfrastructureID
}

func (u *UpdateNuncConnectionRequestBody) GetPrimaryColor() *string {
	if u == nil {
		return nil
	}
	return u.PrimaryColor
}

func (u *UpdateNuncConnectionRequestBody) GetSecondaryColor() *string {
	if u == nil {
		return nil
	}
	return u.SecondaryColor
}

func (u *UpdateNuncConnectionRequestBody) GetExposedFields() []string {
	if u == nil {
		return nil
	}
	return u.ExposedFields
}

func (u *UpdateNuncConnectionRequestBody) GetEnableHistogram() *bool {
	if u == nil {
		return nil
	}
	return u.EnableHistogram
}

func (u *UpdateNuncConnectionRequestBody) GetUIVersion() *int {
	if u == nil {
		return nil
	}
	return u.UIVersion
}

type UpdateNuncConnectionRequest struct {
	NuncConnectionID string                          `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	RequestBody      UpdateNuncConnectionRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateNuncConnectionRequest) GetNuncConnectionID() string {
	if u == nil {
		return ""
	}
	return u.NuncConnectionID
}

func (u *UpdateNuncConnectionRequest) GetRequestBody() UpdateNuncConnectionRequestBody {
	if u == nil {
		return UpdateNuncConnectionRequestBody{}
	}
	return u.RequestBody
}
