// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateWebhookRequest struct {
	WebhookID     string                   `pathParam:"style=simple,explode=false,name=webhook_id"`
	UpdateWebhook components.UpdateWebhook `request:"mediaType=application/json"`
}

func (u *UpdateWebhookRequest) GetWebhookID() string {
	if u == nil {
		return ""
	}
	return u.WebhookID
}

func (u *UpdateWebhookRequest) GetUpdateWebhook() components.UpdateWebhook {
	if u == nil {
		return components.UpdateWebhook{}
	}
	return u.UpdateWebhook
}
