// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateSignalsHeartbeatEndpointConfigurationRequest struct {
	ID                                          string                                                 `pathParam:"style=simple,explode=false,name=id"`
	UpdateSignalsHeartbeatEndpointConfiguration components.UpdateSignalsHeartbeatEndpointConfiguration `request:"mediaType=application/json"`
}

func (u *UpdateSignalsHeartbeatEndpointConfigurationRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSignalsHeartbeatEndpointConfigurationRequest) GetUpdateSignalsHeartbeatEndpointConfiguration() components.UpdateSignalsHeartbeatEndpointConfiguration {
	if u == nil {
		return components.UpdateSignalsHeartbeatEndpointConfiguration{}
	}
	return u.UpdateSignalsHeartbeatEndpointConfiguration
}
