// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateTeamOnCallScheduleRequest struct {
	TeamID                   string                              `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID               string                              `pathParam:"style=simple,explode=false,name=schedule_id"`
	UpdateTeamOnCallSchedule components.UpdateTeamOnCallSchedule `request:"mediaType=application/json"`
}

func (o *UpdateTeamOnCallScheduleRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *UpdateTeamOnCallScheduleRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *UpdateTeamOnCallScheduleRequest) GetUpdateTeamOnCallSchedule() components.UpdateTeamOnCallSchedule {
	if o == nil {
		return components.UpdateTeamOnCallSchedule{}
	}
	return o.UpdateTeamOnCallSchedule
}
