// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateTicketingPriorityRequest struct {
	ID                      string                             `pathParam:"style=simple,explode=false,name=id"`
	UpdateTicketingPriority components.UpdateTicketingPriority `request:"mediaType=application/json"`
}

func (o *UpdateTicketingPriorityRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateTicketingPriorityRequest) GetUpdateTicketingPriority() components.UpdateTicketingPriority {
	if o == nil {
		return components.UpdateTicketingPriority{}
	}
	return o.UpdateTicketingPriority
}
