// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentChangeEventRequest struct {
	RelatedChangeEventID      string                               `pathParam:"style=simple,explode=false,name=related_change_event_id"`
	IncidentID                string                               `pathParam:"style=simple,explode=false,name=incident_id"`
	UpdateIncidentChangeEvent components.UpdateIncidentChangeEvent `request:"mediaType=application/json"`
}

func (u *UpdateIncidentChangeEventRequest) GetRelatedChangeEventID() string {
	if u == nil {
		return ""
	}
	return u.RelatedChangeEventID
}

func (u *UpdateIncidentChangeEventRequest) GetIncidentID() string {
	if u == nil {
		return ""
	}
	return u.IncidentID
}

func (u *UpdateIncidentChangeEventRequest) GetUpdateIncidentChangeEvent() components.UpdateIncidentChangeEvent {
	if u == nil {
		return components.UpdateIncidentChangeEvent{}
	}
	return u.UpdateIncidentChangeEvent
}
