// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateAudienceRequestBody struct {
	// Name of the audience (max 255 characters)
	Name *string `json:"name,omitempty"`
	// Description of the audience (max 4000 characters)
	Description *string `json:"description,omitempty"`
	// Whether this is the default audience
	Default *bool `json:"default,omitempty"`
	// Whether the audience is active or discarded
	Active *bool `json:"active,omitempty"`
	// The incident detail question (max 255 characters)
	DetailsQuestion []string `json:"details[question],omitempty"`
	// The prompt to display when collecting this detail
	DetailsPrompt []string `json:"details[prompt],omitempty"`
	// Optional unique identifier for this detail
	DetailsSlug []string `json:"details[slug],omitempty"`
	// Position of the question in the list (1-based indexing)
	DetailsPosition []int `json:"details[position],omitempty"`
}

func (o *UpdateAudienceRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateAudienceRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateAudienceRequestBody) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *UpdateAudienceRequestBody) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

func (o *UpdateAudienceRequestBody) GetDetailsQuestion() []string {
	if o == nil {
		return nil
	}
	return o.DetailsQuestion
}

func (o *UpdateAudienceRequestBody) GetDetailsPrompt() []string {
	if o == nil {
		return nil
	}
	return o.DetailsPrompt
}

func (o *UpdateAudienceRequestBody) GetDetailsSlug() []string {
	if o == nil {
		return nil
	}
	return o.DetailsSlug
}

func (o *UpdateAudienceRequestBody) GetDetailsPosition() []int {
	if o == nil {
		return nil
	}
	return o.DetailsPosition
}

type UpdateAudienceRequest struct {
	// Unique identifier of the audience
	AudienceID  string                     `pathParam:"style=simple,explode=false,name=audience_id"`
	RequestBody *UpdateAudienceRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateAudienceRequest) GetAudienceID() string {
	if o == nil {
		return ""
	}
	return o.AudienceID
}

func (o *UpdateAudienceRequest) GetRequestBody() *UpdateAudienceRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}
