// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateCommentRequest struct {
	CommentID      string                   `pathParam:"style=simple,explode=false,name=comment_id"`
	ConversationID string                   `pathParam:"style=simple,explode=false,name=conversation_id"`
	UpdateComment  components.UpdateComment `request:"mediaType=application/json"`
}

func (o *UpdateCommentRequest) GetCommentID() string {
	if o == nil {
		return ""
	}
	return o.CommentID
}

func (o *UpdateCommentRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *UpdateCommentRequest) GetUpdateComment() components.UpdateComment {
	if o == nil {
		return components.UpdateComment{}
	}
	return o.UpdateComment
}
