// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateVoteRequest struct {
	IncidentID string                `pathParam:"style=simple,explode=false,name=incident_id"`
	EventID    string                `pathParam:"style=simple,explode=false,name=event_id"`
	UpdateVote components.UpdateVote `request:"mediaType=application/json"`
}

func (o *UpdateVoteRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *UpdateVoteRequest) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *UpdateVoteRequest) GetUpdateVote() components.UpdateVote {
	if o == nil {
		return components.UpdateVote{}
	}
	return o.UpdateVote
}
