// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateChangeEventRequest struct {
	ChangeEventID     string                       `pathParam:"style=simple,explode=false,name=change_event_id"`
	UpdateChangeEvent components.UpdateChangeEvent `request:"mediaType=application/json"`
}

func (u *UpdateChangeEventRequest) GetChangeEventID() string {
	if u == nil {
		return ""
	}
	return u.ChangeEventID
}

func (u *UpdateChangeEventRequest) GetUpdateChangeEvent() components.UpdateChangeEvent {
	if u == nil {
		return components.UpdateChangeEvent{}
	}
	return u.UpdateChangeEvent
}
