// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateSavedSearchResourceType string

const (
	UpdateSavedSearchResourceTypeChangeEvents          UpdateSavedSearchResourceType = "change_events"
	UpdateSavedSearchResourceTypeIncidents             UpdateSavedSearchResourceType = "incidents"
	UpdateSavedSearchResourceTypeServices              UpdateSavedSearchResourceType = "services"
	UpdateSavedSearchResourceTypeScheduledMaintenances UpdateSavedSearchResourceType = "scheduled_maintenances"
	UpdateSavedSearchResourceTypeTicketTasks           UpdateSavedSearchResourceType = "ticket_tasks"
	UpdateSavedSearchResourceTypeTicketFollowUps       UpdateSavedSearchResourceType = "ticket_follow_ups"
	UpdateSavedSearchResourceTypeAnalytics             UpdateSavedSearchResourceType = "analytics"
	UpdateSavedSearchResourceTypeImpactAnalytics       UpdateSavedSearchResourceType = "impact_analytics"
	UpdateSavedSearchResourceTypeAlerts                UpdateSavedSearchResourceType = "alerts"
	UpdateSavedSearchResourceTypeAlertAnalytics        UpdateSavedSearchResourceType = "alert_analytics"
	UpdateSavedSearchResourceTypeIncidentEvents        UpdateSavedSearchResourceType = "incident_events"
)

func (e UpdateSavedSearchResourceType) ToPointer() *UpdateSavedSearchResourceType {
	return &e
}
func (e *UpdateSavedSearchResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "change_events":
		fallthrough
	case "incidents":
		fallthrough
	case "services":
		fallthrough
	case "scheduled_maintenances":
		fallthrough
	case "ticket_tasks":
		fallthrough
	case "ticket_follow_ups":
		fallthrough
	case "analytics":
		fallthrough
	case "impact_analytics":
		fallthrough
	case "alerts":
		fallthrough
	case "alert_analytics":
		fallthrough
	case "incident_events":
		*e = UpdateSavedSearchResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateSavedSearchResourceType: %v", v)
	}
}

type UpdateSavedSearchRequest struct {
	ResourceType      UpdateSavedSearchResourceType `pathParam:"style=simple,explode=false,name=resource_type"`
	SavedSearchID     string                        `pathParam:"style=simple,explode=false,name=saved_search_id"`
	UpdateSavedSearch components.UpdateSavedSearch  `request:"mediaType=application/json"`
}

func (u *UpdateSavedSearchRequest) GetResourceType() UpdateSavedSearchResourceType {
	if u == nil {
		return UpdateSavedSearchResourceType("")
	}
	return u.ResourceType
}

func (u *UpdateSavedSearchRequest) GetSavedSearchID() string {
	if u == nil {
		return ""
	}
	return u.SavedSearchID
}

func (u *UpdateSavedSearchRequest) GetUpdateSavedSearch() components.UpdateSavedSearch {
	if u == nil {
		return components.UpdateSavedSearch{}
	}
	return u.UpdateSavedSearch
}
