// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateTaskListRequest struct {
	TaskListID     string                    `pathParam:"style=simple,explode=false,name=task_list_id"`
	UpdateTaskList components.UpdateTaskList `request:"mediaType=application/json"`
}

func (o *UpdateTaskListRequest) GetTaskListID() string {
	if o == nil {
		return ""
	}
	return o.TaskListID
}

func (o *UpdateTaskListRequest) GetUpdateTaskList() components.UpdateTaskList {
	if o == nil {
		return components.UpdateTaskList{}
	}
	return o.UpdateTaskList
}
