// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdatePriorityRequest struct {
	PrioritySlug   string                    `pathParam:"style=simple,explode=false,name=priority_slug"`
	UpdatePriority components.UpdatePriority `request:"mediaType=application/json"`
}

func (o *UpdatePriorityRequest) GetPrioritySlug() string {
	if o == nil {
		return ""
	}
	return o.PrioritySlug
}

func (o *UpdatePriorityRequest) GetUpdatePriority() components.UpdatePriority {
	if o == nil {
		return components.UpdatePriority{}
	}
	return o.UpdatePriority
}
