// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"firehydrant/models/components"
)

type UpdateSignalsEmailTargetRequest struct {
	ID                       string                              `pathParam:"style=simple,explode=false,name=id"`
	UpdateSignalsEmailTarget components.UpdateSignalsEmailTarget `request:"mediaType=application/json"`
}

func (o *UpdateSignalsEmailTargetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateSignalsEmailTargetRequest) GetUpdateSignalsEmailTarget() components.UpdateSignalsEmailTarget {
	if o == nil {
		return components.UpdateSignalsEmailTarget{}
	}
	return o.UpdateSignalsEmailTarget
}
