// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateIncidentTaskRequest struct {
	TaskID             string                        `pathParam:"style=simple,explode=false,name=task_id"`
	IncidentID         string                        `pathParam:"style=simple,explode=false,name=incident_id"`
	UpdateIncidentTask components.UpdateIncidentTask `request:"mediaType=application/json"`
}

func (u *UpdateIncidentTaskRequest) GetTaskID() string {
	if u == nil {
		return ""
	}
	return u.TaskID
}

func (u *UpdateIncidentTaskRequest) GetIncidentID() string {
	if u == nil {
		return ""
	}
	return u.IncidentID
}

func (u *UpdateIncidentTaskRequest) GetUpdateIncidentTask() components.UpdateIncidentTask {
	if u == nil {
		return components.UpdateIncidentTask{}
	}
	return u.UpdateIncidentTask
}
