// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdatePostMortemReportRequest struct {
	ReportID               string                            `pathParam:"style=simple,explode=false,name=report_id"`
	UpdatePostMortemReport components.UpdatePostMortemReport `request:"mediaType=application/json"`
}

func (o *UpdatePostMortemReportRequest) GetReportID() string {
	if o == nil {
		return ""
	}
	return o.ReportID
}

func (o *UpdatePostMortemReportRequest) GetUpdatePostMortemReport() components.UpdatePostMortemReport {
	if o == nil {
		return components.UpdatePostMortemReport{}
	}
	return o.UpdatePostMortemReport
}
