// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateTicketingCustomDefinitionRequest struct {
	FieldID                         string                                     `pathParam:"style=simple,explode=false,name=field_id"`
	UpdateTicketingCustomDefinition components.UpdateTicketingCustomDefinition `request:"mediaType=application/json"`
}

func (u *UpdateTicketingCustomDefinitionRequest) GetFieldID() string {
	if u == nil {
		return ""
	}
	return u.FieldID
}

func (u *UpdateTicketingCustomDefinitionRequest) GetUpdateTicketingCustomDefinition() components.UpdateTicketingCustomDefinition {
	if u == nil {
		return components.UpdateTicketingCustomDefinition{}
	}
	return u.UpdateTicketingCustomDefinition
}
