// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateScheduledMaintenanceRequest struct {
	ScheduledMaintenanceID     string                                `pathParam:"style=simple,explode=false,name=scheduled_maintenance_id"`
	UpdateScheduledMaintenance components.UpdateScheduledMaintenance `request:"mediaType=application/json"`
}

func (u *UpdateScheduledMaintenanceRequest) GetScheduledMaintenanceID() string {
	if u == nil {
		return ""
	}
	return u.ScheduledMaintenanceID
}

func (u *UpdateScheduledMaintenanceRequest) GetUpdateScheduledMaintenance() components.UpdateScheduledMaintenance {
	if u == nil {
		return components.UpdateScheduledMaintenance{}
	}
	return u.UpdateScheduledMaintenance
}
