// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateChangeRequest struct {
	ChangeID     string                  `pathParam:"style=simple,explode=false,name=change_id"`
	UpdateChange components.UpdateChange `request:"mediaType=application/json"`
}

func (u *UpdateChangeRequest) GetChangeID() string {
	if u == nil {
		return ""
	}
	return u.ChangeID
}

func (u *UpdateChangeRequest) GetUpdateChange() components.UpdateChange {
	if u == nil {
		return components.UpdateChange{}
	}
	return u.UpdateChange
}
