// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateTeamRequest struct {
	TeamID     string                `pathParam:"style=simple,explode=false,name=team_id"`
	UpdateTeam components.UpdateTeam `request:"mediaType=application/json"`
}

func (o *UpdateTeamRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *UpdateTeamRequest) GetUpdateTeam() components.UpdateTeam {
	if o == nil {
		return components.UpdateTeam{}
	}
	return o.UpdateTeam
}
