// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateAwsConnectionRequest struct {
	ID                  string                         `pathParam:"style=simple,explode=false,name=id"`
	UpdateAwsConnection components.UpdateAwsConnection `request:"mediaType=application/json"`
}

func (o *UpdateAwsConnectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAwsConnectionRequest) GetUpdateAwsConnection() components.UpdateAwsConnection {
	if o == nil {
		return components.UpdateAwsConnection{}
	}
	return o.UpdateAwsConnection
}
