// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateIncidentEventRequest struct {
	IncidentID string `pathParam:"style=simple,explode=false,name=incident_id"`
	EventID    string `pathParam:"style=simple,explode=false,name=event_id"`
}

func (o *UpdateIncidentEventRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *UpdateIncidentEventRequest) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}
