// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/firehydrant-go-sdk/models/components"
)

type UpdateOnCallScheduleRotationRequest struct {
	RotationID                   string                                  `pathParam:"style=simple,explode=false,name=rotation_id"`
	TeamID                       string                                  `pathParam:"style=simple,explode=false,name=team_id"`
	ScheduleID                   string                                  `pathParam:"style=simple,explode=false,name=schedule_id"`
	UpdateOnCallScheduleRotation components.UpdateOnCallScheduleRotation `request:"mediaType=application/json"`
}

func (o *UpdateOnCallScheduleRotationRequest) GetRotationID() string {
	if o == nil {
		return ""
	}
	return o.RotationID
}

func (o *UpdateOnCallScheduleRotationRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *UpdateOnCallScheduleRotationRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

func (o *UpdateOnCallScheduleRotationRequest) GetUpdateOnCallScheduleRotation() components.UpdateOnCallScheduleRotation {
	if o == nil {
		return components.UpdateOnCallScheduleRotation{}
	}
	return o.UpdateOnCallScheduleRotation
}
