// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateRunbookExecutionStepScriptRequest struct {
	ExecutionID string `pathParam:"style=simple,explode=false,name=execution_id"`
	StepID      string `pathParam:"style=simple,explode=false,name=step_id"`
	State       string `pathParam:"style=simple,explode=false,name=state"`
}

func (u *UpdateRunbookExecutionStepScriptRequest) GetExecutionID() string {
	if u == nil {
		return ""
	}
	return u.ExecutionID
}

func (u *UpdateRunbookExecutionStepScriptRequest) GetStepID() string {
	if u == nil {
		return ""
	}
	return u.StepID
}

func (u *UpdateRunbookExecutionStepScriptRequest) GetState() string {
	if u == nil {
		return ""
	}
	return u.State
}
