// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AlertsProcessingLogEntryEntityPaginated - Alerts_ProcessingLogEntryEntityPaginated model
type AlertsProcessingLogEntryEntityPaginated struct {
	Data       []AlertsProcessingLogEntryEntity `json:"data,omitempty"`
	Pagination *NullablePaginationEntity        `json:"pagination,omitempty"`
}

func (a *AlertsProcessingLogEntryEntityPaginated) GetData() []AlertsProcessingLogEntryEntity {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AlertsProcessingLogEntryEntityPaginated) GetPagination() *NullablePaginationEntity {
	if a == nil {
		return nil
	}
	return a.Pagination
}
