// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// AlertsSirenAlertEntityLabels - Arbitrary key:value pairs of labels.
type AlertsSirenAlertEntityLabels struct {
}

type AlertsSirenAlertEntity struct {
	ID          *string    `json:"id,omitempty"`
	Summary     *string    `json:"summary,omitempty"`
	Description *string    `json:"description,omitempty"`
	StartsAt    *time.Time `json:"starts_at,omitempty"`
	EndsAt      *time.Time `json:"ends_at,omitempty"`
	Status      *string    `json:"status,omitempty"`
	RemoteID    *string    `json:"remote_id,omitempty"`
	RemoteURL   *string    `json:"remote_url,omitempty"`
	// Arbitrary key:value pairs of labels.
	Labels     *AlertsSirenAlertEntityLabels `json:"labels,omitempty"`
	Tags       []string                      `json:"tags,omitempty"`
	SignalID   *string                       `json:"signal_id,omitempty"`
	SignalRule *NullableSignalsAPIRuleEntity `json:"signal_rule,omitempty"`
}

func (a AlertsSirenAlertEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlertsSirenAlertEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlertsSirenAlertEntity) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AlertsSirenAlertEntity) GetSummary() *string {
	if a == nil {
		return nil
	}
	return a.Summary
}

func (a *AlertsSirenAlertEntity) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AlertsSirenAlertEntity) GetStartsAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.StartsAt
}

func (a *AlertsSirenAlertEntity) GetEndsAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.EndsAt
}

func (a *AlertsSirenAlertEntity) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AlertsSirenAlertEntity) GetRemoteID() *string {
	if a == nil {
		return nil
	}
	return a.RemoteID
}

func (a *AlertsSirenAlertEntity) GetRemoteURL() *string {
	if a == nil {
		return nil
	}
	return a.RemoteURL
}

func (a *AlertsSirenAlertEntity) GetLabels() *AlertsSirenAlertEntityLabels {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AlertsSirenAlertEntity) GetTags() []string {
	if a == nil {
		return nil
	}
	return a.Tags
}

func (a *AlertsSirenAlertEntity) GetSignalID() *string {
	if a == nil {
		return nil
	}
	return a.SignalID
}

func (a *AlertsSirenAlertEntity) GetSignalRule() *NullableSignalsAPIRuleEntity {
	if a == nil {
		return nil
	}
	return a.SignalRule
}
