// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// Attributes - Can be one of: Attachments::LinkEntity, Integrations::CustomerSupportIssueEntity, Attachments::GenericAttachmentEntity
type Attributes struct {
}

type AttachmentsTypedAttachmentEntity struct {
	ID                      *string    `json:"id,omitempty"`
	Type                    *string    `json:"type,omitempty"`
	AttachedToID            *string    `json:"attached_to_id,omitempty"`
	AttachedToType          *string    `json:"attached_to_type,omitempty"`
	SecondaryAttachedToID   *string    `json:"secondary_attached_to_id,omitempty"`
	SecondaryAttachedToType *string    `json:"secondary_attached_to_type,omitempty"`
	CreatedAt               *time.Time `json:"created_at,omitempty"`
	// Can be one of: Attachments::LinkEntity, Integrations::CustomerSupportIssueEntity, Attachments::GenericAttachmentEntity
	Attributes *Attributes `json:"attributes,omitempty"`
}

func (a AttachmentsTypedAttachmentEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AttachmentsTypedAttachmentEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AttachmentsTypedAttachmentEntity) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AttachmentsTypedAttachmentEntity) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AttachmentsTypedAttachmentEntity) GetAttachedToID() *string {
	if a == nil {
		return nil
	}
	return a.AttachedToID
}

func (a *AttachmentsTypedAttachmentEntity) GetAttachedToType() *string {
	if a == nil {
		return nil
	}
	return a.AttachedToType
}

func (a *AttachmentsTypedAttachmentEntity) GetSecondaryAttachedToID() *string {
	if a == nil {
		return nil
	}
	return a.SecondaryAttachedToID
}

func (a *AttachmentsTypedAttachmentEntity) GetSecondaryAttachedToType() *string {
	if a == nil {
		return nil
	}
	return a.SecondaryAttachedToType
}

func (a *AttachmentsTypedAttachmentEntity) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AttachmentsTypedAttachmentEntity) GetAttributes() *Attributes {
	if a == nil {
		return nil
	}
	return a.Attributes
}
