// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AudiencesEntitiesAudienceSummariesEntity - Audiences_Entities_AudienceSummariesEntity model
type AudiencesEntitiesAudienceSummariesEntity struct {
	IncidentID *string `json:"incident_id,omitempty"`
	// JSON-encoded map of audience summaries
	Audiences *string `json:"audiences,omitempty"`
}

func (a *AudiencesEntitiesAudienceSummariesEntity) GetIncidentID() *string {
	if a == nil {
		return nil
	}
	return a.IncidentID
}

func (a *AudiencesEntitiesAudienceSummariesEntity) GetAudiences() *string {
	if a == nil {
		return nil
	}
	return a.Audiences
}
