// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AudiencesEntitiesDetailEntity struct {
	// Unique identifier for the detail item
	ID *string `json:"id,omitzero"`
	// The need-to-know question (maximum 255 characters)
	Question *string `json:"question,omitzero"`
	// AI prompt used to gather this information
	Prompt *string `json:"prompt,omitzero"`
	// Order position of this item in the list
	Position *int `json:"position,omitzero"`
	// Slug of the detail, unique and autogenerated
	Slug *string `json:"slug,omitzero"`
}

func (a *AudiencesEntitiesDetailEntity) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AudiencesEntitiesDetailEntity) GetQuestion() *string {
	if a == nil {
		return nil
	}
	return a.Question
}

func (a *AudiencesEntitiesDetailEntity) GetPrompt() *string {
	if a == nil {
		return nil
	}
	return a.Prompt
}

func (a *AudiencesEntitiesDetailEntity) GetPosition() *int {
	if a == nil {
		return nil
	}
	return a.Position
}

func (a *AudiencesEntitiesDetailEntity) GetSlug() *string {
	if a == nil {
		return nil
	}
	return a.Slug
}
