// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// ChangeEventSlimEntityPaginated model
type ChangeEventSlimEntityPaginated struct {
	Data       []ChangeEventSlimEntity   `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (c ChangeEventSlimEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChangeEventSlimEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChangeEventSlimEntityPaginated) GetData() []ChangeEventSlimEntity {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChangeEventSlimEntityPaginated) GetPagination() *NullablePaginationEntity {
	if c == nil {
		return nil
	}
	return c.Pagination
}
