// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChangeTypeEntity struct {
	ID   *string `json:"id,omitzero"`
	Name *string `json:"name,omitzero"`
}

func (c *ChangeTypeEntity) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChangeTypeEntity) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}
