// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChecklistTemplateEntityPaginated model
type ChecklistTemplateEntityPaginated struct {
	Data       []ChecklistTemplateEntity `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (c *ChecklistTemplateEntityPaginated) GetData() []ChecklistTemplateEntity {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ChecklistTemplateEntityPaginated) GetPagination() *NullablePaginationEntity {
	if c == nil {
		return nil
	}
	return c.Pagination
}
