// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// ChecklistTemplateEntity model
type ChecklistTemplateEntity struct {
	ID          *string                 `json:"id,omitzero"`
	Name        *string                 `json:"name,omitzero"`
	Description *string                 `json:"description,omitzero"`
	CreatedAt   *string                 `json:"created_at,omitzero"`
	UpdatedAt   *time.Time              `json:"updated_at,omitzero"`
	Checks      []ChecklistCheckEntity  `json:"checks,omitzero"`
	Owner       *NullableTeamEntityLite `json:"owner,omitzero"`
	// List of services that use this checklist
	ConnectedServices []ServiceEntityChecklist `json:"connected_services,omitzero"`
}

func (c ChecklistTemplateEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChecklistTemplateEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChecklistTemplateEntity) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ChecklistTemplateEntity) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ChecklistTemplateEntity) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ChecklistTemplateEntity) GetCreatedAt() *string {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *ChecklistTemplateEntity) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *ChecklistTemplateEntity) GetChecks() []ChecklistCheckEntity {
	if c == nil {
		return nil
	}
	return c.Checks
}

func (c *ChecklistTemplateEntity) GetOwner() *NullableTeamEntityLite {
	if c == nil {
		return nil
	}
	return c.Owner
}

func (c *ChecklistTemplateEntity) GetConnectedServices() []ServiceEntityChecklist {
	if c == nil {
		return nil
	}
	return c.ConnectedServices
}
