// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type ConversationsAPIEntitiesReference struct {
	ID            *string                                  `json:"id,omitzero"`
	ResourceClass *string                                  `json:"resource_class,omitzero"`
	ResourceID    *string                                  `json:"resource_id,omitzero"`
	Field         *string                                  `json:"field,omitzero"`
	CommentsURL   *string                                  `json:"comments_url,omitzero"`
	Channel       *NullableConversationsAPIEntitiesChannel `json:"channel,omitzero"`
}

func (c ConversationsAPIEntitiesReference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationsAPIEntitiesReference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationsAPIEntitiesReference) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ConversationsAPIEntitiesReference) GetResourceClass() *string {
	if c == nil {
		return nil
	}
	return c.ResourceClass
}

func (c *ConversationsAPIEntitiesReference) GetResourceID() *string {
	if c == nil {
		return nil
	}
	return c.ResourceID
}

func (c *ConversationsAPIEntitiesReference) GetField() *string {
	if c == nil {
		return nil
	}
	return c.Field
}

func (c *ConversationsAPIEntitiesReference) GetCommentsURL() *string {
	if c == nil {
		return nil
	}
	return c.CommentsURL
}

func (c *ConversationsAPIEntitiesReference) GetChannel() *NullableConversationsAPIEntitiesChannel {
	if c == nil {
		return nil
	}
	return c.Channel
}
