// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CopyOnCallScheduleRotation - Copy an on-call rotation into a different schedule, allowing you to merge them together safely.
type CopyOnCallScheduleRotation struct {
	// The ID of the schedule to clone the rotation into
	TargetScheduleID string `json:"target_schedule_id"`
	// The name of the on-call rotation
	Name *string `json:"name,omitempty"`
}

func (o *CopyOnCallScheduleRotation) GetTargetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.TargetScheduleID
}

func (o *CopyOnCallScheduleRotation) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
