// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreatePostMortemReason - Add a new contributing factor to an incident
type CreatePostMortemReason struct {
	Summary string `json:"summary"`
}

func (o *CreatePostMortemReason) GetSummary() string {
	if o == nil {
		return ""
	}
	return o.Summary
}
