// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type CreateChecklistTemplateCheck struct {
	// The name of the check
	Name string `json:"name"`
	// The description of the check
	Description *string `json:"description,omitzero"`
}

func (c *CreateChecklistTemplateCheck) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateChecklistTemplateCheck) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

type CreateChecklistTemplateConnectedService struct {
	ID string `json:"id"`
}

func (c *CreateChecklistTemplateConnectedService) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// CreateChecklistTemplate - Creates a checklist template for the organization
type CreateChecklistTemplate struct {
	Name string `json:"name"`
	// An array of checks for the checklist template
	Checks      []CreateChecklistTemplateCheck `json:"checks"`
	Description *string                        `json:"description,omitzero"`
	// The ID of the Team that owns the checklist template
	TeamID *string `json:"team_id,omitzero"`
	// Array of service IDs to attach checklist template to
	ConnectedServices []CreateChecklistTemplateConnectedService `json:"connected_services,omitzero"`
}

func (c CreateChecklistTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateChecklistTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateChecklistTemplate) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateChecklistTemplate) GetChecks() []CreateChecklistTemplateCheck {
	if c == nil {
		return []CreateChecklistTemplateCheck{}
	}
	return c.Checks
}

func (c *CreateChecklistTemplate) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateChecklistTemplate) GetTeamID() *string {
	if c == nil {
		return nil
	}
	return c.TeamID
}

func (c *CreateChecklistTemplate) GetConnectedServices() []CreateChecklistTemplateConnectedService {
	if c == nil {
		return nil
	}
	return c.ConnectedServices
}
