// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateSavedSearch - Create a new saved search for a particular resource type
type CreateSavedSearch struct {
	Name         string         `json:"name"`
	IsPrivate    *bool          `json:"is_private,omitzero"`
	FilterValues map[string]any `json:"filter_values"`
}

func (c *CreateSavedSearch) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSavedSearch) GetIsPrivate() *bool {
	if c == nil {
		return nil
	}
	return c.IsPrivate
}

func (c *CreateSavedSearch) GetFilterValues() map[string]any {
	if c == nil {
		return map[string]any{}
	}
	return c.FilterValues
}
