// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CreateServiceServiceTier - Integer representing service tier. Lower values represent higher criticality. If not specified the default value will be 5.
type CreateServiceServiceTier int

const (
	CreateServiceServiceTierZero  CreateServiceServiceTier = 0
	CreateServiceServiceTierOne   CreateServiceServiceTier = 1
	CreateServiceServiceTierTwo   CreateServiceServiceTier = 2
	CreateServiceServiceTierThree CreateServiceServiceTier = 3
	CreateServiceServiceTierFour  CreateServiceServiceTier = 4
	CreateServiceServiceTierFive  CreateServiceServiceTier = 5
)

func (e CreateServiceServiceTier) ToPointer() *CreateServiceServiceTier {
	return &e
}
func (e *CreateServiceServiceTier) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		*e = CreateServiceServiceTier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateServiceServiceTier: %v", v)
	}
}

type CreateServiceFunctionality struct {
	// If you are trying to create a new functionality and attach it to this service, set the summary key
	Summary *string `json:"summary,omitempty"`
	// If you are trying to reuse a functionality, you may set the ID to attach it to the service
	ID *string `json:"id,omitempty"`
}

func (c *CreateServiceFunctionality) GetSummary() *string {
	if c == nil {
		return nil
	}
	return c.Summary
}

func (c *CreateServiceFunctionality) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

type CreateServiceLink struct {
	// Short name used to display and identify this link
	Name string `json:"name"`
	// URL
	HrefURL string `json:"href_url"`
	// An optional URL to an icon representing this link
	IconURL *string `json:"icon_url,omitempty"`
}

func (c *CreateServiceLink) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateServiceLink) GetHrefURL() string {
	if c == nil {
		return ""
	}
	return c.HrefURL
}

func (c *CreateServiceLink) GetIconURL() *string {
	if c == nil {
		return nil
	}
	return c.IconURL
}

// CreateServiceOwner - An object representing a Team that owns the service
type CreateServiceOwner struct {
	ID string `json:"id"`
}

func (c *CreateServiceOwner) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateServiceTeam struct {
	ID string `json:"id"`
}

func (c *CreateServiceTeam) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateServiceExternalResource struct {
	RemoteID string `json:"remote_id"`
	// The integration slug for the external resource. Can be one of: github, opsgenie, pager_duty, victorops. Not required if the resource has already been imported.
	ConnectionType *string `json:"connection_type,omitempty"`
}

func (c *CreateServiceExternalResource) GetRemoteID() string {
	if c == nil {
		return ""
	}
	return c.RemoteID
}

func (c *CreateServiceExternalResource) GetConnectionType() *string {
	if c == nil {
		return nil
	}
	return c.ConnectionType
}

// CreateService - Creates a service for the organization, you may also create or attach functionalities to the service on create.
type CreateService struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// A hash of label keys and values
	Labels map[string]string `json:"labels,omitempty"`
	// Integer representing service tier. Lower values represent higher criticality. If not specified the default value will be 5.
	ServiceTier *CreateServiceServiceTier `json:"service_tier,omitempty"`
	// An array of functionalities
	Functionalities []CreateServiceFunctionality `json:"functionalities,omitempty"`
	// An array of links to associate with this service
	Links []CreateServiceLink `json:"links,omitempty"`
	// An object representing a Team that owns the service
	Owner *CreateServiceOwner `json:"owner,omitempty"`
	// An array of teams to attach to this service.
	Teams                 []CreateServiceTeam `json:"teams,omitempty"`
	AlertOnAdd            *bool               `json:"alert_on_add,omitempty"`
	AutoAddRespondingTeam *bool               `json:"auto_add_responding_team,omitempty"`
	// An array of external resources to attach to this service.
	ExternalResources []CreateServiceExternalResource `json:"external_resources,omitempty"`
}

func (c *CreateService) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateService) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateService) GetLabels() map[string]string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CreateService) GetServiceTier() *CreateServiceServiceTier {
	if c == nil {
		return nil
	}
	return c.ServiceTier
}

func (c *CreateService) GetFunctionalities() []CreateServiceFunctionality {
	if c == nil {
		return nil
	}
	return c.Functionalities
}

func (c *CreateService) GetLinks() []CreateServiceLink {
	if c == nil {
		return nil
	}
	return c.Links
}

func (c *CreateService) GetOwner() *CreateServiceOwner {
	if c == nil {
		return nil
	}
	return c.Owner
}

func (c *CreateService) GetTeams() []CreateServiceTeam {
	if c == nil {
		return nil
	}
	return c.Teams
}

func (c *CreateService) GetAlertOnAdd() *bool {
	if c == nil {
		return nil
	}
	return c.AlertOnAdd
}

func (c *CreateService) GetAutoAddRespondingTeam() *bool {
	if c == nil {
		return nil
	}
	return c.AutoAddRespondingTeam
}

func (c *CreateService) GetExternalResources() []CreateServiceExternalResource {
	if c == nil {
		return nil
	}
	return c.ExternalResources
}
