// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type CreateFunctionalityService struct {
	// ID of a service
	ID string `json:"id"`
}

func (c *CreateFunctionalityService) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateFunctionalityEnvironment struct {
	// ID of an environment
	ID string `json:"id"`
}

func (c *CreateFunctionalityEnvironment) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// CreateFunctionalityServiceTier - Integer representing functionality tier. Lower values represent higher criticality. Default is 5.
type CreateFunctionalityServiceTier int

const (
	CreateFunctionalityServiceTierZero  CreateFunctionalityServiceTier = 0
	CreateFunctionalityServiceTierOne   CreateFunctionalityServiceTier = 1
	CreateFunctionalityServiceTierTwo   CreateFunctionalityServiceTier = 2
	CreateFunctionalityServiceTierThree CreateFunctionalityServiceTier = 3
	CreateFunctionalityServiceTierFour  CreateFunctionalityServiceTier = 4
	CreateFunctionalityServiceTierFive  CreateFunctionalityServiceTier = 5
)

func (e CreateFunctionalityServiceTier) ToPointer() *CreateFunctionalityServiceTier {
	return &e
}
func (e *CreateFunctionalityServiceTier) UnmarshalJSON(data []byte) error {
	var v int
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		*e = CreateFunctionalityServiceTier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFunctionalityServiceTier: %v", v)
	}
}

type CreateFunctionalityExternalResource struct {
	RemoteID string `json:"remote_id"`
	// The integration slug for the external resource. Can be one of: github, opsgenie, pager_duty, statuspage, victorops. Not required if the resource has already been imported.
	ConnectionType *string `json:"connection_type,omitzero"`
}

func (c *CreateFunctionalityExternalResource) GetRemoteID() string {
	if c == nil {
		return ""
	}
	return c.RemoteID
}

func (c *CreateFunctionalityExternalResource) GetConnectionType() *string {
	if c == nil {
		return nil
	}
	return c.ConnectionType
}

type CreateFunctionalityLink struct {
	// Short name used to display and identify this link
	Name string `json:"name"`
	// URL
	HrefURL string `json:"href_url"`
	// An optional URL to an icon representing this link
	IconURL *string `json:"icon_url,omitzero"`
}

func (c *CreateFunctionalityLink) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateFunctionalityLink) GetHrefURL() string {
	if c == nil {
		return ""
	}
	return c.HrefURL
}

func (c *CreateFunctionalityLink) GetIconURL() *string {
	if c == nil {
		return nil
	}
	return c.IconURL
}

// CreateFunctionalityOwner - An object representing a Team that owns the service
type CreateFunctionalityOwner struct {
	ID string `json:"id"`
}

func (c *CreateFunctionalityOwner) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreateFunctionalityTeam struct {
	ID string `json:"id"`
}

func (c *CreateFunctionalityTeam) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// CreateFunctionality - Creates a functionality for the organization
type CreateFunctionality struct {
	Name         string                           `json:"name"`
	Description  *string                          `json:"description,omitzero"`
	Services     []CreateFunctionalityService     `json:"services,omitzero"`
	Environments []CreateFunctionalityEnvironment `json:"environments,omitzero"`
	// A hash of label keys and values
	Labels map[string]string `json:"labels,omitzero"`
	// Integer representing functionality tier. Lower values represent higher criticality. Default is 5.
	ServiceTier           *CreateFunctionalityServiceTier `json:"service_tier,omitzero"`
	AlertOnAdd            *bool                           `json:"alert_on_add,omitzero"`
	AutoAddRespondingTeam *bool                           `json:"auto_add_responding_team,omitzero"`
	// An array of external resources to attach to this service.
	ExternalResources []CreateFunctionalityExternalResource `json:"external_resources,omitzero"`
	// An array of links to associate with this service
	Links []CreateFunctionalityLink `json:"links,omitzero"`
	// An object representing a Team that owns the service
	Owner *CreateFunctionalityOwner `json:"owner,omitzero"`
	// An array of teams to attach to this service.
	Teams []CreateFunctionalityTeam `json:"teams,omitzero"`
}

func (c CreateFunctionality) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFunctionality) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateFunctionality) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateFunctionality) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateFunctionality) GetServices() []CreateFunctionalityService {
	if c == nil {
		return nil
	}
	return c.Services
}

func (c *CreateFunctionality) GetEnvironments() []CreateFunctionalityEnvironment {
	if c == nil {
		return nil
	}
	return c.Environments
}

func (c *CreateFunctionality) GetLabels() map[string]string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CreateFunctionality) GetServiceTier() *CreateFunctionalityServiceTier {
	if c == nil {
		return nil
	}
	return c.ServiceTier
}

func (c *CreateFunctionality) GetAlertOnAdd() *bool {
	if c == nil {
		return nil
	}
	return c.AlertOnAdd
}

func (c *CreateFunctionality) GetAutoAddRespondingTeam() *bool {
	if c == nil {
		return nil
	}
	return c.AutoAddRespondingTeam
}

func (c *CreateFunctionality) GetExternalResources() []CreateFunctionalityExternalResource {
	if c == nil {
		return nil
	}
	return c.ExternalResources
}

func (c *CreateFunctionality) GetLinks() []CreateFunctionalityLink {
	if c == nil {
		return nil
	}
	return c.Links
}

func (c *CreateFunctionality) GetOwner() *CreateFunctionalityOwner {
	if c == nil {
		return nil
	}
	return c.Owner
}

func (c *CreateFunctionality) GetTeams() []CreateFunctionalityTeam {
	if c == nil {
		return nil
	}
	return c.Teams
}
