// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateTaskListTaskListItem struct {
	// A summary of the task
	Summary string `json:"summary"`
	// A long-form description for the task if additional context is helpful
	Description *string `json:"description,omitempty"`
}

func (c *CreateTaskListTaskListItem) GetSummary() string {
	if c == nil {
		return ""
	}
	return c.Summary
}

func (c *CreateTaskListTaskListItem) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

// CreateTaskList - Creates a new task list
type CreateTaskList struct {
	Name          string                       `json:"name"`
	Description   *string                      `json:"description,omitempty"`
	TaskListItems []CreateTaskListTaskListItem `json:"task_list_items"`
}

func (c *CreateTaskList) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateTaskList) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateTaskList) GetTaskListItems() []CreateTaskListTaskListItem {
	if c == nil {
		return []CreateTaskListTaskListItem{}
	}
	return c.TaskListItems
}
