// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateIncidentTypeImpact struct {
	// The id of impact
	ID string `json:"id"`
	// The id of the condition
	ConditionID string `json:"condition_id"`
}

func (c *CreateIncidentTypeImpact) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateIncidentTypeImpact) GetConditionID() string {
	if c == nil {
		return ""
	}
	return c.ConditionID
}

type CreateIncidentTypeTemplate struct {
	Description           *string `json:"description,omitempty"`
	CustomerImpactSummary *string `json:"customer_impact_summary,omitempty"`
	// A labels hash of keys and values
	Labels   map[string]string `json:"labels,omitempty"`
	Severity *string           `json:"severity,omitempty"`
	Priority *string           `json:"priority,omitempty"`
	// List of tags for the incident
	TagList []string `json:"tag_list,omitempty"`
	// List of ids of Runbooks to attach to incidents created from this type
	RunbookIds      []string `json:"runbook_ids,omitempty"`
	PrivateIncident *bool    `json:"private_incident,omitempty"`
	// List of ids of teams to be assigned to incidents
	TeamIds []string `json:"team_ids,omitempty"`
	// An array of impact/condition combinations
	Impacts []CreateIncidentTypeImpact `json:"impacts,omitempty"`
}

func (c *CreateIncidentTypeTemplate) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateIncidentTypeTemplate) GetCustomerImpactSummary() *string {
	if c == nil {
		return nil
	}
	return c.CustomerImpactSummary
}

func (c *CreateIncidentTypeTemplate) GetLabels() map[string]string {
	if c == nil {
		return nil
	}
	return c.Labels
}

func (c *CreateIncidentTypeTemplate) GetSeverity() *string {
	if c == nil {
		return nil
	}
	return c.Severity
}

func (c *CreateIncidentTypeTemplate) GetPriority() *string {
	if c == nil {
		return nil
	}
	return c.Priority
}

func (c *CreateIncidentTypeTemplate) GetTagList() []string {
	if c == nil {
		return nil
	}
	return c.TagList
}

func (c *CreateIncidentTypeTemplate) GetRunbookIds() []string {
	if c == nil {
		return nil
	}
	return c.RunbookIds
}

func (c *CreateIncidentTypeTemplate) GetPrivateIncident() *bool {
	if c == nil {
		return nil
	}
	return c.PrivateIncident
}

func (c *CreateIncidentTypeTemplate) GetTeamIds() []string {
	if c == nil {
		return nil
	}
	return c.TeamIds
}

func (c *CreateIncidentTypeTemplate) GetImpacts() []CreateIncidentTypeImpact {
	if c == nil {
		return nil
	}
	return c.Impacts
}

// CreateIncidentType - Create a new incident type
type CreateIncidentType struct {
	Name string `json:"name"`
	// A description of the incident type
	Description *string                    `json:"description,omitempty"`
	Template    CreateIncidentTypeTemplate `json:"template"`
}

func (c *CreateIncidentType) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateIncidentType) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateIncidentType) GetTemplate() CreateIncidentTypeTemplate {
	if c == nil {
		return CreateIncidentTypeTemplate{}
	}
	return c.Template
}
