// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreatePostMortemReport - Create a report
type CreatePostMortemReport struct {
	IncidentID string `json:"incident_id"`
}

func (o *CreatePostMortemReport) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}
