// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateIncidentTeamAssignment - Assign a team for this incident
type CreateIncidentTeamAssignment struct {
	// The team ID to associate to the incident
	TeamID string `json:"team_id"`
}

func (c *CreateIncidentTeamAssignment) GetTeamID() string {
	if c == nil {
		return ""
	}
	return c.TeamID
}
