// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type DebugSignalsExpressionAnnotations struct {
}

type Image struct {
	Src *string `json:"src,omitzero"`
	Alt *string `json:"alt,omitzero"`
}

func (i *Image) GetSrc() *string {
	if i == nil {
		return nil
	}
	return i.Src
}

func (i *Image) GetAlt() *string {
	if i == nil {
		return nil
	}
	return i.Alt
}

type DebugSignalsExpressionLink struct {
	Href *string `json:"href,omitzero"`
	Text *string `json:"text,omitzero"`
}

func (d *DebugSignalsExpressionLink) GetHref() *string {
	if d == nil {
		return nil
	}
	return d.Href
}

func (d *DebugSignalsExpressionLink) GetText() *string {
	if d == nil {
		return nil
	}
	return d.Text
}

type Signal struct {
	ID             *string                            `json:"id,omitzero"`
	OrganizationID *string                            `json:"organization_id,omitzero"`
	Summary        *string                            `json:"summary,omitzero"`
	Body           *string                            `json:"body,omitzero"`
	Level          *string                            `json:"level,omitzero"`
	Annotations    *DebugSignalsExpressionAnnotations `json:"annotations,omitzero"`
	Tags           []string                           `json:"tags,omitzero"`
	Images         []Image                            `json:"images,omitzero"`
	Links          []DebugSignalsExpressionLink       `json:"links,omitzero"`
}

func (s Signal) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Signal) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Signal) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Signal) GetOrganizationID() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationID
}

func (s *Signal) GetSummary() *string {
	if s == nil {
		return nil
	}
	return s.Summary
}

func (s *Signal) GetBody() *string {
	if s == nil {
		return nil
	}
	return s.Body
}

func (s *Signal) GetLevel() *string {
	if s == nil {
		return nil
	}
	return s.Level
}

func (s *Signal) GetAnnotations() *DebugSignalsExpressionAnnotations {
	if s == nil {
		return nil
	}
	return s.Annotations
}

func (s *Signal) GetTags() []string {
	if s == nil {
		return nil
	}
	return s.Tags
}

func (s *Signal) GetImages() []Image {
	if s == nil {
		return nil
	}
	return s.Images
}

func (s *Signal) GetLinks() []DebugSignalsExpressionLink {
	if s == nil {
		return nil
	}
	return s.Links
}

// DebugSignalsExpression - Debug Signals expressions
type DebugSignalsExpression struct {
	// CEL expression
	Expression string `json:"expression"`
	// List of signals to evaluate rule expression against
	Signals []Signal `json:"signals"`
}

func (d *DebugSignalsExpression) GetExpression() string {
	if d == nil {
		return ""
	}
	return d.Expression
}

func (d *DebugSignalsExpression) GetSignals() []Signal {
	if d == nil {
		return []Signal{}
	}
	return d.Signals
}
