// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Tier string

const (
	TierFree        Tier = "free"
	TierEssentials  Tier = "essentials"
	TierEnterprise  Tier = "enterprise"
	TierSignalsOnly Tier = "signals_only"
)

func (e Tier) ToPointer() *Tier {
	return &e
}
func (e *Tier) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "free":
		fallthrough
	case "essentials":
		fallthrough
	case "enterprise":
		fallthrough
	case "signals_only":
		*e = Tier(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Tier: %v", v)
	}
}

type EntitlementEntity struct {
	CurrentCount *int     `json:"current_count,omitempty"`
	Errors       []string `json:"errors,omitempty"`
	Exists       *bool    `json:"exists,omitempty"`
	Available    *bool    `json:"available,omitempty"`
	Maximum      *int     `json:"maximum,omitempty"`
	Name         *string  `json:"name,omitempty"`
	Slug         *string  `json:"slug,omitempty"`
	Tier         *Tier    `json:"tier,omitempty"`
}

func (e *EntitlementEntity) GetCurrentCount() *int {
	if e == nil {
		return nil
	}
	return e.CurrentCount
}

func (e *EntitlementEntity) GetErrors() []string {
	if e == nil {
		return nil
	}
	return e.Errors
}

func (e *EntitlementEntity) GetExists() *bool {
	if e == nil {
		return nil
	}
	return e.Exists
}

func (e *EntitlementEntity) GetAvailable() *bool {
	if e == nil {
		return nil
	}
	return e.Available
}

func (e *EntitlementEntity) GetMaximum() *int {
	if e == nil {
		return nil
	}
	return e.Maximum
}

func (e *EntitlementEntity) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EntitlementEntity) GetSlug() *string {
	if e == nil {
		return nil
	}
	return e.Slug
}

func (e *EntitlementEntity) GetTier() *Tier {
	if e == nil {
		return nil
	}
	return e.Tier
}
