// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EnvironmentEntryEntityPaginated model
type EnvironmentEntryEntityPaginated struct {
	Data       []EnvironmentEntryEntity  `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (e *EnvironmentEntryEntityPaginated) GetData() []EnvironmentEntryEntity {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EnvironmentEntryEntityPaginated) GetPagination() *NullablePaginationEntity {
	if e == nil {
		return nil
	}
	return e.Pagination
}
