// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// EventGenericChatMessageEntity - Event_GenericChatMessageEntity model
type EventGenericChatMessageEntity struct {
	ID        *string    `json:"id,omitzero"`
	Body      *string    `json:"body,omitzero"`
	CreatedAt *time.Time `json:"created_at,omitzero"`
}

func (e EventGenericChatMessageEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGenericChatMessageEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EventGenericChatMessageEntity) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EventGenericChatMessageEntity) GetBody() *string {
	if e == nil {
		return nil
	}
	return e.Body
}

func (e *EventGenericChatMessageEntity) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}
