// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FormConfigurationEntity model
type FormConfigurationEntity struct {
	Fields            *string `json:"fields,omitzero"`
	ShowIncidentTypes *string `json:"show_incident_types,omitzero"`
}

func (f *FormConfigurationEntity) GetFields() *string {
	if f == nil {
		return nil
	}
	return f.Fields
}

func (f *FormConfigurationEntity) GetShowIncidentTypes() *string {
	if f == nil {
		return nil
	}
	return f.ShowIncidentTypes
}
