// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// FunctionalityEntityPaginated model
type FunctionalityEntityPaginated struct {
	Data       []FunctionalityEntity     `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (f FunctionalityEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FunctionalityEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FunctionalityEntityPaginated) GetData() []FunctionalityEntity {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FunctionalityEntityPaginated) GetPagination() *NullablePaginationEntity {
	if f == nil {
		return nil
	}
	return f.Pagination
}
