// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FunctionalityWithAllServicesEntity model
type FunctionalityWithAllServicesEntity struct {
	// Services this functionality provides
	Services []ServiceEntity `json:"services,omitempty"`
}

func (f *FunctionalityWithAllServicesEntity) GetServices() []ServiceEntity {
	if f == nil {
		return nil
	}
	return f.Services
}
