// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FunctionalityEntityPaginated model
type FunctionalityEntityPaginated struct {
	Data       []FunctionalityEntity     `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (f *FunctionalityEntityPaginated) GetData() []FunctionalityEntity {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FunctionalityEntityPaginated) GetPagination() *NullablePaginationEntity {
	if f == nil {
		return nil
	}
	return f.Pagination
}
