// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// IncidentRoleEntity model
type IncidentRoleEntity struct {
	ID          *string    `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Summary     *string    `json:"summary,omitempty"`
	Description *string    `json:"description,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	DiscardedAt *time.Time `json:"discarded_at,omitempty"`
}

func (i IncidentRoleEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IncidentRoleEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IncidentRoleEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncidentRoleEntity) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *IncidentRoleEntity) GetSummary() *string {
	if i == nil {
		return nil
	}
	return i.Summary
}

func (i *IncidentRoleEntity) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IncidentRoleEntity) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *IncidentRoleEntity) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *IncidentRoleEntity) GetDiscardedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.DiscardedAt
}
