// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IncidentEntityPaginated model
type IncidentEntityPaginated struct {
	Data       []IncidentEntity          `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (i *IncidentEntityPaginated) GetData() []IncidentEntity {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IncidentEntityPaginated) GetPagination() *NullablePaginationEntity {
	if i == nil {
		return nil
	}
	return i.Pagination
}
