// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IncidentImpactEntity model
type IncidentImpactEntity struct {
	ID             *string                 `json:"id,omitempty"`
	Type           *string                 `json:"type,omitempty"`
	Infrastructure *NullableSuccinctEntity `json:"infrastructure,omitempty"`
}

func (i *IncidentImpactEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncidentImpactEntity) GetType() *string {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *IncidentImpactEntity) GetInfrastructure() *NullableSuccinctEntity {
	if i == nil {
		return nil
	}
	return i.Infrastructure
}
