// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IncidentsConferenceBridgeEntityAttachment struct {
}

// IncidentsConferenceBridgeEntity - Incidents_ConferenceBridgeEntity model
type IncidentsConferenceBridgeEntity struct {
	ID *string `json:"id,omitempty"`
	// A list of objects attached to this item. Can be one of: LinkEntity, CustomerSupportIssueEntity, or GenericAttachmentEntity
	Attachments              []IncidentsConferenceBridgeEntityAttachment `json:"attachments,omitempty"`
	HasTranslatedTranscripts *bool                                       `json:"has_translated_transcripts,omitempty"`
	// A list of language codes that have translated transcripts for this conference bridge
	LanguageCodes          []string `json:"language_codes,omitempty"`
	TranscriptionStatus    *string  `json:"transcription_status,omitempty"`
	TranscriptionSubCode   *string  `json:"transcription_sub_code,omitempty"`
	PreviousHostAssignment *string  `json:"previous_host_assignment,omitempty"`
}

func (i *IncidentsConferenceBridgeEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncidentsConferenceBridgeEntity) GetAttachments() []IncidentsConferenceBridgeEntityAttachment {
	if i == nil {
		return nil
	}
	return i.Attachments
}

func (i *IncidentsConferenceBridgeEntity) GetHasTranslatedTranscripts() *bool {
	if i == nil {
		return nil
	}
	return i.HasTranslatedTranscripts
}

func (i *IncidentsConferenceBridgeEntity) GetLanguageCodes() []string {
	if i == nil {
		return nil
	}
	return i.LanguageCodes
}

func (i *IncidentsConferenceBridgeEntity) GetTranscriptionStatus() *string {
	if i == nil {
		return nil
	}
	return i.TranscriptionStatus
}

func (i *IncidentsConferenceBridgeEntity) GetTranscriptionSubCode() *string {
	if i == nil {
		return nil
	}
	return i.TranscriptionSubCode
}

func (i *IncidentsConferenceBridgeEntity) GetPreviousHostAssignment() *string {
	if i == nil {
		return nil
	}
	return i.PreviousHostAssignment
}
