// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IncidentsChannelEntity - Incidents_ChannelEntity model
type IncidentsChannelEntity struct {
	ID         *string `json:"id,omitzero"`
	Name       *string `json:"name,omitzero"`
	Source     *string `json:"source,omitzero"`
	SourceName *string `json:"source_name,omitzero"`
	SourceID   *string `json:"source_id,omitzero"`
	URL        *string `json:"url,omitzero"`
	IconURL    *string `json:"icon_url,omitzero"`
	Status     *string `json:"status,omitzero"`
}

func (i *IncidentsChannelEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IncidentsChannelEntity) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *IncidentsChannelEntity) GetSource() *string {
	if i == nil {
		return nil
	}
	return i.Source
}

func (i *IncidentsChannelEntity) GetSourceName() *string {
	if i == nil {
		return nil
	}
	return i.SourceName
}

func (i *IncidentsChannelEntity) GetSourceID() *string {
	if i == nil {
		return nil
	}
	return i.SourceID
}

func (i *IncidentsChannelEntity) GetURL() *string {
	if i == nil {
		return nil
	}
	return i.URL
}

func (i *IncidentsChannelEntity) GetIconURL() *string {
	if i == nil {
		return nil
	}
	return i.IconURL
}

func (i *IncidentsChannelEntity) GetStatus() *string {
	if i == nil {
		return nil
	}
	return i.Status
}
