// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// IncidentTypeEntityPaginated model
type IncidentTypeEntityPaginated struct {
	Data       []IncidentTypeEntity      `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (i IncidentTypeEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IncidentTypeEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IncidentTypeEntityPaginated) GetData() []IncidentTypeEntity {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IncidentTypeEntityPaginated) GetPagination() *NullablePaginationEntity {
	if i == nil {
		return nil
	}
	return i.Pagination
}
