// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IncidentTypeEntityPaginated model
type IncidentTypeEntityPaginated struct {
	Data       []IncidentTypeEntity      `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (i *IncidentTypeEntityPaginated) GetData() []IncidentTypeEntity {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IncidentTypeEntityPaginated) GetPagination() *NullablePaginationEntity {
	if i == nil {
		return nil
	}
	return i.Pagination
}
