// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IncidentsExportRetrospectiveMarkdownEntity - Incidents_ExportRetrospectiveMarkdownEntity model
type IncidentsExportRetrospectiveMarkdownEntity struct {
	// The retrospective content rendered as markdown.
	Markdown *string `json:"markdown,omitzero"`
}

func (i *IncidentsExportRetrospectiveMarkdownEntity) GetMarkdown() *string {
	if i == nil {
		return nil
	}
	return i.Markdown
}
