// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IncidentEntityFieldRequirementEntity struct {
	// A unique identifier for the field.
	FieldID *string `json:"field_id,omitzero"`
	// The milestone at which this field is required. If null, this field is always required.
	RequiredAtMilestoneID *string `json:"required_at_milestone_id,omitzero"`
}

func (i *IncidentEntityFieldRequirementEntity) GetFieldID() *string {
	if i == nil {
		return nil
	}
	return i.FieldID
}

func (i *IncidentEntityFieldRequirementEntity) GetRequiredAtMilestoneID() *string {
	if i == nil {
		return nil
	}
	return i.RequiredAtMilestoneID
}
