// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// IncidentsStatusPageEntityPaginated - Incidents_StatusPageEntityPaginated model
type IncidentsStatusPageEntityPaginated struct {
	Data       []IncidentsStatusPageEntity `json:"data,omitzero"`
	Pagination *NullablePaginationEntity   `json:"pagination,omitzero"`
}

func (i IncidentsStatusPageEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IncidentsStatusPageEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IncidentsStatusPageEntityPaginated) GetData() []IncidentsStatusPageEntity {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IncidentsStatusPageEntityPaginated) GetPagination() *NullablePaginationEntity {
	if i == nil {
		return nil
	}
	return i.Pagination
}
