// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InfrastructureSearchEntity model
type InfrastructureSearchEntity struct {
	Type           *string `json:"type,omitzero"`
	Infrastructure *string `json:"infrastructure,omitzero"`
}

func (i *InfrastructureSearchEntity) GetType() *string {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *InfrastructureSearchEntity) GetInfrastructure() *string {
	if i == nil {
		return nil
	}
	return i.Infrastructure
}
