// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type IntegrationsAwsConnectionEntityConnectionStatus string

const (
	IntegrationsAwsConnectionEntityConnectionStatusPendingSetup       IntegrationsAwsConnectionEntityConnectionStatus = "pending_setup"
	IntegrationsAwsConnectionEntityConnectionStatusRoleAssumed        IntegrationsAwsConnectionEntityConnectionStatus = "role_assumed"
	IntegrationsAwsConnectionEntityConnectionStatusCantAssumeRole     IntegrationsAwsConnectionEntityConnectionStatus = "cant_assume_role"
	IntegrationsAwsConnectionEntityConnectionStatusInvalidPermissions IntegrationsAwsConnectionEntityConnectionStatus = "invalid_permissions"
	IntegrationsAwsConnectionEntityConnectionStatusValidated          IntegrationsAwsConnectionEntityConnectionStatus = "validated"
)

func (e IntegrationsAwsConnectionEntityConnectionStatus) ToPointer() *IntegrationsAwsConnectionEntityConnectionStatus {
	return &e
}
func (e *IntegrationsAwsConnectionEntityConnectionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending_setup":
		fallthrough
	case "role_assumed":
		fallthrough
	case "cant_assume_role":
		fallthrough
	case "invalid_permissions":
		fallthrough
	case "validated":
		*e = IntegrationsAwsConnectionEntityConnectionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationsAwsConnectionEntityConnectionStatus: %v", v)
	}
}

// IntegrationsAwsConnectionEntity - Integrations_Aws_ConnectionEntity model
type IntegrationsAwsConnectionEntity struct {
	ID                *string                                          `json:"id,omitempty"`
	AwsAccountID      *string                                          `json:"aws_account_id,omitempty"`
	TargetArn         *string                                          `json:"target_arn,omitempty"`
	ExternalID        *string                                          `json:"external_id,omitempty"`
	ConnectionStatus  *IntegrationsAwsConnectionEntityConnectionStatus `json:"connection_status,omitempty"`
	StatusText        *string                                          `json:"status_text,omitempty"`
	StatusDescription *string                                          `json:"status_description,omitempty"`
	EnvironmentID     *string                                          `json:"environment_id,omitempty"`
	EnvironmentName   *string                                          `json:"environment_name,omitempty"`
	Regions           []string                                         `json:"regions,omitempty"`
}

func (i *IntegrationsAwsConnectionEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IntegrationsAwsConnectionEntity) GetAwsAccountID() *string {
	if i == nil {
		return nil
	}
	return i.AwsAccountID
}

func (i *IntegrationsAwsConnectionEntity) GetTargetArn() *string {
	if i == nil {
		return nil
	}
	return i.TargetArn
}

func (i *IntegrationsAwsConnectionEntity) GetExternalID() *string {
	if i == nil {
		return nil
	}
	return i.ExternalID
}

func (i *IntegrationsAwsConnectionEntity) GetConnectionStatus() *IntegrationsAwsConnectionEntityConnectionStatus {
	if i == nil {
		return nil
	}
	return i.ConnectionStatus
}

func (i *IntegrationsAwsConnectionEntity) GetStatusText() *string {
	if i == nil {
		return nil
	}
	return i.StatusText
}

func (i *IntegrationsAwsConnectionEntity) GetStatusDescription() *string {
	if i == nil {
		return nil
	}
	return i.StatusDescription
}

func (i *IntegrationsAwsConnectionEntity) GetEnvironmentID() *string {
	if i == nil {
		return nil
	}
	return i.EnvironmentID
}

func (i *IntegrationsAwsConnectionEntity) GetEnvironmentName() *string {
	if i == nil {
		return nil
	}
	return i.EnvironmentName
}

func (i *IntegrationsAwsConnectionEntity) GetRegions() []string {
	if i == nil {
		return nil
	}
	return i.Regions
}
