// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// IntegrationsIntegrationEntity - Integrations_IntegrationEntity model
type IntegrationsIntegrationEntity struct {
	ID          *string                                          `json:"id,omitzero"`
	Slug        *string                                          `json:"slug,omitzero"`
	Name        *string                                          `json:"name,omitzero"`
	Description *string                                          `json:"description,omitzero"`
	SetupURL    *string                                          `json:"setup_url,omitzero"`
	CreatedAt   *time.Time                                       `json:"created_at,omitzero"`
	Connections []IntegrationsConnectionEntity                   `json:"connections,omitzero"`
	Enabled     *bool                                            `json:"enabled,omitzero"`
	Installed   *bool                                            `json:"installed,omitzero"`
	Deprecated  *bool                                            `json:"deprecated,omitzero"`
	Logo        *NullableIntegrationsIntegrationEntityLogoEntity `json:"logo,omitzero"`
	NatIP       *string                                          `json:"nat_ip,omitzero"`
}

func (i IntegrationsIntegrationEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationsIntegrationEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationsIntegrationEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IntegrationsIntegrationEntity) GetSlug() *string {
	if i == nil {
		return nil
	}
	return i.Slug
}

func (i *IntegrationsIntegrationEntity) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}

func (i *IntegrationsIntegrationEntity) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntegrationsIntegrationEntity) GetSetupURL() *string {
	if i == nil {
		return nil
	}
	return i.SetupURL
}

func (i *IntegrationsIntegrationEntity) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *IntegrationsIntegrationEntity) GetConnections() []IntegrationsConnectionEntity {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *IntegrationsIntegrationEntity) GetEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.Enabled
}

func (i *IntegrationsIntegrationEntity) GetInstalled() *bool {
	if i == nil {
		return nil
	}
	return i.Installed
}

func (i *IntegrationsIntegrationEntity) GetDeprecated() *bool {
	if i == nil {
		return nil
	}
	return i.Deprecated
}

func (i *IntegrationsIntegrationEntity) GetLogo() *NullableIntegrationsIntegrationEntityLogoEntity {
	if i == nil {
		return nil
	}
	return i.Logo
}

func (i *IntegrationsIntegrationEntity) GetNatIP() *string {
	if i == nil {
		return nil
	}
	return i.NatIP
}
