// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IntegrationsSlackWorkspaceEntity - Integrations_Slack_WorkspaceEntity model
type IntegrationsSlackWorkspaceEntity struct {
	ID     *string `json:"id,omitzero"`
	TeamID *string `json:"team_id,omitzero"`
	Name   *string `json:"name,omitzero"`
}

func (i *IntegrationsSlackWorkspaceEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IntegrationsSlackWorkspaceEntity) GetTeamID() *string {
	if i == nil {
		return nil
	}
	return i.TeamID
}

func (i *IntegrationsSlackWorkspaceEntity) GetName() *string {
	if i == nil {
		return nil
	}
	return i.Name
}
