// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IntegrationsStatuspageSeverityEntity struct {
	SeveritySlug *string `json:"severity_slug,omitzero"`
	RemoteStatus *string `json:"remote_status,omitzero"`
}

func (i *IntegrationsStatuspageSeverityEntity) GetSeveritySlug() *string {
	if i == nil {
		return nil
	}
	return i.SeveritySlug
}

func (i *IntegrationsStatuspageSeverityEntity) GetRemoteStatus() *string {
	if i == nil {
		return nil
	}
	return i.RemoteStatus
}
