// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// IntegrationsStatuspageConnectionEntity - Integrations_Statuspage_ConnectionEntity model
type IntegrationsStatuspageConnectionEntity struct {
	ID                *string                                        `json:"id,omitzero"`
	PageName          *string                                        `json:"page_name,omitzero"`
	PageID            *string                                        `json:"page_id,omitzero"`
	Conditions        []IntegrationsStatuspageConditionEntity        `json:"conditions,omitzero"`
	Severities        []IntegrationsStatuspageSeverityEntity         `json:"severities,omitzero"`
	MilestoneMappings []IntegrationsStatuspageMilestoneMappingEntity `json:"milestone_mappings,omitzero"`
}

func (i IntegrationsStatuspageConnectionEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationsStatuspageConnectionEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationsStatuspageConnectionEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IntegrationsStatuspageConnectionEntity) GetPageName() *string {
	if i == nil {
		return nil
	}
	return i.PageName
}

func (i *IntegrationsStatuspageConnectionEntity) GetPageID() *string {
	if i == nil {
		return nil
	}
	return i.PageID
}

func (i *IntegrationsStatuspageConnectionEntity) GetConditions() []IntegrationsStatuspageConditionEntity {
	if i == nil {
		return nil
	}
	return i.Conditions
}

func (i *IntegrationsStatuspageConnectionEntity) GetSeverities() []IntegrationsStatuspageSeverityEntity {
	if i == nil {
		return nil
	}
	return i.Severities
}

func (i *IntegrationsStatuspageConnectionEntity) GetMilestoneMappings() []IntegrationsStatuspageMilestoneMappingEntity {
	if i == nil {
		return nil
	}
	return i.MilestoneMappings
}
