// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type IntegrationsAwsCloudtrailBatchEntityStatus string

const (
	IntegrationsAwsCloudtrailBatchEntityStatusInProgress IntegrationsAwsCloudtrailBatchEntityStatus = "in_progress"
	IntegrationsAwsCloudtrailBatchEntityStatusFailed     IntegrationsAwsCloudtrailBatchEntityStatus = "failed"
	IntegrationsAwsCloudtrailBatchEntityStatusSuccessful IntegrationsAwsCloudtrailBatchEntityStatus = "successful"
	IntegrationsAwsCloudtrailBatchEntityStatusPending    IntegrationsAwsCloudtrailBatchEntityStatus = "pending"
	IntegrationsAwsCloudtrailBatchEntityStatusRetried    IntegrationsAwsCloudtrailBatchEntityStatus = "retried"
)

func (e IntegrationsAwsCloudtrailBatchEntityStatus) ToPointer() *IntegrationsAwsCloudtrailBatchEntityStatus {
	return &e
}
func (e *IntegrationsAwsCloudtrailBatchEntityStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_progress":
		fallthrough
	case "failed":
		fallthrough
	case "successful":
		fallthrough
	case "pending":
		fallthrough
	case "retried":
		*e = IntegrationsAwsCloudtrailBatchEntityStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationsAwsCloudtrailBatchEntityStatus: %v", v)
	}
}

// IntegrationsAwsCloudtrailBatchEntity - Integrations_Aws_CloudtrailBatchEntity model
type IntegrationsAwsCloudtrailBatchEntity struct {
	ID            *string                                     `json:"id,omitzero"`
	EventsCreated *int                                        `json:"events_created,omitzero"`
	Status        *IntegrationsAwsCloudtrailBatchEntityStatus `json:"status,omitzero"`
	StartsAt      *time.Time                                  `json:"starts_at,omitzero"`
	EndsAt        *time.Time                                  `json:"ends_at,omitzero"`
	Connection    *NullableIntegrationsAwsConnectionEntity    `json:"connection,omitzero"`
	CreatedAt     *time.Time                                  `json:"created_at,omitzero"`
}

func (i IntegrationsAwsCloudtrailBatchEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationsAwsCloudtrailBatchEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetEventsCreated() *int {
	if i == nil {
		return nil
	}
	return i.EventsCreated
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetStatus() *IntegrationsAwsCloudtrailBatchEntityStatus {
	if i == nil {
		return nil
	}
	return i.Status
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetStartsAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.StartsAt
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetEndsAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.EndsAt
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetConnection() *NullableIntegrationsAwsConnectionEntity {
	if i == nil {
		return nil
	}
	return i.Connection
}

func (i *IntegrationsAwsCloudtrailBatchEntity) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}
