// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// IntegrationsConnectionEntityPaginated - Integrations_ConnectionEntityPaginated model
type IntegrationsConnectionEntityPaginated struct {
	Data       []IntegrationsConnectionEntity `json:"data,omitzero"`
	Pagination *NullablePaginationEntity      `json:"pagination,omitzero"`
}

func (i IntegrationsConnectionEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationsConnectionEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IntegrationsConnectionEntityPaginated) GetData() []IntegrationsConnectionEntity {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IntegrationsConnectionEntityPaginated) GetPagination() *NullablePaginationEntity {
	if i == nil {
		return nil
	}
	return i.Pagination
}
