// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IntegrationsStatuspageMilestoneMappingEntity struct {
	MilestoneID *string `json:"milestone_id,omitzero"`
	Status      *string `json:"status,omitzero"`
}

func (i *IntegrationsStatuspageMilestoneMappingEntity) GetMilestoneID() *string {
	if i == nil {
		return nil
	}
	return i.MilestoneID
}

func (i *IntegrationsStatuspageMilestoneMappingEntity) GetStatus() *string {
	if i == nil {
		return nil
	}
	return i.Status
}
