// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// IntegrationsZendeskSupportIssueEntityData - Raw data associated with this issue from originating system.
type IntegrationsZendeskSupportIssueEntityData struct {
}

type IntegrationsZendeskSupportIssueEntity struct {
	// The ID of this support issue in the system that originated this issue, eg Zendesk.
	RemoteID *string `json:"remote_id,omitempty"`
	// Title or name of this issue.
	Title *string `json:"title,omitempty"`
	// Longer description of the issue.
	Description *string `json:"description,omitempty"`
	// Browser-accessible url for this issue in the originating system, eg Zendesk.
	RemoteURL *string `json:"remote_url,omitempty"`
	// Raw data associated with this issue from originating system.
	Data *IntegrationsZendeskSupportIssueEntityData `json:"data,omitempty"`
	// Attachment information for this issue.
	Attachments       *string                                                      `json:"attachments,omitempty"`
	Customers         *NullableIntegrationsZendeskSupportIssueEntityCustomerEntity `json:"customers,omitempty"`
	Priority          *string                                                      `json:"priority,omitempty"`
	AttachedIncidents []IncidentEntity                                             `json:"attached_incidents,omitempty"`
	// Type designator for this entity
	Type *string `json:"type,omitempty"`
}

func (i *IntegrationsZendeskSupportIssueEntity) GetRemoteID() *string {
	if i == nil {
		return nil
	}
	return i.RemoteID
}

func (i *IntegrationsZendeskSupportIssueEntity) GetTitle() *string {
	if i == nil {
		return nil
	}
	return i.Title
}

func (i *IntegrationsZendeskSupportIssueEntity) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntegrationsZendeskSupportIssueEntity) GetRemoteURL() *string {
	if i == nil {
		return nil
	}
	return i.RemoteURL
}

func (i *IntegrationsZendeskSupportIssueEntity) GetData() *IntegrationsZendeskSupportIssueEntityData {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IntegrationsZendeskSupportIssueEntity) GetAttachments() *string {
	if i == nil {
		return nil
	}
	return i.Attachments
}

func (i *IntegrationsZendeskSupportIssueEntity) GetCustomers() *NullableIntegrationsZendeskSupportIssueEntityCustomerEntity {
	if i == nil {
		return nil
	}
	return i.Customers
}

func (i *IntegrationsZendeskSupportIssueEntity) GetPriority() *string {
	if i == nil {
		return nil
	}
	return i.Priority
}

func (i *IntegrationsZendeskSupportIssueEntity) GetAttachedIncidents() []IncidentEntity {
	if i == nil {
		return nil
	}
	return i.AttachedIncidents
}

func (i *IntegrationsZendeskSupportIssueEntity) GetType() *string {
	if i == nil {
		return nil
	}
	return i.Type
}
