// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type StatuspageioCondition string

const (
	StatuspageioConditionOperational         StatuspageioCondition = "operational"
	StatuspageioConditionMajorOutage         StatuspageioCondition = "major_outage"
	StatuspageioConditionMinorOutage         StatuspageioCondition = "minor_outage"
	StatuspageioConditionDegradedPerformance StatuspageioCondition = "degraded_performance"
)

func (e StatuspageioCondition) ToPointer() *StatuspageioCondition {
	return &e
}
func (e *StatuspageioCondition) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "operational":
		fallthrough
	case "major_outage":
		fallthrough
	case "minor_outage":
		fallthrough
	case "degraded_performance":
		*e = StatuspageioCondition(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StatuspageioCondition: %v", v)
	}
}

type IntegrationsStatuspageConditionEntity struct {
	ConditionID           *string                `json:"condition_id,omitzero"`
	ConditionName         *string                `json:"condition_name,omitzero"`
	StatuspageioCondition *StatuspageioCondition `json:"statuspageio_condition,omitzero"`
}

func (i *IntegrationsStatuspageConditionEntity) GetConditionID() *string {
	if i == nil {
		return nil
	}
	return i.ConditionID
}

func (i *IntegrationsStatuspageConditionEntity) GetConditionName() *string {
	if i == nil {
		return nil
	}
	return i.ConditionName
}

func (i *IntegrationsStatuspageConditionEntity) GetStatuspageioCondition() *StatuspageioCondition {
	if i == nil {
		return nil
	}
	return i.StatuspageioCondition
}
