// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricsTicketFunnelMetricsEntity - Metrics_TicketFunnelMetricsEntity model
type MetricsTicketFunnelMetricsEntity struct {
	Data      []MetricsTicketFunnelMetricsEntityDataBucketEntity       `json:"data,omitempty"`
	Groupings *NullableMetricsTicketFunnelMetricsEntityGroupingsEntity `json:"groupings,omitempty"`
}

func (m *MetricsTicketFunnelMetricsEntity) GetData() []MetricsTicketFunnelMetricsEntityDataBucketEntity {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MetricsTicketFunnelMetricsEntity) GetGroupings() *NullableMetricsTicketFunnelMetricsEntityGroupingsEntity {
	if m == nil {
		return nil
	}
	return m.Groupings
}
