// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsMilestonesFunnelEntityColumnEntity struct {
	// The slug of the milestone
	Name *string `json:"name,omitempty"`
	// The name of the milestone
	Label *string `json:"label,omitempty"`
	// The description of the milestone
	Tooltip *string `json:"tooltip,omitempty"`
	// The UUID of the milestone
	ID *string `json:"id,omitempty"`
}

func (m *MetricsMilestonesFunnelEntityColumnEntity) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MetricsMilestonesFunnelEntityColumnEntity) GetLabel() *string {
	if m == nil {
		return nil
	}
	return m.Label
}

func (m *MetricsMilestonesFunnelEntityColumnEntity) GetTooltip() *string {
	if m == nil {
		return nil
	}
	return m.Tooltip
}

func (m *MetricsMilestonesFunnelEntityColumnEntity) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}
