// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DisplayInformation struct {
}

type Bucket struct {
}

// MetricsMetricsEntity - Metrics_MetricsEntity model
type MetricsMetricsEntity struct {
	Type *string `json:"type,omitempty"`
	// The field by which the metrics are grouped. Can be one of: total, severity, priority, functionality, service, environment, or user.
	By *string `json:"by,omitempty"`
	// The size of returned buckets. Can be one of: day, week, month, or all_time.
	BucketSize         *int                                    `json:"bucket_size,omitempty"`
	DisplayInformation *DisplayInformation                     `json:"display_information,omitempty"`
	Keys               []string                                `json:"keys,omitempty"`
	Buckets            []Bucket                                `json:"buckets,omitempty"`
	Sort               *NullableMetricsMetricsEntitySortEntity `json:"sort,omitempty"`
}

func (m *MetricsMetricsEntity) GetType() *string {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MetricsMetricsEntity) GetBy() *string {
	if m == nil {
		return nil
	}
	return m.By
}

func (m *MetricsMetricsEntity) GetBucketSize() *int {
	if m == nil {
		return nil
	}
	return m.BucketSize
}

func (m *MetricsMetricsEntity) GetDisplayInformation() *DisplayInformation {
	if m == nil {
		return nil
	}
	return m.DisplayInformation
}

func (m *MetricsMetricsEntity) GetKeys() []string {
	if m == nil {
		return nil
	}
	return m.Keys
}

func (m *MetricsMetricsEntity) GetBuckets() []Bucket {
	if m == nil {
		return nil
	}
	return m.Buckets
}

func (m *MetricsMetricsEntity) GetSort() *NullableMetricsMetricsEntitySortEntity {
	if m == nil {
		return nil
	}
	return m.Sort
}
