// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsMilestonesFunnelEntityDataBucketMilestoneCountEntity struct {
	// The UUID of the milestone
	MilestoneID *string `json:"milestone_id,omitempty"`
	// The frequency count of that milestone for the period
	Count *int `json:"count,omitempty"`
}

func (m *MetricsMilestonesFunnelEntityDataBucketMilestoneCountEntity) GetMilestoneID() *string {
	if m == nil {
		return nil
	}
	return m.MilestoneID
}

func (m *MetricsMilestonesFunnelEntityDataBucketMilestoneCountEntity) GetCount() *int {
	if m == nil {
		return nil
	}
	return m.Count
}
