// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type DisplayInformation struct {
}

type Bucket struct {
}

// MetricsMetricsEntity - Metrics_MetricsEntity model
type MetricsMetricsEntity struct {
	Type *string `json:"type,omitzero"`
	// The field by which the metrics are grouped. Can be one of: total, severity, priority, functionality, service, environment, or user.
	By *string `json:"by,omitzero"`
	// The size of returned buckets. Can be one of: day, week, month, or all_time.
	BucketSize         *int                                    `json:"bucket_size,omitzero"`
	DisplayInformation *DisplayInformation                     `json:"display_information,omitzero"`
	Keys               []string                                `json:"keys,omitzero"`
	Buckets            []Bucket                                `json:"buckets,omitzero"`
	Sort               *NullableMetricsMetricsEntitySortEntity `json:"sort,omitzero"`
}

func (m MetricsMetricsEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsMetricsEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsMetricsEntity) GetType() *string {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MetricsMetricsEntity) GetBy() *string {
	if m == nil {
		return nil
	}
	return m.By
}

func (m *MetricsMetricsEntity) GetBucketSize() *int {
	if m == nil {
		return nil
	}
	return m.BucketSize
}

func (m *MetricsMetricsEntity) GetDisplayInformation() *DisplayInformation {
	if m == nil {
		return nil
	}
	return m.DisplayInformation
}

func (m *MetricsMetricsEntity) GetKeys() []string {
	if m == nil {
		return nil
	}
	return m.Keys
}

func (m *MetricsMetricsEntity) GetBuckets() []Bucket {
	if m == nil {
		return nil
	}
	return m.Buckets
}

func (m *MetricsMetricsEntity) GetSort() *NullableMetricsMetricsEntitySortEntity {
	if m == nil {
		return nil
	}
	return m.Sort
}
