// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetricsRetrospectiveEntityDataEntity struct {
	X *string  `json:"x,omitzero"`
	Y *float32 `json:"y,omitzero"`
}

func (m *MetricsRetrospectiveEntityDataEntity) GetX() *string {
	if m == nil {
		return nil
	}
	return m.X
}

func (m *MetricsRetrospectiveEntityDataEntity) GetY() *float32 {
	if m == nil {
		return nil
	}
	return m.Y
}
