// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableIntegrationsIntegrationEntityLogoEntity struct {
	LogoURL *string `json:"logo_url,omitzero"`
}

func (n *NullableIntegrationsIntegrationEntityLogoEntity) GetLogoURL() *string {
	if n == nil {
		return nil
	}
	return n.LogoURL
}
