// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VersionsUrls - An object with keys that can have different versions of an image
type VersionsUrls struct {
}

type NullableMediaImageEntity struct {
	OriginalURL *string `json:"original_url,omitempty"`
	// An object with keys that can have different versions of an image
	VersionsUrls *VersionsUrls `json:"versions_urls,omitempty"`
}

func (n *NullableMediaImageEntity) GetOriginalURL() *string {
	if n == nil {
		return nil
	}
	return n.OriginalURL
}

func (n *NullableMediaImageEntity) GetVersionsUrls() *VersionsUrls {
	if n == nil {
		return nil
	}
	return n.VersionsUrls
}
