// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableScheduleEntity struct {
	ID          *string `json:"id,omitzero"`
	Name        *string `json:"name,omitzero"`
	Integration *string `json:"integration,omitzero"`
	Discarded   *bool   `json:"discarded,omitzero"`
}

func (n *NullableScheduleEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableScheduleEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableScheduleEntity) GetIntegration() *string {
	if n == nil {
		return nil
	}
	return n.Integration
}

func (n *NullableScheduleEntity) GetDiscarded() *bool {
	if n == nil {
		return nil
	}
	return n.Discarded
}
