// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIEscalationPolicyHandoffStepEntity struct {
	ID     *string                         `json:"id,omitempty"`
	Target *NullableSignalsAPITargetEntity `json:"target,omitempty"`
}

func (n *NullableSignalsAPIEscalationPolicyHandoffStepEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableSignalsAPIEscalationPolicyHandoffStepEntity) GetTarget() *NullableSignalsAPITargetEntity {
	if n == nil {
		return nil
	}
	return n.Target
}
