// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableRunbooksElementTextareaEntity struct {
	Label        *string `json:"label,omitzero"`
	Placeholder  *string `json:"placeholder,omitzero"`
	DefaultValue *string `json:"default_value,omitzero"`
}

func (n *NullableRunbooksElementTextareaEntity) GetLabel() *string {
	if n == nil {
		return nil
	}
	return n.Label
}

func (n *NullableRunbooksElementTextareaEntity) GetPlaceholder() *string {
	if n == nil {
		return nil
	}
	return n.Placeholder
}

func (n *NullableRunbooksElementTextareaEntity) GetDefaultValue() *string {
	if n == nil {
		return nil
	}
	return n.DefaultValue
}
