// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type NullableImportsImportableResourceEntityState string

const (
	NullableImportsImportableResourceEntityStateSelected NullableImportsImportableResourceEntityState = "selected"
	NullableImportsImportableResourceEntityStateSkipped  NullableImportsImportableResourceEntityState = "skipped"
	NullableImportsImportableResourceEntityStateImported NullableImportsImportableResourceEntityState = "imported"
	NullableImportsImportableResourceEntityStateErrored  NullableImportsImportableResourceEntityState = "errored"
)

func (e NullableImportsImportableResourceEntityState) ToPointer() *NullableImportsImportableResourceEntityState {
	return &e
}
func (e *NullableImportsImportableResourceEntityState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "selected":
		fallthrough
	case "skipped":
		fallthrough
	case "imported":
		fallthrough
	case "errored":
		*e = NullableImportsImportableResourceEntityState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NullableImportsImportableResourceEntityState: %v", v)
	}
}

type NullableImportsImportableResourceEntity struct {
	ImportErrors []ImportsImportErrorEntity                    `json:"import_errors,omitzero"`
	ImportedAt   *time.Time                                    `json:"imported_at,omitzero"`
	RemoteID     *string                                       `json:"remote_id,omitzero"`
	State        *NullableImportsImportableResourceEntityState `json:"state,omitzero"`
}

func (n NullableImportsImportableResourceEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableImportsImportableResourceEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableImportsImportableResourceEntity) GetImportErrors() []ImportsImportErrorEntity {
	if n == nil {
		return nil
	}
	return n.ImportErrors
}

func (n *NullableImportsImportableResourceEntity) GetImportedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.ImportedAt
}

func (n *NullableImportsImportableResourceEntity) GetRemoteID() *string {
	if n == nil {
		return nil
	}
	return n.RemoteID
}

func (n *NullableImportsImportableResourceEntity) GetState() *NullableImportsImportableResourceEntityState {
	if n == nil {
		return nil
	}
	return n.State
}
