// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// NullableUserEntity - UserEntity model
type NullableUserEntity struct {
	ID                                  *string                                            `json:"id,omitzero"`
	Name                                *string                                            `json:"name,omitzero"`
	Email                               *string                                            `json:"email,omitzero"`
	SlackUserID                         *string                                            `json:"slack_user_id,omitzero"`
	Role                                *string                                            `json:"role,omitzero"`
	SlackLinked                         *bool                                              `json:"slack_linked?,omitzero"`
	CreatedAt                           *time.Time                                         `json:"created_at,omitzero"`
	UpdatedAt                           *time.Time                                         `json:"updated_at,omitzero"`
	SignalsEnabledNotificationTypes     []string                                           `json:"signals_enabled_notification_types,omitzero"`
	SignalsNotificationPolicyCompliance []SignalsAPINotificationPolicyItemComplianceEntity `json:"signals_notification_policy_compliance,omitzero"`
}

func (n NullableUserEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableUserEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableUserEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableUserEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableUserEntity) GetEmail() *string {
	if n == nil {
		return nil
	}
	return n.Email
}

func (n *NullableUserEntity) GetSlackUserID() *string {
	if n == nil {
		return nil
	}
	return n.SlackUserID
}

func (n *NullableUserEntity) GetRole() *string {
	if n == nil {
		return nil
	}
	return n.Role
}

func (n *NullableUserEntity) GetSlackLinked() *bool {
	if n == nil {
		return nil
	}
	return n.SlackLinked
}

func (n *NullableUserEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NullableUserEntity) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}

func (n *NullableUserEntity) GetSignalsEnabledNotificationTypes() []string {
	if n == nil {
		return nil
	}
	return n.SignalsEnabledNotificationTypes
}

func (n *NullableUserEntity) GetSignalsNotificationPolicyCompliance() []SignalsAPINotificationPolicyItemComplianceEntity {
	if n == nil {
		return nil
	}
	return n.SignalsNotificationPolicyCompliance
}
