// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type NullableTicketingProjectFieldMapExternalValueEntityType string

const (
	NullableTicketingProjectFieldMapExternalValueEntityTypeLiteral     NullableTicketingProjectFieldMapExternalValueEntityType = "literal"
	NullableTicketingProjectFieldMapExternalValueEntityTypeFhAttribute NullableTicketingProjectFieldMapExternalValueEntityType = "fh-attribute"
	NullableTicketingProjectFieldMapExternalValueEntityTypeFhType      NullableTicketingProjectFieldMapExternalValueEntityType = "fh-type"
)

func (e NullableTicketingProjectFieldMapExternalValueEntityType) ToPointer() *NullableTicketingProjectFieldMapExternalValueEntityType {
	return &e
}
func (e *NullableTicketingProjectFieldMapExternalValueEntityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "literal":
		fallthrough
	case "fh-attribute":
		fallthrough
	case "fh-type":
		*e = NullableTicketingProjectFieldMapExternalValueEntityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NullableTicketingProjectFieldMapExternalValueEntityType: %v", v)
	}
}

type NullableTicketingProjectFieldMapExternalValueEntity struct {
	Type         *NullableTicketingProjectFieldMapExternalValueEntityType `json:"type,omitzero"`
	Value        *string                                                  `json:"value,omitzero"`
	Attribute    *string                                                  `json:"attribute,omitzero"`
	Presentation *string                                                  `json:"presentation,omitzero"`
}

func (n *NullableTicketingProjectFieldMapExternalValueEntity) GetType() *NullableTicketingProjectFieldMapExternalValueEntityType {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NullableTicketingProjectFieldMapExternalValueEntity) GetValue() *string {
	if n == nil {
		return nil
	}
	return n.Value
}

func (n *NullableTicketingProjectFieldMapExternalValueEntity) GetAttribute() *string {
	if n == nil {
		return nil
	}
	return n.Attribute
}

func (n *NullableTicketingProjectFieldMapExternalValueEntity) GetPresentation() *string {
	if n == nil {
		return nil
	}
	return n.Presentation
}
