// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullablePublicAPIV1IncidentsSuccinctEntity struct {
	ID     *string `json:"id,omitzero"`
	Name   *string `json:"name,omitzero"`
	Number *int    `json:"number,omitzero"`
}

func (n *NullablePublicAPIV1IncidentsSuccinctEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullablePublicAPIV1IncidentsSuccinctEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullablePublicAPIV1IncidentsSuccinctEntity) GetNumber() *int {
	if n == nil {
		return nil
	}
	return n.Number
}
