// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableFHTypesGenericEntity struct {
	Type  *string `json:"type,omitzero"`
	Value *string `json:"value,omitzero"`
	Label *string `json:"label,omitzero"`
}

func (n *NullableFHTypesGenericEntity) GetType() *string {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NullableFHTypesGenericEntity) GetValue() *string {
	if n == nil {
		return nil
	}
	return n.Value
}

func (n *NullableFHTypesGenericEntity) GetLabel() *string {
	if n == nil {
		return nil
	}
	return n.Label
}
