// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// NullableIncidentRoleEntity - IncidentRoleEntity model
type NullableIncidentRoleEntity struct {
	ID          *string    `json:"id,omitzero"`
	Name        *string    `json:"name,omitzero"`
	Summary     *string    `json:"summary,omitzero"`
	Description *string    `json:"description,omitzero"`
	CreatedAt   *time.Time `json:"created_at,omitzero"`
	UpdatedAt   *time.Time `json:"updated_at,omitzero"`
	DiscardedAt *time.Time `json:"discarded_at,omitzero"`
}

func (n NullableIncidentRoleEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableIncidentRoleEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableIncidentRoleEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableIncidentRoleEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableIncidentRoleEntity) GetSummary() *string {
	if n == nil {
		return nil
	}
	return n.Summary
}

func (n *NullableIncidentRoleEntity) GetDescription() *string {
	if n == nil {
		return nil
	}
	return n.Description
}

func (n *NullableIncidentRoleEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NullableIncidentRoleEntity) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}

func (n *NullableIncidentRoleEntity) GetDiscardedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.DiscardedAt
}
