// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableNuncConditionEntity struct {
	NuncCondition *string `json:"nunc_condition,omitzero"`
	ConditionName *string `json:"condition_name,omitzero"`
	ConditionID   *string `json:"condition_id,omitzero"`
}

func (n *NullableNuncConditionEntity) GetNuncCondition() *string {
	if n == nil {
		return nil
	}
	return n.NuncCondition
}

func (n *NullableNuncConditionEntity) GetConditionName() *string {
	if n == nil {
		return nil
	}
	return n.ConditionName
}

func (n *NullableNuncConditionEntity) GetConditionID() *string {
	if n == nil {
		return nil
	}
	return n.ConditionID
}
