// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIGroupingEntityActionEntityFyiEntity struct {
	SlackChannels []IntegrationsSlackSlackChannelEntity `json:"slack_channels,omitempty"`
}

func (n *NullableSignalsAPIGroupingEntityActionEntityFyiEntity) GetSlackChannels() []IntegrationsSlackSlackChannelEntity {
	if n == nil {
		return nil
	}
	return n.SlackChannels
}
