// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableNuncComponentEntity struct {
	InfrastructureType *string `json:"infrastructure_type,omitempty"`
	InfrastructureID   *string `json:"infrastructure_id,omitempty"`
	Label              *string `json:"label,omitempty"`
	Position           *int    `json:"position,omitempty"`
	ComponentGroupID   *string `json:"component_group_id,omitempty"`
}

func (n *NullableNuncComponentEntity) GetInfrastructureType() *string {
	if n == nil {
		return nil
	}
	return n.InfrastructureType
}

func (n *NullableNuncComponentEntity) GetInfrastructureID() *string {
	if n == nil {
		return nil
	}
	return n.InfrastructureID
}

func (n *NullableNuncComponentEntity) GetLabel() *string {
	if n == nil {
		return nil
	}
	return n.Label
}

func (n *NullableNuncComponentEntity) GetPosition() *int {
	if n == nil {
		return nil
	}
	return n.Position
}

func (n *NullableNuncComponentEntity) GetComponentGroupID() *string {
	if n == nil {
		return nil
	}
	return n.ComponentGroupID
}
