// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIOnCallStrategyEntity struct {
	Type          *string `json:"type,omitempty"`
	HandoffTime   *string `json:"handoff_time,omitempty"`
	HandoffDay    *string `json:"handoff_day,omitempty"`
	ShiftDuration *string `json:"shift_duration,omitempty"`
}

func (o *NullableSignalsAPIOnCallStrategyEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *NullableSignalsAPIOnCallStrategyEntity) GetHandoffTime() *string {
	if o == nil {
		return nil
	}
	return o.HandoffTime
}

func (o *NullableSignalsAPIOnCallStrategyEntity) GetHandoffDay() *string {
	if o == nil {
		return nil
	}
	return o.HandoffDay
}

func (o *NullableSignalsAPIOnCallStrategyEntity) GetShiftDuration() *string {
	if o == nil {
		return nil
	}
	return o.ShiftDuration
}
