// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIOnCallStrategyEntity struct {
	Type          *string `json:"type,omitempty"`
	HandoffTime   *string `json:"handoff_time,omitempty"`
	HandoffDay    *string `json:"handoff_day,omitempty"`
	ShiftDuration *string `json:"shift_duration,omitempty"`
}

func (n *NullableSignalsAPIOnCallStrategyEntity) GetType() *string {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NullableSignalsAPIOnCallStrategyEntity) GetHandoffTime() *string {
	if n == nil {
		return nil
	}
	return n.HandoffTime
}

func (n *NullableSignalsAPIOnCallStrategyEntity) GetHandoffDay() *string {
	if n == nil {
		return nil
	}
	return n.HandoffDay
}

func (n *NullableSignalsAPIOnCallStrategyEntity) GetShiftDuration() *string {
	if n == nil {
		return nil
	}
	return n.ShiftDuration
}
