// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableAuthorEntity struct {
	ID     *string `json:"id,omitzero"`
	Name   *string `json:"name,omitzero"`
	Source *string `json:"source,omitzero"`
	Email  *string `json:"email,omitzero"`
}

func (n *NullableAuthorEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableAuthorEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableAuthorEntity) GetSource() *string {
	if n == nil {
		return nil
	}
	return n.Source
}

func (n *NullableAuthorEntity) GetEmail() *string {
	if n == nil {
		return nil
	}
	return n.Email
}
