// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableNuncComponentGroupEntity struct {
	ID               *string `json:"id,omitempty"`
	ComponentGroupID *string `json:"component_group_id,omitempty"`
	Name             *string `json:"name,omitempty"`
	Position         *int    `json:"position,omitempty"`
}

func (n *NullableNuncComponentGroupEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableNuncComponentGroupEntity) GetComponentGroupID() *string {
	if n == nil {
		return nil
	}
	return n.ComponentGroupID
}

func (n *NullableNuncComponentGroupEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableNuncComponentGroupEntity) GetPosition() *int {
	if n == nil {
		return nil
	}
	return n.Position
}
