// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type NullableIntegrationEntity struct {
	ID              *string    `json:"id,omitempty"`
	IntegrationName *string    `json:"integration_name,omitempty"`
	IntegrationSlug *string    `json:"integration_slug,omitempty"`
	DisplayName     *string    `json:"display_name,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
}

func (n NullableIntegrationEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableIntegrationEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableIntegrationEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableIntegrationEntity) GetIntegrationName() *string {
	if n == nil {
		return nil
	}
	return n.IntegrationName
}

func (n *NullableIntegrationEntity) GetIntegrationSlug() *string {
	if n == nil {
		return nil
	}
	return n.IntegrationSlug
}

func (n *NullableIntegrationEntity) GetDisplayName() *string {
	if n == nil {
		return nil
	}
	return n.DisplayName
}

func (n *NullableIntegrationEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}
