// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIGroupingEntityStrategyEntity struct {
	Substring *NullableSignalsAPIGroupingEntityStrategyEntitySubstringEntity `json:"substring,omitempty"`
}

func (n *NullableSignalsAPIGroupingEntityStrategyEntity) GetSubstring() *NullableSignalsAPIGroupingEntityStrategyEntitySubstringEntity {
	if n == nil {
		return nil
	}
	return n.Substring
}
