// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// NullableTicketingPriorityEntity - Ticketing_PriorityEntity model
type NullableTicketingPriorityEntity struct {
	ID        *string    `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Position  *int       `json:"position,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (n NullableTicketingPriorityEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableTicketingPriorityEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableTicketingPriorityEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableTicketingPriorityEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableTicketingPriorityEntity) GetPosition() *int {
	if n == nil {
		return nil
	}
	return n.Position
}

func (n *NullableTicketingPriorityEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NullableTicketingPriorityEntity) GetUpdatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.UpdatedAt
}
