// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type NullableIntegrationsAwsConnectionEntityConnectionStatus string

const (
	NullableIntegrationsAwsConnectionEntityConnectionStatusPendingSetup       NullableIntegrationsAwsConnectionEntityConnectionStatus = "pending_setup"
	NullableIntegrationsAwsConnectionEntityConnectionStatusRoleAssumed        NullableIntegrationsAwsConnectionEntityConnectionStatus = "role_assumed"
	NullableIntegrationsAwsConnectionEntityConnectionStatusCantAssumeRole     NullableIntegrationsAwsConnectionEntityConnectionStatus = "cant_assume_role"
	NullableIntegrationsAwsConnectionEntityConnectionStatusInvalidPermissions NullableIntegrationsAwsConnectionEntityConnectionStatus = "invalid_permissions"
	NullableIntegrationsAwsConnectionEntityConnectionStatusValidated          NullableIntegrationsAwsConnectionEntityConnectionStatus = "validated"
)

func (e NullableIntegrationsAwsConnectionEntityConnectionStatus) ToPointer() *NullableIntegrationsAwsConnectionEntityConnectionStatus {
	return &e
}
func (e *NullableIntegrationsAwsConnectionEntityConnectionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending_setup":
		fallthrough
	case "role_assumed":
		fallthrough
	case "cant_assume_role":
		fallthrough
	case "invalid_permissions":
		fallthrough
	case "validated":
		*e = NullableIntegrationsAwsConnectionEntityConnectionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NullableIntegrationsAwsConnectionEntityConnectionStatus: %v", v)
	}
}

// NullableIntegrationsAwsConnectionEntity - Integrations_Aws_ConnectionEntity model
type NullableIntegrationsAwsConnectionEntity struct {
	ID                *string                                                  `json:"id,omitzero"`
	AwsAccountID      *string                                                  `json:"aws_account_id,omitzero"`
	TargetArn         *string                                                  `json:"target_arn,omitzero"`
	ExternalID        *string                                                  `json:"external_id,omitzero"`
	ConnectionStatus  *NullableIntegrationsAwsConnectionEntityConnectionStatus `json:"connection_status,omitzero"`
	StatusText        *string                                                  `json:"status_text,omitzero"`
	StatusDescription *string                                                  `json:"status_description,omitzero"`
	EnvironmentID     *string                                                  `json:"environment_id,omitzero"`
	EnvironmentName   *string                                                  `json:"environment_name,omitzero"`
	Regions           []string                                                 `json:"regions,omitzero"`
}

func (n NullableIntegrationsAwsConnectionEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableIntegrationsAwsConnectionEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableIntegrationsAwsConnectionEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableIntegrationsAwsConnectionEntity) GetAwsAccountID() *string {
	if n == nil {
		return nil
	}
	return n.AwsAccountID
}

func (n *NullableIntegrationsAwsConnectionEntity) GetTargetArn() *string {
	if n == nil {
		return nil
	}
	return n.TargetArn
}

func (n *NullableIntegrationsAwsConnectionEntity) GetExternalID() *string {
	if n == nil {
		return nil
	}
	return n.ExternalID
}

func (n *NullableIntegrationsAwsConnectionEntity) GetConnectionStatus() *NullableIntegrationsAwsConnectionEntityConnectionStatus {
	if n == nil {
		return nil
	}
	return n.ConnectionStatus
}

func (n *NullableIntegrationsAwsConnectionEntity) GetStatusText() *string {
	if n == nil {
		return nil
	}
	return n.StatusText
}

func (n *NullableIntegrationsAwsConnectionEntity) GetStatusDescription() *string {
	if n == nil {
		return nil
	}
	return n.StatusDescription
}

func (n *NullableIntegrationsAwsConnectionEntity) GetEnvironmentID() *string {
	if n == nil {
		return nil
	}
	return n.EnvironmentID
}

func (n *NullableIntegrationsAwsConnectionEntity) GetEnvironmentName() *string {
	if n == nil {
		return nil
	}
	return n.EnvironmentName
}

func (n *NullableIntegrationsAwsConnectionEntity) GetRegions() []string {
	if n == nil {
		return nil
	}
	return n.Regions
}
