// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableMetricsTicketFunnelMetricsEntityGroupingsEntity struct {
	// The bucket size for the data
	BucketSize *string `json:"bucket_size,omitzero"`
}

func (n *NullableMetricsTicketFunnelMetricsEntityGroupingsEntity) GetBucketSize() *string {
	if n == nil {
		return nil
	}
	return n.BucketSize
}
