// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableSignalsAPIAnalyticsNoiseMetricsEntityMetricEntity struct {
	// The time bucket
	Bucket *string `json:"bucket,omitempty"`
	// The total number of alerts
	TotalAlerts *int `json:"total_alerts,omitempty"`
	// The number of alerts marked as noise
	NoisyAlerts *int `json:"noisy_alerts,omitempty"`
	// The percentage of alerts that are noise
	Percentage *float32 `json:"percentage,omitempty"`
}

func (n *NullableSignalsAPIAnalyticsNoiseMetricsEntityMetricEntity) GetBucket() *string {
	if n == nil {
		return nil
	}
	return n.Bucket
}

func (n *NullableSignalsAPIAnalyticsNoiseMetricsEntityMetricEntity) GetTotalAlerts() *int {
	if n == nil {
		return nil
	}
	return n.TotalAlerts
}

func (n *NullableSignalsAPIAnalyticsNoiseMetricsEntityMetricEntity) GetNoisyAlerts() *int {
	if n == nil {
		return nil
	}
	return n.NoisyAlerts
}

func (n *NullableSignalsAPIAnalyticsNoiseMetricsEntityMetricEntity) GetPercentage() *float32 {
	if n == nil {
		return nil
	}
	return n.Percentage
}
