// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NullableImportsImportErrorEntityResourceEntity struct {
	ResourceID   *string `json:"resource_id,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
	Name         *string `json:"name,omitempty"`
}

func (n *NullableImportsImportErrorEntityResourceEntity) GetResourceID() *string {
	if n == nil {
		return nil
	}
	return n.ResourceID
}

func (n *NullableImportsImportErrorEntityResourceEntity) GetResourceType() *string {
	if n == nil {
		return nil
	}
	return n.ResourceType
}

func (n *NullableImportsImportErrorEntityResourceEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}
