// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// NullableIncidentEntityLabels - A key/value of labels
type NullableIncidentEntityLabels struct {
}

type NullableIncidentEntityRetroExport struct {
}

// NullableIncidentEntity - IncidentEntity model
type NullableIncidentEntity struct {
	// UUID of the Incident
	ID *string `json:"id,omitempty"`
	// Name of the incident
	Name *string `json:"name,omitempty"`
	// The time the incident was opened
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The time the incident started
	StartedAt *time.Time `json:"started_at,omitempty"`
	// The time the incident was archived
	DiscardedAt           *time.Time `json:"discarded_at,omitempty"`
	Summary               *string    `json:"summary,omitempty"`
	CustomerImpactSummary *string    `json:"customer_impact_summary,omitempty"`
	Description           *string    `json:"description,omitempty"`
	// The type/slug of the current milestone. Will be one of the currently configured milestones for the given incident.
	CurrentMilestone *string `json:"current_milestone,omitempty"`
	// Incident number
	Number                  *int                                   `json:"number,omitempty"`
	Priority                *string                                `json:"priority,omitempty"`
	Severity                *string                                `json:"severity,omitempty"`
	SeverityColor           *string                                `json:"severity_color,omitempty"`
	SeverityImpact          *string                                `json:"severity_impact,omitempty"`
	SeverityCondition       *string                                `json:"severity_condition,omitempty"`
	TagList                 []string                               `json:"tag_list,omitempty"`
	IncidentType            *NullableSuccinctEntity                `json:"incident_type,omitempty"`
	SeverityImpactObject    *NullableSeverityMatrixImpactEntity    `json:"severity_impact_object,omitempty"`
	SeverityConditionObject *NullableSeverityMatrixConditionEntity `json:"severity_condition_object,omitempty"`
	PrivateID               *string                                `json:"private_id,omitempty"`
	OrganizationID          *string                                `json:"organization_id,omitempty"`
	// DEPRECATED: Please use lifecycle phases instead
	Milestones            []IncidentsMilestoneEntity            `json:"milestones,omitempty"`
	LifecyclePhases       []IncidentsLifecyclePhaseEntity       `json:"lifecycle_phases,omitempty"`
	LifecycleMeasurements []IncidentsLifecycleMeasurementEntity `json:"lifecycle_measurements,omitempty"`
	Active                *bool                                 `json:"active,omitempty"`
	// A key/value of labels
	Labels               *NullableIncidentEntityLabels   `json:"labels,omitempty"`
	RoleAssignments      []IncidentsRoleAssignmentEntity `json:"role_assignments,omitempty"`
	StatusPages          []IncidentsStatusPageEntity     `json:"status_pages,omitempty"`
	IncidentURL          *string                         `json:"incident_url,omitempty"`
	PrivateStatusPageURL *string                         `json:"private_status_page_url,omitempty"`
	Organization         *NullableOrganizationEntity     `json:"organization,omitempty"`
	CustomersImpacted    *int                            `json:"customers_impacted,omitempty"`
	MonetaryImpact       *int                            `json:"monetary_impact,omitempty"`
	MonetaryImpactCents  *int                            `json:"monetary_impact_cents,omitempty"`
	LastUpdate           *string                         `json:"last_update,omitempty"`
	LastNote             *NullableEventNoteEntity        `json:"last_note,omitempty"`
	ReportID             *string                         `json:"report_id,omitempty"`
	AiIncidentSummary    *string                         `json:"ai_incident_summary,omitempty"`
	Services             []SuccinctEntity                `json:"services,omitempty"`
	Environments         []SuccinctEntity                `json:"environments,omitempty"`
	Functionalities      []SuccinctEntity                `json:"functionalities,omitempty"`
	ChannelName          *string                         `json:"channel_name,omitempty"`
	ChannelReference     *string                         `json:"channel_reference,omitempty"`
	ChannelID            *string                         `json:"channel_id,omitempty"`
	// inoperative: 0, operational: 1, archived: 2
	ChannelStatus     *string                           `json:"channel_status,omitempty"`
	IncidentTickets   []TicketingTicketEntity           `json:"incident_tickets,omitempty"`
	Ticket            *NullableTicketingTicketEntity    `json:"ticket,omitempty"`
	Impacts           []IncidentsImpactEntity           `json:"impacts,omitempty"`
	ConferenceBridges []IncidentsConferenceBridgeEntity `json:"conference_bridges,omitempty"`
	IncidentChannels  []IncidentsChannelEntity          `json:"incident_channels,omitempty"`
	// A list of objects attached to this item. Can be one of: LinkEntity, CustomerSupportIssueEntity, or GenericAttachmentEntity
	RetroExports      []NullableIncidentEntityRetroExport    `json:"retro_exports,omitempty"`
	CreatedBy         *NullableAuthorEntity                  `json:"created_by,omitempty"`
	ContextObject     *NullableIncidentsContextObjectEntity  `json:"context_object,omitempty"`
	TeamAssignments   []IncidentsTeamAssignmentEntityLite    `json:"team_assignments,omitempty"`
	Conversations     []ConversationsAPIEntitiesReference    `json:"conversations,omitempty"`
	CustomFields      []CustomFieldsFieldValue               `json:"custom_fields,omitempty"`
	FieldRequirements []IncidentEntityFieldRequirementEntity `json:"field_requirements,omitempty"`
}

func (n NullableIncidentEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableIncidentEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableIncidentEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableIncidentEntity) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *NullableIncidentEntity) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NullableIncidentEntity) GetStartedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.StartedAt
}

func (n *NullableIncidentEntity) GetDiscardedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.DiscardedAt
}

func (n *NullableIncidentEntity) GetSummary() *string {
	if n == nil {
		return nil
	}
	return n.Summary
}

func (n *NullableIncidentEntity) GetCustomerImpactSummary() *string {
	if n == nil {
		return nil
	}
	return n.CustomerImpactSummary
}

func (n *NullableIncidentEntity) GetDescription() *string {
	if n == nil {
		return nil
	}
	return n.Description
}

func (n *NullableIncidentEntity) GetCurrentMilestone() *string {
	if n == nil {
		return nil
	}
	return n.CurrentMilestone
}

func (n *NullableIncidentEntity) GetNumber() *int {
	if n == nil {
		return nil
	}
	return n.Number
}

func (n *NullableIncidentEntity) GetPriority() *string {
	if n == nil {
		return nil
	}
	return n.Priority
}

func (n *NullableIncidentEntity) GetSeverity() *string {
	if n == nil {
		return nil
	}
	return n.Severity
}

func (n *NullableIncidentEntity) GetSeverityColor() *string {
	if n == nil {
		return nil
	}
	return n.SeverityColor
}

func (n *NullableIncidentEntity) GetSeverityImpact() *string {
	if n == nil {
		return nil
	}
	return n.SeverityImpact
}

func (n *NullableIncidentEntity) GetSeverityCondition() *string {
	if n == nil {
		return nil
	}
	return n.SeverityCondition
}

func (n *NullableIncidentEntity) GetTagList() []string {
	if n == nil {
		return nil
	}
	return n.TagList
}

func (n *NullableIncidentEntity) GetIncidentType() *NullableSuccinctEntity {
	if n == nil {
		return nil
	}
	return n.IncidentType
}

func (n *NullableIncidentEntity) GetSeverityImpactObject() *NullableSeverityMatrixImpactEntity {
	if n == nil {
		return nil
	}
	return n.SeverityImpactObject
}

func (n *NullableIncidentEntity) GetSeverityConditionObject() *NullableSeverityMatrixConditionEntity {
	if n == nil {
		return nil
	}
	return n.SeverityConditionObject
}

func (n *NullableIncidentEntity) GetPrivateID() *string {
	if n == nil {
		return nil
	}
	return n.PrivateID
}

func (n *NullableIncidentEntity) GetOrganizationID() *string {
	if n == nil {
		return nil
	}
	return n.OrganizationID
}

func (n *NullableIncidentEntity) GetMilestones() []IncidentsMilestoneEntity {
	if n == nil {
		return nil
	}
	return n.Milestones
}

func (n *NullableIncidentEntity) GetLifecyclePhases() []IncidentsLifecyclePhaseEntity {
	if n == nil {
		return nil
	}
	return n.LifecyclePhases
}

func (n *NullableIncidentEntity) GetLifecycleMeasurements() []IncidentsLifecycleMeasurementEntity {
	if n == nil {
		return nil
	}
	return n.LifecycleMeasurements
}

func (n *NullableIncidentEntity) GetActive() *bool {
	if n == nil {
		return nil
	}
	return n.Active
}

func (n *NullableIncidentEntity) GetLabels() *NullableIncidentEntityLabels {
	if n == nil {
		return nil
	}
	return n.Labels
}

func (n *NullableIncidentEntity) GetRoleAssignments() []IncidentsRoleAssignmentEntity {
	if n == nil {
		return nil
	}
	return n.RoleAssignments
}

func (n *NullableIncidentEntity) GetStatusPages() []IncidentsStatusPageEntity {
	if n == nil {
		return nil
	}
	return n.StatusPages
}

func (n *NullableIncidentEntity) GetIncidentURL() *string {
	if n == nil {
		return nil
	}
	return n.IncidentURL
}

func (n *NullableIncidentEntity) GetPrivateStatusPageURL() *string {
	if n == nil {
		return nil
	}
	return n.PrivateStatusPageURL
}

func (n *NullableIncidentEntity) GetOrganization() *NullableOrganizationEntity {
	if n == nil {
		return nil
	}
	return n.Organization
}

func (n *NullableIncidentEntity) GetCustomersImpacted() *int {
	if n == nil {
		return nil
	}
	return n.CustomersImpacted
}

func (n *NullableIncidentEntity) GetMonetaryImpact() *int {
	if n == nil {
		return nil
	}
	return n.MonetaryImpact
}

func (n *NullableIncidentEntity) GetMonetaryImpactCents() *int {
	if n == nil {
		return nil
	}
	return n.MonetaryImpactCents
}

func (n *NullableIncidentEntity) GetLastUpdate() *string {
	if n == nil {
		return nil
	}
	return n.LastUpdate
}

func (n *NullableIncidentEntity) GetLastNote() *NullableEventNoteEntity {
	if n == nil {
		return nil
	}
	return n.LastNote
}

func (n *NullableIncidentEntity) GetReportID() *string {
	if n == nil {
		return nil
	}
	return n.ReportID
}

func (n *NullableIncidentEntity) GetAiIncidentSummary() *string {
	if n == nil {
		return nil
	}
	return n.AiIncidentSummary
}

func (n *NullableIncidentEntity) GetServices() []SuccinctEntity {
	if n == nil {
		return nil
	}
	return n.Services
}

func (n *NullableIncidentEntity) GetEnvironments() []SuccinctEntity {
	if n == nil {
		return nil
	}
	return n.Environments
}

func (n *NullableIncidentEntity) GetFunctionalities() []SuccinctEntity {
	if n == nil {
		return nil
	}
	return n.Functionalities
}

func (n *NullableIncidentEntity) GetChannelName() *string {
	if n == nil {
		return nil
	}
	return n.ChannelName
}

func (n *NullableIncidentEntity) GetChannelReference() *string {
	if n == nil {
		return nil
	}
	return n.ChannelReference
}

func (n *NullableIncidentEntity) GetChannelID() *string {
	if n == nil {
		return nil
	}
	return n.ChannelID
}

func (n *NullableIncidentEntity) GetChannelStatus() *string {
	if n == nil {
		return nil
	}
	return n.ChannelStatus
}

func (n *NullableIncidentEntity) GetIncidentTickets() []TicketingTicketEntity {
	if n == nil {
		return nil
	}
	return n.IncidentTickets
}

func (n *NullableIncidentEntity) GetTicket() *NullableTicketingTicketEntity {
	if n == nil {
		return nil
	}
	return n.Ticket
}

func (n *NullableIncidentEntity) GetImpacts() []IncidentsImpactEntity {
	if n == nil {
		return nil
	}
	return n.Impacts
}

func (n *NullableIncidentEntity) GetConferenceBridges() []IncidentsConferenceBridgeEntity {
	if n == nil {
		return nil
	}
	return n.ConferenceBridges
}

func (n *NullableIncidentEntity) GetIncidentChannels() []IncidentsChannelEntity {
	if n == nil {
		return nil
	}
	return n.IncidentChannels
}

func (n *NullableIncidentEntity) GetRetroExports() []NullableIncidentEntityRetroExport {
	if n == nil {
		return nil
	}
	return n.RetroExports
}

func (n *NullableIncidentEntity) GetCreatedBy() *NullableAuthorEntity {
	if n == nil {
		return nil
	}
	return n.CreatedBy
}

func (n *NullableIncidentEntity) GetContextObject() *NullableIncidentsContextObjectEntity {
	if n == nil {
		return nil
	}
	return n.ContextObject
}

func (n *NullableIncidentEntity) GetTeamAssignments() []IncidentsTeamAssignmentEntityLite {
	if n == nil {
		return nil
	}
	return n.TeamAssignments
}

func (n *NullableIncidentEntity) GetConversations() []ConversationsAPIEntitiesReference {
	if n == nil {
		return nil
	}
	return n.Conversations
}

func (n *NullableIncidentEntity) GetCustomFields() []CustomFieldsFieldValue {
	if n == nil {
		return nil
	}
	return n.CustomFields
}

func (n *NullableIncidentEntity) GetFieldRequirements() []IncidentEntityFieldRequirementEntity {
	if n == nil {
		return nil
	}
	return n.FieldRequirements
}
