// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// NullableTicketingProjectConfigEntityDetails - A config object containing details about the project config. Can be one of: Ticketing::JiraCloud::ProjectConfigEntity, Ticketing::JiraOnprem::ProjectConfigEntity, or Ticketing::Shortcut::ProjectConfigEntity
type NullableTicketingProjectConfigEntityDetails struct {
}

// NullableTicketingProjectConfigEntity - Ticketing_ProjectConfigEntity model
type NullableTicketingProjectConfigEntity struct {
	ID                   *string `json:"id,omitzero"`
	ConnectionID         *string `json:"connection_id,omitzero"`
	ConnectionType       *string `json:"connection_type,omitzero"`
	TicketingProjectID   *string `json:"ticketing_project_id,omitzero"`
	TicketingProjectName *string `json:"ticketing_project_name,omitzero"`
	// A config object containing details about the project config. Can be one of: Ticketing::JiraCloud::ProjectConfigEntity, Ticketing::JiraOnprem::ProjectConfigEntity, or Ticketing::Shortcut::ProjectConfigEntity
	Details *NullableTicketingProjectConfigEntityDetails `json:"details,omitzero"`
}

func (n NullableTicketingProjectConfigEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableTicketingProjectConfigEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NullableTicketingProjectConfigEntity) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *NullableTicketingProjectConfigEntity) GetConnectionID() *string {
	if n == nil {
		return nil
	}
	return n.ConnectionID
}

func (n *NullableTicketingProjectConfigEntity) GetConnectionType() *string {
	if n == nil {
		return nil
	}
	return n.ConnectionType
}

func (n *NullableTicketingProjectConfigEntity) GetTicketingProjectID() *string {
	if n == nil {
		return nil
	}
	return n.TicketingProjectID
}

func (n *NullableTicketingProjectConfigEntity) GetTicketingProjectName() *string {
	if n == nil {
		return nil
	}
	return n.TicketingProjectName
}

func (n *NullableTicketingProjectConfigEntity) GetDetails() *NullableTicketingProjectConfigEntityDetails {
	if n == nil {
		return nil
	}
	return n.Details
}
