// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PatchScimGroupOperation struct {
	// The operation to perform. Options are add, remove, replace
	Op string `json:"op"`
	// The path to the attribute to be modified
	Path string `json:"path"`
}

func (p *PatchScimGroupOperation) GetOp() string {
	if p == nil {
		return ""
	}
	return p.Op
}

func (p *PatchScimGroupOperation) GetPath() string {
	if p == nil {
		return ""
	}
	return p.Path
}

// PatchScimGroup - SCIM endpoint to partially update a Team (Colloquial for Group in the SCIM protocol). Supports adding, removing, or replacing members using SCIM PATCH operations.
type PatchScimGroup struct {
	// An optional trail to log the request
	Trail *string `json:"trail,omitempty"`
	// An array of operations to perform on the group
	Operations []PatchScimGroupOperation `json:"Operations"`
}

func (p *PatchScimGroup) GetTrail() *string {
	if p == nil {
		return nil
	}
	return p.Trail
}

func (p *PatchScimGroup) GetOperations() []PatchScimGroupOperation {
	if p == nil {
		return []PatchScimGroupOperation{}
	}
	return p.Operations
}
