// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PostMortemsReasonEntity - PostMortems_ReasonEntity model
type PostMortemsReasonEntity struct {
	ID            *string                             `json:"id,omitempty"`
	Summary       *string                             `json:"summary,omitempty"`
	Position      *int                                `json:"position,omitempty"`
	CreatedBy     *NullableAuthorEntity               `json:"created_by,omitempty"`
	Conversations []ConversationsAPIEntitiesReference `json:"conversations,omitempty"`
}

func (p *PostMortemsReasonEntity) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PostMortemsReasonEntity) GetSummary() *string {
	if p == nil {
		return nil
	}
	return p.Summary
}

func (p *PostMortemsReasonEntity) GetPosition() *int {
	if p == nil {
		return nil
	}
	return p.Position
}

func (p *PostMortemsReasonEntity) GetCreatedBy() *NullableAuthorEntity {
	if p == nil {
		return nil
	}
	return p.CreatedBy
}

func (p *PostMortemsReasonEntity) GetConversations() []ConversationsAPIEntitiesReference {
	if p == nil {
		return nil
	}
	return p.Conversations
}
