// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// PostMortemsQuestionTypeEntityPaginated - PostMortems_QuestionTypeEntityPaginated model
type PostMortemsQuestionTypeEntityPaginated struct {
	Data       []PostMortemsQuestionTypeEntity `json:"data,omitzero"`
	Pagination *NullablePaginationEntity       `json:"pagination,omitzero"`
}

func (p PostMortemsQuestionTypeEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostMortemsQuestionTypeEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostMortemsQuestionTypeEntityPaginated) GetData() []PostMortemsQuestionTypeEntity {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostMortemsQuestionTypeEntityPaginated) GetPagination() *NullablePaginationEntity {
	if p == nil {
		return nil
	}
	return p.Pagination
}
