// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PostMortemsSectionFieldEntity - PostMortems_SectionFieldEntity model
type PostMortemsSectionFieldEntity struct {
	ID    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

func (p *PostMortemsSectionFieldEntity) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PostMortemsSectionFieldEntity) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PostMortemsSectionFieldEntity) GetValue() *string {
	if p == nil {
		return nil
	}
	return p.Value
}
