// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PublicAPIV1IncidentsSuccinctEntity struct {
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Number *int    `json:"number,omitempty"`
}

func (p *PublicAPIV1IncidentsSuccinctEntity) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PublicAPIV1IncidentsSuccinctEntity) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PublicAPIV1IncidentsSuccinctEntity) GetNumber() *int {
	if p == nil {
		return nil
	}
	return p.Number
}
