// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// PublicAPIV1IncidentsTranscriptEntity - PublicAPI_V1_Incidents_TranscriptEntity model
type PublicAPIV1IncidentsTranscriptEntity struct {
	// The unique identifier for the transcript entry
	ID *string `json:"id,omitzero"`
	// The speaker for the transcript entry
	Speaker *string `json:"speaker,omitzero"`
	// The start time for the transcript entry
	Start *int `json:"start,omitzero"`
	// The end time for the transcript entry
	Until *int `json:"until,omitzero"`
	// The words spoken for the transcript entry
	Words *string `json:"words,omitzero"`
	// The time the transcript entry was created
	CreatedAt *time.Time `json:"created_at,omitzero"`
	// The time the transcript entry was last updated
	UpdatedAt *time.Time            `json:"updated_at,omitzero"`
	Author    *NullableAuthorEntity `json:"author,omitzero"`
}

func (p PublicAPIV1IncidentsTranscriptEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIV1IncidentsTranscriptEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetSpeaker() *string {
	if p == nil {
		return nil
	}
	return p.Speaker
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetStart() *int {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetUntil() *int {
	if p == nil {
		return nil
	}
	return p.Until
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetWords() *string {
	if p == nil {
		return nil
	}
	return p.Words
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *PublicAPIV1IncidentsTranscriptEntity) GetAuthor() *NullableAuthorEntity {
	if p == nil {
		return nil
	}
	return p.Author
}
