// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// PublicAPIV1RoleEntity - PublicAPI_V1_RoleEntity model
type PublicAPIV1RoleEntity struct {
	ID          *string                       `json:"id,omitempty"`
	Name        *string                       `json:"name,omitempty"`
	Slug        *string                       `json:"slug,omitempty"`
	Description *string                       `json:"description,omitempty"`
	CreatedAt   *time.Time                    `json:"created_at,omitempty"`
	UpdatedAt   *time.Time                    `json:"updated_at,omitempty"`
	BuiltIn     *bool                         `json:"built_in,omitempty"`
	ReadOnly    *bool                         `json:"read_only,omitempty"`
	Permissions []PublicAPIV1PermissionEntity `json:"permissions,omitempty"`
}

func (p PublicAPIV1RoleEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicAPIV1RoleEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PublicAPIV1RoleEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PublicAPIV1RoleEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PublicAPIV1RoleEntity) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *PublicAPIV1RoleEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PublicAPIV1RoleEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *PublicAPIV1RoleEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *PublicAPIV1RoleEntity) GetBuiltIn() *bool {
	if o == nil {
		return nil
	}
	return o.BuiltIn
}

func (o *PublicAPIV1RoleEntity) GetReadOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ReadOnly
}

func (o *PublicAPIV1RoleEntity) GetPermissions() []PublicAPIV1PermissionEntity {
	if o == nil {
		return nil
	}
	return o.Permissions
}
