// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ReportsDataPointEntity struct {
	Key   *string `json:"key,omitzero"`
	Value *int    `json:"value,omitzero"`
}

func (r *ReportsDataPointEntity) GetKey() *string {
	if r == nil {
		return nil
	}
	return r.Key
}

func (r *ReportsDataPointEntity) GetValue() *int {
	if r == nil {
		return nil
	}
	return r.Value
}
