// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RetrospectivesTemplateEntity - Retrospectives_TemplateEntity model
type RetrospectivesTemplateEntity struct {
	ID          *string                                             `json:"id,omitempty"`
	Name        *string                                             `json:"name,omitempty"`
	Description *string                                             `json:"description,omitempty"`
	IsDefault   *bool                                               `json:"is_default,omitempty"`
	Sections    []RetrospectivesTemplateEntityIncidentSectionEntity `json:"sections,omitempty"`
	Fields      []RetrospectivesFieldEntity                         `json:"fields,omitempty"`
}

func (r *RetrospectivesTemplateEntity) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RetrospectivesTemplateEntity) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RetrospectivesTemplateEntity) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RetrospectivesTemplateEntity) GetIsDefault() *bool {
	if r == nil {
		return nil
	}
	return r.IsDefault
}

func (r *RetrospectivesTemplateEntity) GetSections() []RetrospectivesTemplateEntityIncidentSectionEntity {
	if r == nil {
		return nil
	}
	return r.Sections
}

func (r *RetrospectivesTemplateEntity) GetFields() []RetrospectivesFieldEntity {
	if r == nil {
		return nil
	}
	return r.Fields
}
