// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// RoleEntityPaginated model
type RoleEntityPaginated struct {
	Data       []PublicAPIV1RoleEntity   `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (r RoleEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoleEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoleEntityPaginated) GetData() []PublicAPIV1RoleEntity {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RoleEntityPaginated) GetPagination() *NullablePaginationEntity {
	if r == nil {
		return nil
	}
	return r.Pagination
}
