// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunbooksElementDynamicSelectEntitySelectOptionEntity struct {
	Label *string `json:"label,omitempty"`
	Value *string `json:"value,omitempty"`
}

func (r *RunbooksElementDynamicSelectEntitySelectOptionEntity) GetLabel() *string {
	if r == nil {
		return nil
	}
	return r.Label
}

func (r *RunbooksElementDynamicSelectEntitySelectOptionEntity) GetValue() *string {
	if r == nil {
		return nil
	}
	return r.Value
}
