// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunbooksElementEntity struct {
	ID            *string                                     `json:"id,omitempty"`
	Type          *string                                     `json:"type,omitempty"`
	Markdown      *NullableRunbooksElementMarkdownEntity      `json:"markdown,omitempty"`
	Textarea      *NullableRunbooksElementTextareaEntity      `json:"textarea,omitempty"`
	Input         *NullableRunbooksElementInputEntity         `json:"input,omitempty"`
	PlainText     *NullableRunbooksElementMarkdownEntity      `json:"plain_text,omitempty"`
	DynamicSelect *NullableRunbooksElementDynamicSelectEntity `json:"dynamic_select,omitempty"`
}

func (o *RunbooksElementEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RunbooksElementEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *RunbooksElementEntity) GetMarkdown() *NullableRunbooksElementMarkdownEntity {
	if o == nil {
		return nil
	}
	return o.Markdown
}

func (o *RunbooksElementEntity) GetTextarea() *NullableRunbooksElementTextareaEntity {
	if o == nil {
		return nil
	}
	return o.Textarea
}

func (o *RunbooksElementEntity) GetInput() *NullableRunbooksElementInputEntity {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *RunbooksElementEntity) GetPlainText() *NullableRunbooksElementMarkdownEntity {
	if o == nil {
		return nil
	}
	return o.PlainText
}

func (o *RunbooksElementEntity) GetDynamicSelect() *NullableRunbooksElementDynamicSelectEntity {
	if o == nil {
		return nil
	}
	return o.DynamicSelect
}
