// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// RunbooksExecutionEntity - Runbooks_ExecutionEntity model
type RunbooksExecutionEntity struct {
	ID                  *string                                           `json:"id,omitzero"`
	Status              *string                                           `json:"status,omitzero"`
	StatusReason        *string                                           `json:"status_reason,omitzero"`
	StatusReasonMessage *string                                           `json:"status_reason_message,omitzero"`
	HasBeenRerun        *bool                                             `json:"has_been_rerun,omitzero"`
	CreatedAt           *time.Time                                        `json:"created_at,omitzero"`
	UpdatedAt           *time.Time                                        `json:"updated_at,omitzero"`
	CreatedBy           *string                                           `json:"created_by,omitzero"`
	Runbook             *NullableSlimRunbookEntity                        `json:"runbook,omitzero"`
	Steps               *NullableRunbooksExecutionStepEntity              `json:"steps,omitzero"`
	ExecutedFor         *NullableRunbooksExecutionEntityExecutedForEntity `json:"executed_for,omitzero"`
}

func (r RunbooksExecutionEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RunbooksExecutionEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RunbooksExecutionEntity) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RunbooksExecutionEntity) GetStatus() *string {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *RunbooksExecutionEntity) GetStatusReason() *string {
	if r == nil {
		return nil
	}
	return r.StatusReason
}

func (r *RunbooksExecutionEntity) GetStatusReasonMessage() *string {
	if r == nil {
		return nil
	}
	return r.StatusReasonMessage
}

func (r *RunbooksExecutionEntity) GetHasBeenRerun() *bool {
	if r == nil {
		return nil
	}
	return r.HasBeenRerun
}

func (r *RunbooksExecutionEntity) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RunbooksExecutionEntity) GetUpdatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *RunbooksExecutionEntity) GetCreatedBy() *string {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *RunbooksExecutionEntity) GetRunbook() *NullableSlimRunbookEntity {
	if r == nil {
		return nil
	}
	return r.Runbook
}

func (r *RunbooksExecutionEntity) GetSteps() *NullableRunbooksExecutionStepEntity {
	if r == nil {
		return nil
	}
	return r.Steps
}

func (r *RunbooksExecutionEntity) GetExecutedFor() *NullableRunbooksExecutionEntityExecutedForEntity {
	if r == nil {
		return nil
	}
	return r.ExecutedFor
}
