// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RunbooksElementEntity struct {
	ID            *string                                     `json:"id,omitempty"`
	Type          *string                                     `json:"type,omitempty"`
	Markdown      *NullableRunbooksElementMarkdownEntity      `json:"markdown,omitempty"`
	Textarea      *NullableRunbooksElementTextareaEntity      `json:"textarea,omitempty"`
	Input         *NullableRunbooksElementInputEntity         `json:"input,omitempty"`
	PlainText     *NullableRunbooksElementMarkdownEntity      `json:"plain_text,omitempty"`
	DynamicSelect *NullableRunbooksElementDynamicSelectEntity `json:"dynamic_select,omitempty"`
}

func (r *RunbooksElementEntity) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RunbooksElementEntity) GetType() *string {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RunbooksElementEntity) GetMarkdown() *NullableRunbooksElementMarkdownEntity {
	if r == nil {
		return nil
	}
	return r.Markdown
}

func (r *RunbooksElementEntity) GetTextarea() *NullableRunbooksElementTextareaEntity {
	if r == nil {
		return nil
	}
	return r.Textarea
}

func (r *RunbooksElementEntity) GetInput() *NullableRunbooksElementInputEntity {
	if r == nil {
		return nil
	}
	return r.Input
}

func (r *RunbooksElementEntity) GetPlainText() *NullableRunbooksElementMarkdownEntity {
	if r == nil {
		return nil
	}
	return r.PlainText
}

func (r *RunbooksElementEntity) GetDynamicSelect() *NullableRunbooksElementDynamicSelectEntity {
	if r == nil {
		return nil
	}
	return r.DynamicSelect
}
