// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// ScheduleEntityPaginated model
type ScheduleEntityPaginated struct {
	Data       []ScheduleEntity          `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (s ScheduleEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ScheduleEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ScheduleEntityPaginated) GetData() []ScheduleEntity {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *ScheduleEntityPaginated) GetPagination() *NullablePaginationEntity {
	if s == nil {
		return nil
	}
	return s.Pagination
}
