// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ScheduleEntity struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Integration *string `json:"integration,omitempty"`
	Discarded   *bool   `json:"discarded,omitempty"`
}

func (s *ScheduleEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ScheduleEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ScheduleEntity) GetIntegration() *string {
	if s == nil {
		return nil
	}
	return s.Integration
}

func (s *ScheduleEntity) GetDiscarded() *bool {
	if s == nil {
		return nil
	}
	return s.Discarded
}
