// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ScheduleEntityPaginated model
type ScheduleEntityPaginated struct {
	Data       []ScheduleEntity          `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (s *ScheduleEntityPaginated) GetData() []ScheduleEntity {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *ScheduleEntityPaginated) GetPagination() *NullablePaginationEntity {
	if s == nil {
		return nil
	}
	return s.Pagination
}
