// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ScheduledMaintenancesImpactEntity struct {
	ID        *string                                `json:"id,omitempty"`
	Type      *string                                `json:"type,omitempty"`
	Impact    *NullableSuccinctEntity                `json:"impact,omitempty"`
	Condition *NullableSeverityMatrixConditionEntity `json:"condition,omitempty"`
}

func (s *ScheduledMaintenancesImpactEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ScheduledMaintenancesImpactEntity) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *ScheduledMaintenancesImpactEntity) GetImpact() *NullableSuccinctEntity {
	if s == nil {
		return nil
	}
	return s.Impact
}

func (s *ScheduledMaintenancesImpactEntity) GetCondition() *NullableSeverityMatrixConditionEntity {
	if s == nil {
		return nil
	}
	return s.Condition
}
