// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type ServiceParentDependencyEntity struct {
	ID        *string                `json:"id,omitzero"`
	Notes     *string                `json:"notes,omitzero"`
	CreatedAt *time.Time             `json:"created_at,omitzero"`
	UpdatedAt *time.Time             `json:"updated_at,omitzero"`
	Service   *NullableServiceEntity `json:"service,omitzero"`
	Type      *string                `json:"type,omitzero"`
}

func (s ServiceParentDependencyEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceParentDependencyEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceParentDependencyEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ServiceParentDependencyEntity) GetNotes() *string {
	if s == nil {
		return nil
	}
	return s.Notes
}

func (s *ServiceParentDependencyEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ServiceParentDependencyEntity) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ServiceParentDependencyEntity) GetService() *NullableServiceEntity {
	if s == nil {
		return nil
	}
	return s.Service
}

func (s *ServiceParentDependencyEntity) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}
