// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// ServiceEntityLite model
type ServiceEntityLite struct {
	ID            *string    `json:"id,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Description   *string    `json:"description,omitempty"`
	Slug          *string    `json:"slug,omitempty"`
	ServiceTier   *int       `json:"service_tier,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	AllowedParams []string   `json:"allowed_params,omitempty"`
	// An object of label key and values
	Labels                map[string]any `json:"labels,omitempty"`
	AlertOnAdd            *bool          `json:"alert_on_add,omitempty"`
	AutoAddRespondingTeam *bool          `json:"auto_add_responding_team,omitempty"`
}

func (s ServiceEntityLite) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceEntityLite) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceEntityLite) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ServiceEntityLite) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ServiceEntityLite) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *ServiceEntityLite) GetSlug() *string {
	if s == nil {
		return nil
	}
	return s.Slug
}

func (s *ServiceEntityLite) GetServiceTier() *int {
	if s == nil {
		return nil
	}
	return s.ServiceTier
}

func (s *ServiceEntityLite) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ServiceEntityLite) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ServiceEntityLite) GetAllowedParams() []string {
	if s == nil {
		return nil
	}
	return s.AllowedParams
}

func (s *ServiceEntityLite) GetLabels() map[string]any {
	if s == nil {
		return nil
	}
	return s.Labels
}

func (s *ServiceEntityLite) GetAlertOnAdd() *bool {
	if s == nil {
		return nil
	}
	return s.AlertOnAdd
}

func (s *ServiceEntityLite) GetAutoAddRespondingTeam() *bool {
	if s == nil {
		return nil
	}
	return s.AutoAddRespondingTeam
}
