// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// ServiceDependencyEntity model
type ServiceDependencyEntity struct {
	ID               *string                `json:"id,omitzero"`
	Notes            *string                `json:"notes,omitzero"`
	CreatedAt        *time.Time             `json:"created_at,omitzero"`
	UpdatedAt        *time.Time             `json:"updated_at,omitzero"`
	Service          *NullableServiceEntity `json:"service,omitzero"`
	ConnectedService *NullableServiceEntity `json:"connected_service,omitzero"`
}

func (s ServiceDependencyEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServiceDependencyEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServiceDependencyEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ServiceDependencyEntity) GetNotes() *string {
	if s == nil {
		return nil
	}
	return s.Notes
}

func (s *ServiceDependencyEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ServiceDependencyEntity) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ServiceDependencyEntity) GetService() *NullableServiceEntity {
	if s == nil {
		return nil
	}
	return s.Service
}

func (s *ServiceDependencyEntity) GetConnectedService() *NullableServiceEntity {
	if s == nil {
		return nil
	}
	return s.ConnectedService
}
