// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SeverityEntityPaginated model
type SeverityEntityPaginated struct {
	Data       []SeverityEntity          `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (s *SeverityEntityPaginated) GetData() []SeverityEntity {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SeverityEntityPaginated) GetPagination() *NullablePaginationEntity {
	if s == nil {
		return nil
	}
	return s.Pagination
}
