// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SeverityMatrixConditionEntity - SeverityMatrix_ConditionEntity model
type SeverityMatrixConditionEntity struct {
	ID   *string `json:"id,omitzero"`
	Name *string `json:"name,omitzero"`
	// Position is used to determine ordering of conditions in API responses and dropdowns. The condition with the lowest position (typically 0) will be considered the Default Condition
	Position *int `json:"position,omitzero"`
}

func (s *SeverityMatrixConditionEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SeverityMatrixConditionEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SeverityMatrixConditionEntity) GetPosition() *int {
	if s == nil {
		return nil
	}
	return s.Position
}
