// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity - Signals_API_OnCallSchedulePreviewEntity_RotationPreviewEntity model
type SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity struct {
	Name   *string                                                   `json:"name,omitempty"`
	Color  *string                                                   `json:"color,omitempty"`
	Shifts []SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity `json:"shifts,omitempty"`
}

func (o *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *SignalsAPIOnCallSchedulePreviewEntityRotationPreviewEntity) GetShifts() []SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity {
	if o == nil {
		return nil
	}
	return o.Shifts
}
