// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// SignalsAPIEscalationPolicyEntity - Signals_API_EscalationPolicyEntity model
type SignalsAPIEscalationPolicyEntity struct {
	ID           *string                                              `json:"id,omitzero"`
	Name         *string                                              `json:"name,omitzero"`
	Description  *string                                              `json:"description,omitzero"`
	Default      *bool                                                `json:"default,omitzero"`
	Repetitions  *int                                                 `json:"repetitions,omitzero"`
	Steps        []SignalsAPIEscalationPolicyStepEntity               `json:"steps,omitzero"`
	HandoffStep  *NullableSignalsAPIEscalationPolicyHandoffStepEntity `json:"handoff_step,omitzero"`
	CreatedBy    *NullableAuthorEntity                                `json:"created_by,omitzero"`
	CreatedAt    *time.Time                                           `json:"created_at,omitzero"`
	UpdatedAt    *time.Time                                           `json:"updated_at,omitzero"`
	StepStrategy *string                                              `json:"step_strategy,omitzero"`
	// Priority-specific policies for dynamic escalation policies
	NotificationPriorityPolicies []SignalsAPINotificationPriorityPolicyEntity `json:"notification_priority_policies,omitzero"`
}

func (s SignalsAPIEscalationPolicyEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIEscalationPolicyEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIEscalationPolicyEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPIEscalationPolicyEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SignalsAPIEscalationPolicyEntity) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SignalsAPIEscalationPolicyEntity) GetDefault() *bool {
	if s == nil {
		return nil
	}
	return s.Default
}

func (s *SignalsAPIEscalationPolicyEntity) GetRepetitions() *int {
	if s == nil {
		return nil
	}
	return s.Repetitions
}

func (s *SignalsAPIEscalationPolicyEntity) GetSteps() []SignalsAPIEscalationPolicyStepEntity {
	if s == nil {
		return nil
	}
	return s.Steps
}

func (s *SignalsAPIEscalationPolicyEntity) GetHandoffStep() *NullableSignalsAPIEscalationPolicyHandoffStepEntity {
	if s == nil {
		return nil
	}
	return s.HandoffStep
}

func (s *SignalsAPIEscalationPolicyEntity) GetCreatedBy() *NullableAuthorEntity {
	if s == nil {
		return nil
	}
	return s.CreatedBy
}

func (s *SignalsAPIEscalationPolicyEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SignalsAPIEscalationPolicyEntity) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *SignalsAPIEscalationPolicyEntity) GetStepStrategy() *string {
	if s == nil {
		return nil
	}
	return s.StepStrategy
}

func (s *SignalsAPIEscalationPolicyEntity) GetNotificationPriorityPolicies() []SignalsAPINotificationPriorityPolicyEntity {
	if s == nil {
		return nil
	}
	return s.NotificationPriorityPolicies
}
