// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SignalsAPIGroupingEntity - Signals_API_GroupingEntity model
type SignalsAPIGroupingEntity struct {
	ID                       *string                                         `json:"id,omitempty"`
	Strategy                 *NullableSignalsAPIGroupingEntityStrategyEntity `json:"strategy,omitempty"`
	Action                   *NullableSignalsAPIGroupingEntityActionEntity   `json:"action,omitempty"`
	ReferenceAlertTimePeriod *string                                         `json:"reference_alert_time_period,omitempty"`
}

func (o *SignalsAPIGroupingEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SignalsAPIGroupingEntity) GetStrategy() *NullableSignalsAPIGroupingEntityStrategyEntity {
	if o == nil {
		return nil
	}
	return o.Strategy
}

func (o *SignalsAPIGroupingEntity) GetAction() *NullableSignalsAPIGroupingEntityActionEntity {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *SignalsAPIGroupingEntity) GetReferenceAlertTimePeriod() *string {
	if o == nil {
		return nil
	}
	return o.ReferenceAlertTimePeriod
}
