// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type SignalsAPIUserNotificationSettingEntity struct {
	ID                   *string                              `json:"id,omitzero"`
	NotificationType     *string                              `json:"notification_type,omitzero"`
	Delay                *string                              `json:"delay,omitzero"`
	NotificationPriority *string                              `json:"notification_priority,omitzero"`
	Destination          *NullableSignalsAPIDestinationEntity `json:"destination,omitzero"`
}

func (s SignalsAPIUserNotificationSettingEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIUserNotificationSettingEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIUserNotificationSettingEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPIUserNotificationSettingEntity) GetNotificationType() *string {
	if s == nil {
		return nil
	}
	return s.NotificationType
}

func (s *SignalsAPIUserNotificationSettingEntity) GetDelay() *string {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *SignalsAPIUserNotificationSettingEntity) GetNotificationPriority() *string {
	if s == nil {
		return nil
	}
	return s.NotificationPriority
}

func (s *SignalsAPIUserNotificationSettingEntity) GetDestination() *NullableSignalsAPIDestinationEntity {
	if s == nil {
		return nil
	}
	return s.Destination
}
