// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignalsAPITargetEntity struct {
	ID         *string `json:"id,omitzero"`
	Name       *string `json:"name,omitzero"`
	Type       *string `json:"type,omitzero"`
	TeamID     *string `json:"team_id,omitzero"`
	IsPageable *bool   `json:"is_pageable,omitzero"`
}

func (s *SignalsAPITargetEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPITargetEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SignalsAPITargetEntity) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *SignalsAPITargetEntity) GetTeamID() *string {
	if s == nil {
		return nil
	}
	return s.TeamID
}

func (s *SignalsAPITargetEntity) GetIsPageable() *bool {
	if s == nil {
		return nil
	}
	return s.IsPageable
}
