// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity struct {
	StartTime *time.Time              `json:"start_time,omitempty"`
	EndTime   *time.Time              `json:"end_time,omitempty"`
	User      *NullableSuccinctEntity `json:"user,omitempty"`
}

func (s SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity) GetStartTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartTime
}

func (o *SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *SignalsAPIOnCallSchedulePreviewEntityShiftPreviewEntity) GetUser() *NullableSuccinctEntity {
	if o == nil {
		return nil
	}
	return o.User
}
