// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// SignalsAPIEmailTargetEntity - Signals_API_EmailTargetEntity model
type SignalsAPIEmailTargetEntity struct {
	ID                   *string                         `json:"id,omitempty"`
	Slug                 *string                         `json:"slug,omitempty"`
	Name                 *string                         `json:"name,omitempty"`
	Description          *string                         `json:"description,omitempty"`
	Email                *string                         `json:"email,omitempty"`
	StatusCel            *string                         `json:"status_cel,omitempty"`
	LevelCel             *string                         `json:"level_cel,omitempty"`
	Target               *NullableSignalsAPITargetEntity `json:"target,omitempty"`
	AllowedSenders       []string                        `json:"allowed_senders,omitempty"`
	Rules                []string                        `json:"rules,omitempty"`
	RuleMatchingStrategy *string                         `json:"rule_matching_strategy,omitempty"`
	CreatedBy            *NullableAuthorEntity           `json:"created_by,omitempty"`
	CreatedAt            *time.Time                      `json:"created_at,omitempty"`
	UpdatedAt            *time.Time                      `json:"updated_at,omitempty"`
	// The team ID that the email target belongs to, if applicable
	TeamID *string `json:"team_id,omitempty"`
}

func (s SignalsAPIEmailTargetEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIEmailTargetEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIEmailTargetEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPIEmailTargetEntity) GetSlug() *string {
	if s == nil {
		return nil
	}
	return s.Slug
}

func (s *SignalsAPIEmailTargetEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SignalsAPIEmailTargetEntity) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SignalsAPIEmailTargetEntity) GetEmail() *string {
	if s == nil {
		return nil
	}
	return s.Email
}

func (s *SignalsAPIEmailTargetEntity) GetStatusCel() *string {
	if s == nil {
		return nil
	}
	return s.StatusCel
}

func (s *SignalsAPIEmailTargetEntity) GetLevelCel() *string {
	if s == nil {
		return nil
	}
	return s.LevelCel
}

func (s *SignalsAPIEmailTargetEntity) GetTarget() *NullableSignalsAPITargetEntity {
	if s == nil {
		return nil
	}
	return s.Target
}

func (s *SignalsAPIEmailTargetEntity) GetAllowedSenders() []string {
	if s == nil {
		return nil
	}
	return s.AllowedSenders
}

func (s *SignalsAPIEmailTargetEntity) GetRules() []string {
	if s == nil {
		return nil
	}
	return s.Rules
}

func (s *SignalsAPIEmailTargetEntity) GetRuleMatchingStrategy() *string {
	if s == nil {
		return nil
	}
	return s.RuleMatchingStrategy
}

func (s *SignalsAPIEmailTargetEntity) GetCreatedBy() *NullableAuthorEntity {
	if s == nil {
		return nil
	}
	return s.CreatedBy
}

func (s *SignalsAPIEmailTargetEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SignalsAPIEmailTargetEntity) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *SignalsAPIEmailTargetEntity) GetTeamID() *string {
	if s == nil {
		return nil
	}
	return s.TeamID
}
