// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SignalsAPIHackerModeEntity - Signals_API_HackerModeEntity model
type SignalsAPIHackerModeEntity struct {
	Enabled *bool   `json:"enabled,omitempty"`
	URLKey  *string `json:"url_key,omitempty"`
	URL     *string `json:"url,omitempty"`
}

func (s *SignalsAPIHackerModeEntity) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

func (s *SignalsAPIHackerModeEntity) GetURLKey() *string {
	if s == nil {
		return nil
	}
	return s.URLKey
}

func (s *SignalsAPIHackerModeEntity) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}
