// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignalsAPIOnCallRestrictionEntity struct {
	StartDay  *string `json:"start_day,omitempty"`
	StartTime *string `json:"start_time,omitempty"`
	EndDay    *string `json:"end_day,omitempty"`
	EndTime   *string `json:"end_time,omitempty"`
}

func (o *SignalsAPIOnCallRestrictionEntity) GetStartDay() *string {
	if o == nil {
		return nil
	}
	return o.StartDay
}

func (o *SignalsAPIOnCallRestrictionEntity) GetStartTime() *string {
	if o == nil {
		return nil
	}
	return o.StartTime
}

func (o *SignalsAPIOnCallRestrictionEntity) GetEndDay() *string {
	if o == nil {
		return nil
	}
	return o.EndDay
}

func (o *SignalsAPIOnCallRestrictionEntity) GetEndTime() *string {
	if o == nil {
		return nil
	}
	return o.EndTime
}
