// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

type SignalsAPIOrganizationOnCallRotationEntity struct {
	ID           *string                              `json:"id,omitempty"`
	Name         *string                              `json:"name,omitempty"`
	Description  *string                              `json:"description,omitempty"`
	TimeZone     *string                              `json:"time_zone,omitempty"`
	CurrentShift *NullableSignalsAPIOnCallShiftEntity `json:"current_shift,omitempty"`
	NextShift    *NullableSignalsAPIOnCallShiftEntity `json:"next_shift,omitempty"`
	CreatedBy    *NullableAuthorEntity                `json:"created_by,omitempty"`
	CreatedAt    *time.Time                           `json:"created_at,omitempty"`
	UpdatedAt    *time.Time                           `json:"updated_at,omitempty"`
}

func (s SignalsAPIOrganizationOnCallRotationEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetTimeZone() *string {
	if s == nil {
		return nil
	}
	return s.TimeZone
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetCurrentShift() *NullableSignalsAPIOnCallShiftEntity {
	if s == nil {
		return nil
	}
	return s.CurrentShift
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetNextShift() *NullableSignalsAPIOnCallShiftEntity {
	if s == nil {
		return nil
	}
	return s.NextShift
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetCreatedBy() *NullableAuthorEntity {
	if s == nil {
		return nil
	}
	return s.CreatedBy
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}
