// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignalsAPIOnCallRestrictionEntity struct {
	StartDay  *string `json:"start_day,omitzero"`
	StartTime *string `json:"start_time,omitzero"`
	EndDay    *string `json:"end_day,omitzero"`
	EndTime   *string `json:"end_time,omitzero"`
}

func (s *SignalsAPIOnCallRestrictionEntity) GetStartDay() *string {
	if s == nil {
		return nil
	}
	return s.StartDay
}

func (s *SignalsAPIOnCallRestrictionEntity) GetStartTime() *string {
	if s == nil {
		return nil
	}
	return s.StartTime
}

func (s *SignalsAPIOnCallRestrictionEntity) GetEndDay() *string {
	if s == nil {
		return nil
	}
	return s.EndDay
}

func (s *SignalsAPIOnCallRestrictionEntity) GetEndTime() *string {
	if s == nil {
		return nil
	}
	return s.EndTime
}
