// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TagEntityPaginated model
type TagEntityPaginated struct {
	Data       []TagEntity               `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (t *TagEntityPaginated) GetData() []TagEntity {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TagEntityPaginated) GetPagination() *NullablePaginationEntity {
	if t == nil {
		return nil
	}
	return t.Pagination
}
