// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// TaskEntityPaginated model
type TaskEntityPaginated struct {
	Data       []TaskEntity              `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (t TaskEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskEntityPaginated) GetData() []TaskEntity {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TaskEntityPaginated) GetPagination() *NullablePaginationEntity {
	if t == nil {
		return nil
	}
	return t.Pagination
}
