// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// TaskListEntity model
type TaskListEntity struct {
	ID            *string               `json:"id,omitzero"`
	Name          *string               `json:"name,omitzero"`
	Description   *string               `json:"description,omitzero"`
	CreatedAt     *time.Time            `json:"created_at,omitzero"`
	UpdatedAt     *time.Time            `json:"updated_at,omitzero"`
	CreatedBy     *NullableAuthorEntity `json:"created_by,omitzero"`
	TaskListItems []TaskListItemEntity  `json:"task_list_items,omitzero"`
}

func (t TaskListEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskListEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskListEntity) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}

func (t *TaskListEntity) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaskListEntity) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TaskListEntity) GetCreatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.CreatedAt
}

func (t *TaskListEntity) GetUpdatedAt() *time.Time {
	if t == nil {
		return nil
	}
	return t.UpdatedAt
}

func (t *TaskListEntity) GetCreatedBy() *NullableAuthorEntity {
	if t == nil {
		return nil
	}
	return t.CreatedBy
}

func (t *TaskListEntity) GetTaskListItems() []TaskListItemEntity {
	if t == nil {
		return nil
	}
	return t.TaskListItems
}
