// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// TeamEntityPaginated model
type TeamEntityPaginated struct {
	Data       []TeamEntity              `json:"data,omitzero"`
	Pagination *NullablePaginationEntity `json:"pagination,omitzero"`
}

func (t TeamEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TeamEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TeamEntityPaginated) GetData() []TeamEntity {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TeamEntityPaginated) GetPagination() *NullablePaginationEntity {
	if t == nil {
		return nil
	}
	return t.Pagination
}
