// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TeamEntityPaginated model
type TeamEntityPaginated struct {
	Data       []TeamEntity              `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (t *TeamEntityPaginated) GetData() []TeamEntity {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TeamEntityPaginated) GetPagination() *NullablePaginationEntity {
	if t == nil {
		return nil
	}
	return t.Pagination
}
