// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateRunbookOwner - An object representing a Team that owns the runbook
type UpdateRunbookOwner struct {
	ID *string `json:"id,omitempty"`
}

func (u *UpdateRunbookOwner) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

type UpdateRunbookSeverity struct {
	ID *string `json:"id,omitempty"`
}

func (u *UpdateRunbookSeverity) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

type UpdateRunbookService struct {
	ID *string `json:"id,omitempty"`
}

func (u *UpdateRunbookService) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

type Environment struct {
	ID *string `json:"id,omitempty"`
}

func (e *Environment) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

type UpdateRunbookAttachmentRule struct {
	// The JSON logic for the attaching the runbook
	Logic string `json:"logic"`
	// The user data for the rule
	UserData *string `json:"user_data,omitempty"`
}

func (u *UpdateRunbookAttachmentRule) GetLogic() string {
	if u == nil {
		return ""
	}
	return u.Logic
}

func (u *UpdateRunbookAttachmentRule) GetUserData() *string {
	if u == nil {
		return nil
	}
	return u.UserData
}

type UpdateRunbookRule struct {
	// The JSON logic for the rule
	Logic string `json:"logic"`
	// The user data for the rule
	UserData *string `json:"user_data,omitempty"`
}

func (u *UpdateRunbookRule) GetLogic() string {
	if u == nil {
		return ""
	}
	return u.Logic
}

func (u *UpdateRunbookRule) GetUserData() *string {
	if u == nil {
		return nil
	}
	return u.UserData
}

type UpdateRunbookStep struct {
	// ID of step to be updated
	StepID *string `json:"step_id,omitempty"`
	// Name for step
	Name string `json:"name"`
	// ID of action to use for this step.
	ActionID string             `json:"action_id"`
	Rule     *UpdateRunbookRule `json:"rule,omitempty"`
}

func (u *UpdateRunbookStep) GetStepID() *string {
	if u == nil {
		return nil
	}
	return u.StepID
}

func (u *UpdateRunbookStep) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateRunbookStep) GetActionID() string {
	if u == nil {
		return ""
	}
	return u.ActionID
}

func (u *UpdateRunbookStep) GetRule() *UpdateRunbookRule {
	if u == nil {
		return nil
	}
	return u.Rule
}

// UpdateRunbook - Update a runbook and any attachment rules associated with it. This endpoint is used to configure nearly everything
// about a runbook, including but not limited to the steps, environments, attachment rules, and severities.
type UpdateRunbook struct {
	Name        *string `json:"name,omitempty"`
	Summary     *string `json:"summary,omitempty"`
	Description *string `json:"description,omitempty"`
	// Whether or not this runbook is a tutorial runbook
	Tutorial *bool `json:"tutorial,omitempty"`
	// An object representing a Team that owns the runbook
	Owner          *UpdateRunbookOwner          `json:"owner,omitempty"`
	Severities     []UpdateRunbookSeverity      `json:"severities,omitempty"`
	Services       []UpdateRunbookService       `json:"services,omitempty"`
	Environments   []Environment                `json:"environments,omitempty"`
	AttachmentRule *UpdateRunbookAttachmentRule `json:"attachment_rule,omitempty"`
	Steps          []UpdateRunbookStep          `json:"steps,omitempty"`
	// Whether or not this runbook should be automatically attached to restricted incidents. Note that setting this to `true` will prevent it from being attached to public incidents, even manually. Defaults to `false`.
	AutoAttachToRestrictedIncidents *bool `json:"auto_attach_to_restricted_incidents,omitempty"`
}

func (u *UpdateRunbook) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateRunbook) GetSummary() *string {
	if u == nil {
		return nil
	}
	return u.Summary
}

func (u *UpdateRunbook) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateRunbook) GetTutorial() *bool {
	if u == nil {
		return nil
	}
	return u.Tutorial
}

func (u *UpdateRunbook) GetOwner() *UpdateRunbookOwner {
	if u == nil {
		return nil
	}
	return u.Owner
}

func (u *UpdateRunbook) GetSeverities() []UpdateRunbookSeverity {
	if u == nil {
		return nil
	}
	return u.Severities
}

func (u *UpdateRunbook) GetServices() []UpdateRunbookService {
	if u == nil {
		return nil
	}
	return u.Services
}

func (u *UpdateRunbook) GetEnvironments() []Environment {
	if u == nil {
		return nil
	}
	return u.Environments
}

func (u *UpdateRunbook) GetAttachmentRule() *UpdateRunbookAttachmentRule {
	if u == nil {
		return nil
	}
	return u.AttachmentRule
}

func (u *UpdateRunbook) GetSteps() []UpdateRunbookStep {
	if u == nil {
		return nil
	}
	return u.Steps
}

func (u *UpdateRunbook) GetAutoAttachToRestrictedIncidents() *bool {
	if u == nil {
		return nil
	}
	return u.AutoAttachToRestrictedIncidents
}
