// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateIncidentTask - Update a task's attributes
type UpdateIncidentTask struct {
	// The title of the task.
	Title *string `json:"title,omitempty"`
	// A description of what the task is for.
	Description *string `json:"description,omitempty"`
	// The state of the task. One of: open, in_progress, cancelled, done
	State *string `json:"state,omitempty"`
	// The ID of the user assigned to the task.
	AssigneeID *string `json:"assignee_id,omitempty"`
	// The due date of the task. Relative values are supported such as '5m'
	DueAt *string `json:"due_at,omitempty"`
}

func (u *UpdateIncidentTask) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateIncidentTask) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateIncidentTask) GetState() *string {
	if u == nil {
		return nil
	}
	return u.State
}

func (u *UpdateIncidentTask) GetAssigneeID() *string {
	if u == nil {
		return nil
	}
	return u.AssigneeID
}

func (u *UpdateIncidentTask) GetDueAt() *string {
	if u == nil {
		return nil
	}
	return u.DueAt
}
