// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdatePostMortemQuestionsQuestion struct {
	// ID of a question
	ID *string `json:"id,omitempty"`
	// title of a question
	Title *string `json:"title,omitempty"`
	// tooltip of a question
	Tooltip *string `json:"tooltip,omitempty"`
}

func (u *UpdatePostMortemQuestionsQuestion) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdatePostMortemQuestionsQuestion) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdatePostMortemQuestionsQuestion) GetTooltip() *string {
	if u == nil {
		return nil
	}
	return u.Tooltip
}

// UpdatePostMortemQuestions - Update the questions configured to be provided and filled out on future retrospective reports.
type UpdatePostMortemQuestions struct {
	MakeSwaggerWork *string                             `json:"_make_swagger_work_,omitempty"`
	Questions       []UpdatePostMortemQuestionsQuestion `json:"questions,omitempty"`
}

func (u *UpdatePostMortemQuestions) GetMakeSwaggerWork() *string {
	if u == nil {
		return nil
	}
	return u.MakeSwaggerWork
}

func (u *UpdatePostMortemQuestions) GetQuestions() []UpdatePostMortemQuestionsQuestion {
	if u == nil {
		return nil
	}
	return u.Questions
}
