// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// UpdateChange - Update a change entry
type UpdateChange struct {
	Summary     *string           `json:"summary,omitzero"`
	Description *string           `json:"description,omitzero"`
	Labels      map[string]string `json:"labels,omitzero"`
}

func (u UpdateChange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateChange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateChange) GetSummary() *string {
	if u == nil {
		return nil
	}
	return u.Summary
}

func (u *UpdateChange) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateChange) GetLabels() map[string]string {
	if u == nil {
		return nil
	}
	return u.Labels
}
