// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateIncidentImpactPutImpact struct {
	ID          string `json:"id"`
	ConditionID string `json:"condition_id"`
}

func (u *UpdateIncidentImpactPutImpact) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateIncidentImpactPutImpact) GetConditionID() string {
	if u == nil {
		return ""
	}
	return u.ConditionID
}

type UpdateIncidentImpactPutStatusPage struct {
	ID              string `json:"id"`
	IntegrationSlug string `json:"integration_slug"`
}

func (u *UpdateIncidentImpactPutStatusPage) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateIncidentImpactPutStatusPage) GetIntegrationSlug() string {
	if u == nil {
		return ""
	}
	return u.IntegrationSlug
}

// UpdateIncidentImpactPut - Allows updating an incident's impacted infrastructure, with the option to
// move the incident into a different milestone and provide a note to update
// the incident timeline and any attached status pages. If this method is
// requested with the PUT verb, impacts will be completely replaced with the
// information in the request body, even if not provided (effectively clearing
// all impacts). If this method is requested with the PATCH verb, the provided
// impacts will be added or updated, but no impacts will be removed.
type UpdateIncidentImpactPut struct {
	Note        *string                             `json:"note,omitempty"`
	Milestone   *string                             `json:"milestone,omitempty"`
	Impact      []UpdateIncidentImpactPutImpact     `json:"impact,omitempty"`
	StatusPages []UpdateIncidentImpactPutStatusPage `json:"status_pages,omitempty"`
}

func (u *UpdateIncidentImpactPut) GetNote() *string {
	if u == nil {
		return nil
	}
	return u.Note
}

func (u *UpdateIncidentImpactPut) GetMilestone() *string {
	if u == nil {
		return nil
	}
	return u.Milestone
}

func (u *UpdateIncidentImpactPut) GetImpact() []UpdateIncidentImpactPutImpact {
	if u == nil {
		return nil
	}
	return u.Impact
}

func (u *UpdateIncidentImpactPut) GetStatusPages() []UpdateIncidentImpactPutStatusPage {
	if u == nil {
		return nil
	}
	return u.StatusPages
}
