// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

type UpdateIncidentTypeImpact struct {
	// The id of impact
	ID string `json:"id"`
	// The id of the condition
	ConditionID string `json:"condition_id"`
}

func (u *UpdateIncidentTypeImpact) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateIncidentTypeImpact) GetConditionID() string {
	if u == nil {
		return ""
	}
	return u.ConditionID
}

type UpdateIncidentTypeTemplate struct {
	Description           *string `json:"description,omitzero"`
	CustomerImpactSummary *string `json:"customer_impact_summary,omitzero"`
	// A labels hash of keys and values
	Labels   map[string]string `json:"labels,omitzero"`
	Severity *string           `json:"severity,omitzero"`
	Priority *string           `json:"priority,omitzero"`
	// List of tags for the incident
	TagList []string `json:"tag_list,omitzero"`
	// List of ids of Runbooks to attach to incidents created from this type
	RunbookIds      []string `json:"runbook_ids,omitzero"`
	PrivateIncident *bool    `json:"private_incident,omitzero"`
	// List of ids of teams to be assigned to incidents
	TeamIds []string `json:"team_ids,omitzero"`
	// An array of impact/condition combinations
	Impacts []UpdateIncidentTypeImpact `json:"impacts,omitzero"`
}

func (u UpdateIncidentTypeTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIncidentTypeTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateIncidentTypeTemplate) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateIncidentTypeTemplate) GetCustomerImpactSummary() *string {
	if u == nil {
		return nil
	}
	return u.CustomerImpactSummary
}

func (u *UpdateIncidentTypeTemplate) GetLabels() map[string]string {
	if u == nil {
		return nil
	}
	return u.Labels
}

func (u *UpdateIncidentTypeTemplate) GetSeverity() *string {
	if u == nil {
		return nil
	}
	return u.Severity
}

func (u *UpdateIncidentTypeTemplate) GetPriority() *string {
	if u == nil {
		return nil
	}
	return u.Priority
}

func (u *UpdateIncidentTypeTemplate) GetTagList() []string {
	if u == nil {
		return nil
	}
	return u.TagList
}

func (u *UpdateIncidentTypeTemplate) GetRunbookIds() []string {
	if u == nil {
		return nil
	}
	return u.RunbookIds
}

func (u *UpdateIncidentTypeTemplate) GetPrivateIncident() *bool {
	if u == nil {
		return nil
	}
	return u.PrivateIncident
}

func (u *UpdateIncidentTypeTemplate) GetTeamIds() []string {
	if u == nil {
		return nil
	}
	return u.TeamIds
}

func (u *UpdateIncidentTypeTemplate) GetImpacts() []UpdateIncidentTypeImpact {
	if u == nil {
		return nil
	}
	return u.Impacts
}

// UpdateIncidentType - Update a single incident type from its ID
type UpdateIncidentType struct {
	Name string `json:"name"`
	// A description of the incident type
	Description *string                    `json:"description,omitzero"`
	Template    UpdateIncidentTypeTemplate `json:"template"`
}

func (u *UpdateIncidentType) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateIncidentType) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateIncidentType) GetTemplate() UpdateIncidentTypeTemplate {
	if u == nil {
		return UpdateIncidentTypeTemplate{}
	}
	return u.Template
}
