// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateSignalsWebhookTarget - Update a Signals webhook target by ID
type UpdateSignalsWebhookTarget struct {
	// The webhook target's name.
	Name *string `json:"name,omitempty"`
	// An optional detailed description of the webhook target.
	Description *string `json:"description,omitempty"`
	// The URL that the webhook target will notify.
	URL *string `json:"url,omitempty"`
	// An optional secret we will provide in the `FH-Signature` header
	// when sending a payload to the webhook target. This key will not be
	// shown in any response once configured.
	//
	SigningKey *string `json:"signing_key,omitempty"`
}

func (u *UpdateSignalsWebhookTarget) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSignalsWebhookTarget) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateSignalsWebhookTarget) GetURL() *string {
	if u == nil {
		return nil
	}
	return u.URL
}

func (u *UpdateSignalsWebhookTarget) GetSigningKey() *string {
	if u == nil {
		return nil
	}
	return u.SigningKey
}
