// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateIncidentRole - Update a single incident role from its ID
type UpdateIncidentRole struct {
	Name        *string `json:"name,omitzero"`
	Summary     *string `json:"summary,omitzero"`
	Description *string `json:"description,omitzero"`
}

func (u *UpdateIncidentRole) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateIncidentRole) GetSummary() *string {
	if u == nil {
		return nil
	}
	return u.Summary
}

func (u *UpdateIncidentRole) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}
