// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateIncidentLink - Update the external incident link attributes
type UpdateIncidentLink struct {
	DisplayText *string `json:"display_text,omitempty"`
	IconURL     *string `json:"icon_url,omitempty"`
	HrefURL     *string `json:"href_url,omitempty"`
}

func (u *UpdateIncidentLink) GetDisplayText() *string {
	if u == nil {
		return nil
	}
	return u.DisplayText
}

func (u *UpdateIncidentLink) GetIconURL() *string {
	if u == nil {
		return nil
	}
	return u.IconURL
}

func (u *UpdateIncidentLink) GetHrefURL() *string {
	if u == nil {
		return nil
	}
	return u.HrefURL
}
