// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateAwsConnection - Update the AWS connection with the provided data.
type UpdateAwsConnection struct {
	AwsAccountID     *string `json:"aws_account_id,omitzero"`
	TargetArn        *string `json:"target_arn,omitzero"`
	ConnectionStatus *string `json:"connection_status,omitzero"`
}

func (u *UpdateAwsConnection) GetAwsAccountID() *string {
	if u == nil {
		return nil
	}
	return u.AwsAccountID
}

func (u *UpdateAwsConnection) GetTargetArn() *string {
	if u == nil {
		return nil
	}
	return u.TargetArn
}

func (u *UpdateAwsConnection) GetConnectionStatus() *string {
	if u == nil {
		return nil
	}
	return u.ConnectionStatus
}
