// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateIncidentNote - Updates the body of a note
type UpdateIncidentNote struct {
	Body string `json:"body"`
}

func (o *UpdateIncidentNote) GetBody() string {
	if o == nil {
		return ""
	}
	return o.Body
}
