// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateNuncLink - Update a link to be displayed on a FireHydrant status page
type UpdateNuncLink struct {
	DisplayText *string `json:"display_text,omitempty"`
	IconURL     *string `json:"icon_url,omitempty"`
	HrefURL     *string `json:"href_url,omitempty"`
}

func (u *UpdateNuncLink) GetDisplayText() *string {
	if u == nil {
		return nil
	}
	return u.DisplayText
}

func (u *UpdateNuncLink) GetIconURL() *string {
	if u == nil {
		return nil
	}
	return u.IconURL
}

func (u *UpdateNuncLink) GetHrefURL() *string {
	if u == nil {
		return nil
	}
	return u.HrefURL
}
