// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdatePostMortemField - Update a field value on a post mortem report
type UpdatePostMortemField struct {
	Value string `json:"value"`
}

func (u *UpdatePostMortemField) GetValue() string {
	if u == nil {
		return ""
	}
	return u.Value
}
