// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateSeverityMatrixCondition - Update a severity matrix condition
type UpdateSeverityMatrixCondition struct {
	Name *string `json:"name,omitzero"`
	// Position is used to determine ordering of conditions in API responses and dropdowns. The condition with the lowest position (typically 0) will be considered the Default Condition
	Position *int `json:"position,omitzero"`
}

func (u *UpdateSeverityMatrixCondition) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSeverityMatrixCondition) GetPosition() *int {
	if u == nil {
		return nil
	}
	return u.Position
}
