// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
	"time"
)

// UserEntity model
type UserEntity struct {
	ID                                  *string                                            `json:"id,omitempty"`
	Name                                *string                                            `json:"name,omitempty"`
	Email                               *string                                            `json:"email,omitempty"`
	SlackUserID                         *string                                            `json:"slack_user_id,omitempty"`
	SlackLinked                         *bool                                              `json:"slack_linked?,omitempty"`
	CreatedAt                           *time.Time                                         `json:"created_at,omitempty"`
	UpdatedAt                           *time.Time                                         `json:"updated_at,omitempty"`
	SignalsEnabledNotificationTypes     []string                                           `json:"signals_enabled_notification_types,omitempty"`
	SignalsNotificationPolicyCompliance []SignalsAPINotificationPolicyItemComplianceEntity `json:"signals_notification_policy_compliance,omitempty"`
}

func (u UserEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserEntity) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserEntity) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UserEntity) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserEntity) GetSlackUserID() *string {
	if u == nil {
		return nil
	}
	return u.SlackUserID
}

func (u *UserEntity) GetSlackLinked() *bool {
	if u == nil {
		return nil
	}
	return u.SlackLinked
}

func (u *UserEntity) GetCreatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserEntity) GetUpdatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

func (u *UserEntity) GetSignalsEnabledNotificationTypes() []string {
	if u == nil {
		return nil
	}
	return u.SignalsEnabledNotificationTypes
}

func (u *UserEntity) GetSignalsNotificationPolicyCompliance() []SignalsAPINotificationPolicyItemComplianceEntity {
	if u == nil {
		return nil
	}
	return u.SignalsNotificationPolicyCompliance
}
