// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/firehydrant/firehydrant-go-sdk/internal/utils"
)

// WebhooksEntitiesWebhookEntityPaginated - Webhooks_Entities_WebhookEntityPaginated model
type WebhooksEntitiesWebhookEntityPaginated struct {
	Data       []WebhooksEntitiesWebhookEntity `json:"data,omitzero"`
	Pagination *NullablePaginationEntity       `json:"pagination,omitzero"`
}

func (w WebhooksEntitiesWebhookEntityPaginated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhooksEntitiesWebhookEntityPaginated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhooksEntitiesWebhookEntityPaginated) GetData() []WebhooksEntitiesWebhookEntity {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WebhooksEntitiesWebhookEntityPaginated) GetPagination() *NullablePaginationEntity {
	if w == nil {
		return nil
	}
	return w.Pagination
}
