workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    firehydrant-oas:
        inputs:
            - location: ./.speakeasy/openapi.json
        registry:
            location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-oas
targets:
    fire-hydrant:
        target: go
        source: firehydrant-oas
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-oas-go-code-samples
            blocking: false
