name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK repo
        uses: actions/checkout@v3
        
      - name: Checkout developers repo
        uses: actions/checkout@v3
        with:
          repository: firehydrant/developers
          path: 'dev-repo'
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          ref: main
          
      - name: Copy OpenAPI spec
        run: |
          mkdir -p .speakeasy
          cp dev-repo/docs/public/openapi3_doc.json .openapi.json
          
      - name: Generate SDK
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          force: ${{ github.event.inputs.force }}
          mode: pr
          set_version: ${{ github.event.inputs.set_version }}
        env:
          github_access_token: ${{ secrets.CROSS_REPO_TOKEN }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}